In [1]:
import pandas as pd
from copy import copy

pd.options.display.max_columns = None
pd.set_option('display.width', None)
#pd.set_option('display.max_rows', None)

In [37]:
combine = pd.read_csv('../data/raw/stats/RU1_players_24-25.csv')
combine['league'] = ['RU1']*len(combine)
combine

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,Value,2CrdY,Fls,Fld,Off,Crs,Int,TklW,OG,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,league
0,Dzhamalutdin Abdulkadyrov,RUS,DF,CSKA Moscow,19,3,2,209,2.3,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.80,0,2,0,0,0,1,2,0,3,0,0.0,1.29,0.00,0.00,0.00,RU1
1,Saminu Abdullahi,NGA,MF,FC Khimki,23,7,4,356,4.0,0,0,0,0,0,0,1,0,0.00,0.00,0.00,0.00,0.00,0.30,0,7,3,0,4,7,2,0,3,1,33.3,0.76,0.25,0.00,0.00,RU1
2,Myenty Abena,SUR,DF,Spartak Moscow,29,7,4,383,4.3,0,0,0,0,0,0,1,0,0.00,0.00,0.00,0.00,0.00,0.70,0,8,6,0,0,2,6,0,0,0,0.0,0.00,0.00,0.00,0.00,RU1
3,Arsen Adamov,RUS,DF,Akhmat Grozny,24,30,29,2563,28.5,1,1,2,1,0,0,0,0,0.04,0.04,0.07,0.04,0.07,2.00,0,11,48,1,40,46,47,0,25,5,20.0,0.88,0.18,0.04,0.20,RU1
4,Denis Adamov,RUS,GK,Zenit,26,4,3,327,3.6,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,1.00,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0.00,0.00,RU1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,Aleksandr Zotov,RUS,MF,Rubin Kazan,33,22,12,1219,13.5,2,0,2,2,0,0,4,0,0.15,0.00,0.15,0.15,0.15,0.15,0,14,15,1,14,15,11,0,7,2,28.6,0.52,0.15,0.29,1.00,RU1
461,Georgi Zotov,RUS,DF,Orenburg,34,7,4,376,4.2,0,1,1,0,0,0,1,0,0.00,0.24,0.24,0.00,0.24,0.05,0,4,6,0,5,9,3,0,5,0,0.0,1.20,0.00,0.00,0.00,RU1
462,Ifet Djakovac,BIH,MF,FK Akron Tolyatti,26,8,6,447,5.0,2,0,2,2,0,0,1,0,0.40,0.00,0.40,0.40,0.40,2.50,0,7,5,0,14,9,8,0,9,3,33.3,1.81,0.60,0.22,0.67,RU1
463,Jan Djapo,SVN,"MF,DF",D'mo Makhachkala,21,16,9,694,7.7,1,0,1,1,0,0,2,0,0.13,0.00,0.13,0.13,0.13,0.50,0,12,3,1,27,8,12,0,12,1,8.3,1.56,0.13,0.08,1.00,RU1
464,Aleksa Djurasovic,SRB,MF,FK Akron Tolyatti,21,30,29,2524,28.0,0,0,0,0,0,0,2,0,0.00,0.00,0.00,0.00,0.00,2.00,0,12,25,0,7,34,27,1,14,2,14.3,0.50,0.07,0.00,0.00,RU1

In [38]:
leagues = ['BE1', 'ES1', 'FR1', 'GB1', 'IT1', 'L1', 'NL1', 'PO1']

In [39]:
for league in leagues:
    df = pd.read_csv(f'../data/raw/stats/{league}_players_24-25.csv')
    df['league'] = [league]*len(df)
    combine = pd.concat([combine, df])
combine

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,Value,2CrdY,Fls,...,Off,Crs,Int,TklW,OG,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,league,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1
0,Dzhamalutdin Abdulkadyrov,RUS,DF,CSKA Moscow,19.0,3.0,2.0,209.0,2.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.8,0.0,2.0,...,0.0,0.0,1.0,2.0,0.0,3.0,0.0,0.0,1.29,0.00,0.00,0.00,RU1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Saminu Abdullahi,NGA,MF,FC Khimki,23.0,7.0,4.0,356.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.00,0.00,0.00,0.00,0.00,0.3,0.0,7.0,...,0.0,4.0,7.0,2.0,0.0,3.0,1.0,33.3,0.76,0.25,0.00,0.00,RU1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Myenty Abena,SUR,DF,Spartak Moscow,29.0,7.0,4.0,383.0,4.3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.00,0.00,0.00,0.00,0.00,0.7,0.0,8.0,...,0.0,0.0,2.0,6.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,RU1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Arsen Adamov,RUS,DF,Akhmat Grozny,24.0,30.0,29.0,2563.0,28.5,1.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.04,0.04,0.07,0.04,0.07,2.0,0.0,11.0,...,1.0,40.0,46.0,47.0,0.0,25.0,5.0,20.0,0.88,0.18,0.04,0.20,RU1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Denis Adamov,RUS,GK,Zenit,26.0,4.0,3.0,327.0,3.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,RU1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
563,Rodrigo Zalazar,URU,"MF,FW",Braga,24.0,19.0,17.0,1390.0,15.4,4.0,5.0,9.0,3.0,1.0,1.0,4.0,0.0,0.26,0.32,0.58,0.19,0.52,18.0,0.0,21.0,...,0.0,80.0,7.0,17.0,0.0,43.0,9.0,20.9,2.78,0.58,0.07,0.33,PO1,3.6,2.8,4.4,7.2,65.0,76.0,116.0,0.23,0.28,0.52,0.18,0.46
564,Vinicius Zanocelo,BRA,MF,Estoril,23.0,30.0,23.0,2075.0,23.1,2.0,0.0,2.0,2.0,0.0,0.0,8.0,0.0,0.09,0.00,0.09,0.09,0.09,2.5,0.0,48.0,...,0.0,6.0,18.0,33.0,0.0,29.0,8.0,27.6,1.26,0.35,0.07,0.25,PO1,2.2,2.0,0.2,2.3,11.0,106.0,34.0,0.10,0.01,0.11,0.09,0.10
565,Ivan Zlobin,RUS,GK,Famalicão,27.0,15.0,15.0,1350.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.00,0.00,0.00,0.00,0.00,1.5,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,PO1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
566,Karem Zoabi,ISR,"FW,MF",Rio Ave,18.0,12.0,2.0,222.0,2.5,0.0,2.0,2.0,0.0,0.0,0.0,1.0,0.0,0.00,0.81,0.81,0.00,0.81,0.9,0.0,7.0,...,4.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,PO1,0.0,0.0,1.4,1.4,2.0,1.0,11.0,0.00,0.57,0.57,0.00,0.57
567,Nermin Zolotic,BIH,DF,Casa Pia,31.0,7.0,7.0,626.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.00,0.00,0.00,0.00,0.00,0.6,0.0,8.0,...,0.0,1.0,5.0,9.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,PO1,0.0,0.0,0.0,0.0,9.0,29.0,0.0,0.00,0.00,0.00,0.00,0.00

In [61]:
combine.to_csv('../data/raw/stats/combine_players_24-25.csv', index=False)

In [62]:
combine = pd.read_csv('../data/raw/stats/combine_players_24-25.csv')

In [42]:
combine = combine[combine['Pos']!='GK']
combine

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,Value,2CrdY,Fls,...,Off,Crs,Int,TklW,OG,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,league,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1
0,Dzhamalutdin Abdulkadyrov,RUS,DF,CSKA Moscow,19.0,3.0,2.0,209.0,2.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.8,0.0,2.0,...,0.0,0.0,1.0,2.0,0.0,3.0,0.0,0.0,1.29,0.00,0.00,0.00,RU1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Saminu Abdullahi,NGA,MF,FC Khimki,23.0,7.0,4.0,356.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.00,0.00,0.00,0.00,0.00,0.3,0.0,7.0,...,0.0,4.0,7.0,2.0,0.0,3.0,1.0,33.3,0.76,0.25,0.00,0.00,RU1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Myenty Abena,SUR,DF,Spartak Moscow,29.0,7.0,4.0,383.0,4.3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.00,0.00,0.00,0.00,0.00,0.7,0.0,8.0,...,0.0,0.0,2.0,6.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,RU1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Arsen Adamov,RUS,DF,Akhmat Grozny,24.0,30.0,29.0,2563.0,28.5,1.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.04,0.04,0.07,0.04,0.07,2.0,0.0,11.0,...,1.0,40.0,46.0,47.0,0.0,25.0,5.0,20.0,0.88,0.18,0.04,0.20,RU1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Gamid Agalarov,RUS,FW,D'mo Makhachkala,24.0,28.0,26.0,2039.0,22.6,7.0,4.0,11.0,5.0,2.0,3.0,3.0,0.0,0.31,0.18,0.49,0.22,0.40,1.2,0.0,39.0,...,15.0,11.0,4.0,3.0,0.0,40.0,18.0,45.0,1.77,0.80,0.18,0.39,RU1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4779,Yassir Zabiri,MAR,"FW,MF",Famalicão,19.0,5.0,0.0,58.0,0.6,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.55,0.00,1.55,1.55,1.55,0.6,0.0,0.0,...,0.0,4.0,0.0,1.0,0.0,1.0,1.0,100.0,1.55,1.55,1.00,1.00,PO1,0.6,0.6,0.0,0.6,0.0,2.0,4.0,0.98,0.00,0.98,0.98,0.98
4780,Rodrigo Zalazar,URU,"MF,FW",Braga,24.0,19.0,17.0,1390.0,15.4,4.0,5.0,9.0,3.0,1.0,1.0,4.0,0.0,0.26,0.32,0.58,0.19,0.52,18.0,0.0,21.0,...,0.0,80.0,7.0,17.0,0.0,43.0,9.0,20.9,2.78,0.58,0.07,0.33,PO1,3.6,2.8,4.4,7.2,65.0,76.0,116.0,0.23,0.28,0.52,0.18,0.46
4781,Vinicius Zanocelo,BRA,MF,Estoril,23.0,30.0,23.0,2075.0,23.1,2.0,0.0,2.0,2.0,0.0,0.0,8.0,0.0,0.09,0.00,0.09,0.09,0.09,2.5,0.0,48.0,...,0.0,6.0,18.0,33.0,0.0,29.0,8.0,27.6,1.26,0.35,0.07,0.25,PO1,2.2,2.0,0.2,2.3,11.0,106.0,34.0,0.10,0.01,0.11,0.09,0.10
4783,Karem Zoabi,ISR,"FW,MF",Rio Ave,18.0,12.0,2.0,222.0,2.5,0.0,2.0,2.0,0.0,0.0,0.0,1.0,0.0,0.00,0.81,0.81,0.00,0.81,0.9,0.0,7.0,...,4.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,PO1,0.0,0.0,1.4,1.4,2.0,1.0,11.0,0.00,0.57,0.57,0.00,0.57
4784,Nermin Zolotic,BIH,DF,Casa Pia,31.0,7.0,7.0,626.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.00,0.00,0.00,0.00,0.00,0.6,0.0,8.0,...,0.0,1.0,5.0,9.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,PO1,0.0,0.0,0.0,0.0,9.0,29.0,0.0,0.00,0.00,0.00,0.00,0.00

In [17]:
combine.at[83, 'Value'] = 0.4

In [47]:
combine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 51 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Player      4424 non-null   object
 1   Nation      4409 non-null   object
 2   Pos         4424 non-null   object
 3   Squad       4424 non-null   object
 4   Age         4412 non-null   float64
 5   MP          4424 non-null   float64
 6   Starts      4424 non-null   float64
 7   Min         4424 non-null   float64
 8   90s         4424 non-null   float64
 9   Gls         4424 non-null   float64
 10  Ast         4424 non-null   float64
 11  G+A         4424 non-null   float64
 12  G-PK        4424 non-null   float64
 13  PK          4424 non-null   float64
 14  PKatt       4424 non-null   float64
 15  CrdY        4424 non-null   float64
 16  CrdR        4424 non-null   float64
 17  Gls.1       4424 non-null   float64
 18  Ast.1       4424 non-null   float64
 19  G+A.1       4424 non-null   float64
 20  G-PK.1      4424 non-null   float64
 21  G+A-PK      4424 non-null   float64
 22  Value       4424 non-null   float64
 23  2CrdY       4424 non-null   float64
 24  Fls         4424 non-null   float64
 25  Fld         4424 non-null   float64
 26  Off         4424 non-null   float64
 27  Crs         4424 non-null   float64
 28  Int         4424 non-null   float64
 29  TklW        4424 non-null   float64
 30  OG          4424 non-null   float64
 31  Sh          4424 non-null   float64
 32  SoT         4424 non-null   float64
 33  SoT%        4424 non-null   float64
 34  Sh/90       4424 non-null   float64
 35  SoT/90      4424 non-null   float64
 36  G/Sh        4424 non-null   float64
 37  G/SoT       4424 non-null   float64
 38  league      4424 non-null   object
 39  xG          3549 non-null   float64
 40  npxG        3549 non-null   float64
 41  xAG         3549 non-null   float64
 42  npxG+xAG    3549 non-null   float64
 43  PrgC        3549 non-null   float64
 44  PrgP        3549 non-null   float64
 45  PrgR        3549 non-null   float64
 46  xG.1        3549 non-null   float64
 47  xAG.1       3549 non-null   float64
 48  xG+xAG      3549 non-null   float64
 49  npxG.1      3549 non-null   float64
 50  npxG+xAG.1  3549 non-null   float64
dtypes: float64(46), object(5)
memory usage: 1.7+ MB

In [16]:
combine.describe()

,Age,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,Value,2CrdY,Fls,Fld,Off,Crs,Int,TklW,OG,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT
count,4412.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000
mean,24.496827,18.507459,12.806962,1149.167269,12.767812,1.730561,1.209991,2.940552,1.575723,0.154837,0.194620,2.541139,0.124322,0.126809,0.082228,0.209069,0.118025,0.200278,8.006849,0.053119,15.559901,14.634720,2.156193,23.294982,11.164557,13.577758,0.049051,16.562161,5.742089,27.639801,1.454586,0.492082,0.071074,0.195992
std,4.352756,10.863985,10.627382,900.359363,10.004215,3.056364,1.885120,4.364196,2.684925,0.691170,0.792434,2.560527,0.360126,0.302662,0.164823,0.359685,0.295602,0.352166,14.973552,0.231245,13.422120,14.756687,3.956154,36.069086,12.261712,13.063414,0.238863,19.301966,7.948095,21.561982,2.519529,1.655880,0.103104,0.249301
min,15.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,21.000000,9.000000,3.000000,309.000000,3.400000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.800000,0.000000,4.000000,3.000000,0.000000,1.000000,2.000000,3.000000,0.000000,3.000000,1.000000,9.100000,0.440000,0.040000,0.000000,0.000000
50%,24.000000,20.000000,11.000000,1023.000000,11.400000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,2.000000,0.000000,0.030000,0.000000,0.110000,0.030000,0.100000,2.500000,0.000000,13.000000,10.000000,1.000000,8.000000,7.000000,10.000000,0.000000,10.000000,3.000000,28.900000,0.970000,0.250000,0.030000,0.100000
75%,27.000000,28.000000,21.000000,1857.500000,20.625000,2.000000,2.000000,4.000000,2.000000,0.000000,0.000000,4.000000,0.000000,0.170000,0.120000,0.310000,0.160000,0.290000,8.000000,0.000000,24.000000,21.000000,2.000000,29.000000,17.000000,21.000000,0.000000,23.000000,8.000000,40.000000,2.020000,0.660000,0.120000,0.330000
max,41.000000,38.000000,38.000000,3420.000000,38.000000,39.000000,18.000000,47.000000,27.000000,12.000000,12.000000,15.000000,3.000000,12.860000,6.000000,12.860000,12.860000,12.860000,200.000000,2.000000,83.000000,107.000000,57.000000,287.000000,73.000000,78.000000,3.000000,161.000000,85.000000,100.000000,90.000000,90.000000,1.000000,1.000000

In [63]:
combine[combine['Age'].isna()]

Empty DataFrame
Columns: [Player, Nation, Pos, Squad, Age, MP, Starts, Min, 90s, Gls, Ast, G+A, G-PK, PK, PKatt, CrdY, CrdR, Gls.1, Ast.1, G+A.1, G-PK.1, G+A-PK, Value, 2CrdY, Fls, Fld, Off, Crs, Int, TklW, OG, Sh, SoT, SoT%, Sh/90, SoT/90, G/Sh, G/SoT, league, xG, npxG, xAG, npxG+xAG, PrgC, PrgP, PrgR, xG.1, xAG.1, xG+xAG, npxG.1, npxG+xAG.1]
Index: []

[0 rows x 51 columns]

In [60]:
combine.at[1552, 'Age'] = 19

In [2]:
df = pd.read_csv('../data/raw/stats/combine_players_24-25.csv')

In [5]:
df[df['Player'].str.contains('Sperts')]

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,Value,2CrdY,Fls,Fld,Off,Crs,Int,TklW,OG,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,league,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1
359,Eduard Spertsyan,ARM,MF,Krasnodar,24.0,28.0,27.0,2283.0,25.4,11.0,6.0,17.0,7.0,4.0,5.0,2.0,0.0,0.43,0.24,0.67,0.28,0.51,25.0,0.0,39.0,46.0,4.0,122.0,19.0,20.0,0.0,59.0,25.0,42.4,2.33,0.99,0.12,0.28,RU1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df[(df['Squad']=='Krasnodar') & (df['Pos']=='DF')]

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,Value,2CrdY,Fls,Fld,Off,Crs,Int,TklW,OG,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,league,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1
90,Diego,BRA,DF,Krasnodar,25.0,28.0,28.0,2508.0,27.9,1.0,0.0,1.0,1.0,0.0,0.0,7.0,1.0,0.04,0.00,0.04,0.04,0.04,8.0,1.0,34.0,5.0,2.0,6.0,34.0,36.0,0.0,16.0,2.0,12.5,0.57,0.07,0.06,0.5,RU1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,Giovanni Gonzalez,URU,DF,Krasnodar,29.0,22.0,9.0,1043.0,11.6,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.00,0.00,0.00,0.00,0.00,2.5,0.0,14.0,14.0,0.0,34.0,20.0,16.0,0.0,6.0,0.0,0.0,0.52,0.00,0.00,0.0,RU1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
281,Lucas Olaza,URU,DF,Krasnodar,30.0,27.0,27.0,2368.0,26.3,1.0,2.0,3.0,1.0,0.0,0.0,4.0,0.0,0.04,0.08,0.11,0.04,0.11,4.0,0.0,24.0,22.0,1.0,146.0,21.0,38.0,0.0,17.0,2.0,11.8,0.65,0.08,0.06,0.5,RU1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,Kaio Pantaleao,BRA,DF,Krasnodar,28.0,13.0,12.0,992.0,11.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.09,0.00,0.09,0.09,0.09,1.8,0.0,16.0,13.0,1.0,1.0,23.0,15.0,0.0,5.0,1.0,20.0,0.45,0.09,0.20,1.0,RU1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295,Sergei Petrov,RUS,DF,Krasnodar,33.0,27.0,21.0,1697.0,18.9,0.0,1.0,1.0,0.0,0.0,0.0,4.0,0.0,0.00,0.05,0.05,0.00,0.05,0.4,0.0,11.0,13.0,0.0,53.0,27.0,20.0,0.0,6.0,0.0,0.0,0.32,0.00,0.00,0.0,RU1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
381,Vi­tor Tormena,BRA,DF,Krasnodar,28.0,23.0,22.0,2052.0,22.8,2.0,1.0,3.0,2.0,0.0,0.0,4.0,0.0,0.09,0.04,0.13,0.09,0.13,7.0,0.0,25.0,5.0,0.0,1.0,30.0,19.0,0.0,15.0,4.0,26.7,0.66,0.18,0.13,0.5,RU1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
gks = pd.read_csv('../data/raw/stats/combine_gk_24-25.csv')

In [3]:
gks

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,GA,GA90,SoTA,Saves,Save%,W,D,L,CS,CS%,PKatt,PKA,PKsv,PKm,PKsv%,Value,league
0,Denis Adamov,RUS,GK,Zenit,26,4,3,327,3.6,5,1.38,14,9,64.3,2,0,1,1,33.3,0,0,0,0,0.0,1.0,RU1
1,Stanislav Agkatsev,RUS,GK,Krasnodar,22,30,30,2700,30.0,23,0.77,98,79,77.6,20,7,3,15,50.0,4,1,3,0,75.0,7.5,RU1
2,Igor Akinfeev,RUS,GK,CSKA Moscow,38,28,28,2520,28.0,21,0.75,71,53,74.6,15,8,5,12,42.9,3,3,0,0,0.0,1.0,RU1
3,Rustam Yatimov,TJK,GK,Rostov,26,20,20,1771,19.7,26,1.32,81,57,70.4,9,6,5,3,15.0,3,2,0,1,0.0,1.5,RU1
4,Aleksandr Belenov,RUS,GK,Fakel Voronezh,37,12,12,1080,12.0,17,1.42,48,31,64.6,1,4,7,3,25.0,0,0,0,0,0.0,0.1,RU1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,Anatolii Trubin,UKR,GK,Benfica,22,32,32,2880,32.0,28,0.87,97,72,73.2,23,5,4,13,40.6,3,2,1,0,33.3,28.0,PO1
352,Joao Valido,POR,GK,Arouca,24,5,5,450,5.0,6,1.20,19,14,73.7,1,3,1,1,20.0,1,1,0,0,0.0,0.3,PO1
353,Bruno Varela,CPV,GK,Vitoria Guimarães,29,34,34,3060,34.0,37,1.09,98,63,67.3,14,12,8,13,38.2,7,5,0,2,0.0,2.5,PO1
354,Ricardo Velho,POR,GK,Farense,25,28,28,2520,28.0,40,1.43,123,89,72.4,3,9,16,6,21.4,7,6,0,1,0.0,4.0,PO1
355,Ivan Zlobin,RUS,GK,Famalicão,27,15,15,1350,15.0,18,1.20,62,45,72.6,4,7,4,5,33.3,1,1,0,0,0.0,1.5,PO1

In [15]:
duplicates = gks[gks.duplicated(subset=['Player', 'Age', 'Nation'], keep=False)]
duplicates

Empty DataFrame
Columns: [Player, Nation, Pos, Squad, Age, MP, Starts, Min, 90s, GA, GA90, SoTA, Saves, Save%, W, D, L, CS, CS%, PKatt, PKA, PKsv, PKm, PKsv%, Value, league]
Index: []

In [14]:
grouped_gk = duplicates.groupby(['Player', 'Age', 'Nation'])
for _, group in grouped_gk:
    #print(group)
    ind_to_save = group.index[0]
    ind_to_del = group.index[1]
    group = group.reset_index(drop=True)
    if group.at[1, '90s'] > group.at[0, '90s']:
        group.at[0, 'Squad'] = group.at[1, 'Squad']
        group.at[0, 'league'] = group.at[1, 'league']
    for col in group.columns[5:len(group.columns) - 2]:
        group.at[0, col] += group.at[1, col]
    group.at[0, 'GA90'] = group.at[0, 'GA'] / group.at[0, '90s']
    group.at[0, 'Save%'] = group.at[0, 'Saves'] / group.at[0, 'SoTA'] * 100
    group.at[0, 'CS%'] = group.at[0, 'CS'] / group.at[0, 'MP'] * 100
    if group.at[0, 'PKatt'] != 0:
        group.at[0, 'PKsv%'] = group.at[0, 'PKsv'] / (group.at[0, 'PKatt'] - group.at[0, 'PKm']) * 100
    gks.loc[ind_to_save] = group.loc[0]
    gks = gks.drop(ind_to_del)

In [8]:
gks[(gks['PKsv']>0)&(gks['PKm']>0)]

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,GA,GA90,SoTA,Saves,Save%,W,D,L,CS,CS%,PKatt,PKA,PKsv,PKm,PKsv%,Value,league
37,Colin Coosemans,BEL,GK,Anderlecht,31,38,38,3420,38.0,38,1.00,172,136,78.50,17,7,14,17,44.70,4,1,2,1,66.7,1.5,BE1
51,Andreas Jungdal,DEN,GK,Westerlo,22,17,17,1530,17.0,26,1.53,67,46,65.70,7,6,4,3,17.60,6,3,2,1,40.0,1.5,BE1
59,Anthony Moris,LUX,GK,Union SG,34,40,40,3600,40.0,28,0.70,113,86,76.10,24,11,5,20,50.00,3,1,1,1,50.0,1.8,BE1
68,Tom Vandenberghe,BEL,GK,Gent,31,22,22,1980,22.0,55,2.50,118,67,56.78,4,2,16,3,0.14,5,3,1,1,25.0,0.4,BE1
75,Jasper Cillessen,NED,GK,Las Palmas,35,27,27,2335,25.9,42,1.62,123,88,69.10,6,8,13,3,11.10,8,4,3,1,42.9,0.8,ES1
116,Marco Bizot,NED,GK,Brest,33,32,32,2880,32.0,54,1.69,121,76,62.00,14,5,13,10,31.30,10,8,1,1,11.1,3.0,FR1
157,Wladimiro Falcone,ITA,GK,Lecce,29,38,38,3420,38.0,58,1.53,177,127,71.80,8,10,20,9,23.70,10,8,1,1,11.1,3.5,IT1
166,Alex Meret,ITA,GK,Napoli,27,34,34,3005,33.4,25,0.75,81,59,70.40,21,9,4,17,50.00,4,1,2,1,66.7,18.0,IT1
168,Lorenzo Montipo,ITA,GK,Hellas Verona,28,36,36,3240,36.0,64,1.78,161,100,61.50,9,7,20,8,22.20,4,2,1,1,33.3,2.0,IT1
300,Rome-Jayden Owusu-Oduro,NED,GK,AZ Alkmaar,20,28,28,2520,28.0,34,1.21,85,53,61.20,11,9,8,9,32.10,3,1,1,1,50.0,6.0,NL1
316,Gabriel Batista,BRA,GK,Santa Clara,26,34,34,3060,34.0,32,0.94,108,81,74.10,17,6,11,11,32.40,6,4,1,1,20.0,4.0,PO1

In [16]:
gks.to_csv('../data/raw/stats/combine_gk_24-25.csv', index=False)

In [33]:
gks[gks['Player'].str.contains('Carne')]

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,GA,GA90,SoTA,Saves,Save%,W,D,L,CS,CS%,PKatt,PKA,PKsv,PKm,PKsv%,Value,league
153,Marco Carnesecchi,ITA,GK,Atalanta,24,34,34,3060,34.0,34,1.0,130,98,75.4,19,7,8,13,38.2,2,2,0,0,0.0,25.0,IT1