In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

pd.options.display.max_columns = 51
pd.set_option('display.width', None)
pd.set_option('display.max_rows', 10)

In [5]:
gks = pd.read_csv('../data/raw/stats/combine_gk_24-25.csv')

In [2]:
combine = pd.read_csv('../data/raw/stats/combine_players_24-25.csv')
combine

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,Value,2CrdY,Fls,Fld,Off,Crs,Int,TklW,OG,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,league,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1
0,Dzhamalutdin Abdulkadyrov,RUS,DF,CSKA Moscow,19.0,3.0,2.0,209.0,2.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.8,0.0,2.0,0.0,0.0,0.0,1.0,2.0,0.0,3.0,0.0,0.0,1.29,0.00,0.00,0.00,RU1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Saminu Abdullahi,NGA,MF,FC Khimki,23.0,7.0,4.0,356.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.00,0.00,0.00,0.00,0.00,0.3,0.0,7.0,3.0,0.0,4.0,7.0,2.0,0.0,3.0,1.0,33.3,0.76,0.25,0.00,0.00,RU1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Myenty Abena,SUR,DF,Spartak Moscow,29.0,7.0,4.0,383.0,4.3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.00,0.00,0.00,0.00,0.00,0.7,0.0,8.0,6.0,0.0,0.0,2.0,6.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,RU1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Arsen Adamov,RUS,DF,Akhmat Grozny,24.0,30.0,29.0,2563.0,28.5,1.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.04,0.04,0.07,0.04,0.07,2.0,0.0,11.0,48.0,1.0,40.0,46.0,47.0,0.0,25.0,5.0,20.0,0.88,0.18,0.04,0.20,RU1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Gamid Agalarov,RUS,FW,D'mo Makhachkala,24.0,28.0,26.0,2039.0,22.6,7.0,4.0,11.0,5.0,2.0,3.0,3.0,0.0,0.31,0.18,0.49,0.22,0.40,1.2,0.0,39.0,35.0,15.0,11.0,4.0,3.0,0.0,40.0,18.0,45.0,1.77,0.80,0.18,0.39,RU1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4284,Yassir Zabiri,MAR,"FW,MF",Famalicão,19.0,5.0,0.0,58.0,0.6,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.55,0.00,1.55,1.55,1.55,0.6,0.0,0.0,1.0,0.0,4.0,0.0,1.0,0.0,1.0,1.0,100.0,1.55,1.55,1.00,1.00,PO1,0.6,0.6,0.0,0.6,0.0,2.0,4.0,0.98,0.00,0.98,0.98,0.98
4285,Rodrigo Zalazar,URU,"MF,FW",Braga,24.0,19.0,17.0,1390.0,15.4,4.0,5.0,9.0,3.0,1.0,1.0,4.0,0.0,0.26,0.32,0.58,0.19,0.52,18.0,0.0,21.0,38.0,0.0,80.0,7.0,17.0,0.0,43.0,9.0,20.9,2.78,0.58,0.07,0.33,PO1,3.6,2.8,4.4,7.2,65.0,76.0,116.0,0.23,0.28,0.52,0.18,0.46
4286,Vinicius Zanocelo,BRA,MF,Estoril,23.0,30.0,23.0,2075.0,23.1,2.0,0.0,2.0,2.0,0.0,0.0,8.0,0.0,0.09,0.00,0.09,0.09,0.09,2.5,0.0,48.0,24.0,0.0,6.0,18.0,33.0,0.0,29.0,8.0,27.6,1.26,0.35,0.07,0.25,PO1,2.2,2.0,0.2,2.3,11.0,106.0,34.0,0.10,0.01,0.11,0.09,0.10
4287,Karem Zoabi,ISR,"FW,MF",Rio Ave,18.0,12.0,2.0,222.0,2.5,0.0,2.0,2.0,0.0,0.0,0.0,1.0,0.0,0.00,0.81,0.81,0.00,0.81,0.9,0.0,7.0,3.0,4.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,PO1,0.0,0.0,1.4,1.4,2.0,1.0,11.0,0.00,0.57,0.57,0.00,0.57
4288,Nermin Zolotic,BIH,DF,Casa Pia,31.0,7.0,7.0,626.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.00,0.00,0.00,0.00,0.00,0.6,0.0,8.0,3.0,0.0,1.0,5.0,9.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,PO1,0.0,0.0,0.0,0.0,9.0,29.0,0.0,0.00,0.00,0.00,0.00,0.00

In [110]:
duplicates = combine[combine.duplicated(subset=['Player', 'Age', 'Nation'], keep=False)]
duplicates

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,Value,2CrdY,Fls,Fld,Off,Crs,Int,TklW,OG,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,league,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1
232,Ricardo Mangas,POR,DF,Spartak Moscow,26.0,11.0,1.0,200.0,2.2,2.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.90,0.00,0.90,0.90,0.90,2.5,0.0,7.0,5.0,0.0,8.0,6.0,3.0,0.0,3.0,2.0,66.7,1.35,0.90,0.67,1.00,RU1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
437,Adryelson,BRA,DF,Anderlecht,26.0,7.0,6.0,542.0,6.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.17,0.00,0.17,0.17,0.17,3.5,0.0,2.0,4.0,0.0,1.0,10.0,7.0,0.0,6.0,3.0,50.0,0.76,0.38,0.17,0.33,BE1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
485,Bilal Brahimi,ALG,"MF,FW",Sint-Truiden,24.0,21.0,16.0,1487.0,16.5,1.0,3.0,4.0,1.0,0.0,0.0,6.0,1.0,0.06,0.18,0.24,0.06,0.24,1.8,1.0,12.0,19.0,5.0,218.0,13.0,8.0,0.0,65.0,22.0,33.8,3.27,1.11,0.03,0.09,BE1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
523,Olivier Deman,BEL,DF,Antwerp,24.0,10.0,10.0,891.0,9.9,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.00,0.00,0.00,0.00,0.00,3.0,0.0,25.0,19.0,1.0,51.0,28.0,47.0,0.0,12.0,5.0,41.7,0.64,0.26,0.00,0.00,BE1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
527,Djevencio van der Kust,SUR,DF,Beerschot,23.0,3.0,3.0,197.0,2.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.6,0.0,0.0,4.0,0.0,7.0,5.0,6.0,0.0,3.0,0.0,0.0,0.80,0.00,0.00,0.00,BE1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4190,Toni Martinez,ESP,FW,Porto,27.0,1.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,2.5,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,PO1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
4214,Morato,BRA,DF,Benfica,23.0,1.0,1.0,90.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,14.0,0.0,1.0,0.0,0.0,0.0,3.0,2.0,0.0,2.0,0.0,0.0,2.00,0.00,0.00,0.00,PO1,0.1,0.1,0.0,0.1,4.0,10.0,0.0,0.05,0.00,0.05,0.05,0.05
4269,Nehuen Perez,ARG,DF,Porto,24.0,25.0,24.0,2069.0,23.0,1.0,2.0,3.0,1.0,0.0,0.0,11.0,1.0,0.04,0.09,0.13,0.04,0.13,13.0,1.0,38.0,7.0,1.0,11.0,24.0,16.0,1.0,13.0,5.0,38.5,0.57,0.22,0.08,0.20,PO1,1.4,1.4,0.6,1.9,18.0,130.0,10.0,0.06,0.02,0.08,0.06,0.08
4283,Boris Popovic,SRB,DF,Arouca,24.0,16.0,10.0,898.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.00,0.00,0.00,0.00,0.00,1.5,0.0,2.0,5.0,0.0,1.0,13.0,6.0,0.0,3.0,0.0,0.0,0.30,0.00,0.00,0.00,PO1,0.1,0.1,0.0,0.1,2.0,22.0,1.0,0.01,0.00,0.01,0.01,0.01
4397,Danilo Veiga,POR,"DF,MF",Estrela,21.0,15.0,14.0,1280.0,14.2,0.0,2.0,2.0,0.0,0.0,0.0,5.0,1.0,0.00,0.14,0.14,0.00,0.14,1.0,1.0,23.0,37.0,1.0,48.0,18.0,19.0,0.0,2.0,0.0,0.0,0.14,0.00,0.00,0.00,PO1,0.7,0.7,1.5,2.2,20.0,39.0,47.0,0.05,0.11,0.16,0.05,0.16

In [111]:
duplicates[duplicates['Player'].str.contains('Mang')]

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,Value,2CrdY,Fls,Fld,Off,Crs,Int,TklW,OG,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,league,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1
232,Ricardo Mangas,POR,DF,Spartak Moscow,26.0,11.0,1.0,200.0,2.2,2.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.90,0.0,0.90,0.90,0.90,2.5,0.0,7.0,5.0,0.0,8.0,6.0,3.0,0.0,3.0,2.0,66.7,1.35,0.90,0.67,1.00,RU1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1719,Orel Mangala,BEL,MF,Lyon,26.0,1.0,1.0,67.0,0.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00,18.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.34,0.00,0.00,0.00,FR1,0.1,0.1,0.0,0.1,1.0,7.0,3.0,0.07,0.03,0.10,0.07,0.10
2214,Orel Mangala,BEL,MF,Everton,26.0,19.0,14.0,1261.0,14.0,1.0,0.0,1.0,1.0,0.0,0.0,2.0,0.0,0.07,0.0,0.07,0.07,0.07,18.0,0.0,24.0,17.0,2.0,6.0,21.0,8.0,0.0,16.0,6.0,37.5,1.14,0.43,0.06,0.17,GB1,1.1,1.1,0.6,1.8,6.0,34.0,19.0,0.08,0.05,0.13,0.08,0.13
4176,Ricardo Mangas,POR,FW,Vitoria,26.0,4.0,4.0,339.0,3.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00,2.5,0.0,4.0,7.0,2.0,7.0,0.0,3.0,0.0,5.0,3.0,60.0,1.33,0.80,0.00,0.00,PO1,0.9,0.9,0.3,1.2,9.0,4.0,25.0,0.24,0.07,0.32,0.24,0.32

In [112]:
grouped = duplicates.groupby(['Player', 'Age', 'Nation'])
for name, group in grouped:
    print(group)

                  Player Nation Pos            Squad   Age    MP  Starts  \
1668  Abdukodir Khusanov    UZB  DF             Lens  20.0  13.0    11.0
2175  Abdukodir Khusanov    UZB  DF  Manchester City  20.0   6.0     6.0

        Min   90s  Gls  Ast  G+A  G-PK   PK  PKatt  CrdY  CrdR  Gls.1  Ast.1  \
1668  975.0  10.8  0.0  0.0  0.0   0.0  0.0    0.0   2.0   1.0    0.0    0.0
2175  503.0   5.6  0.0  0.0  0.0   0.0  0.0    0.0   1.0   0.0    0.0    0.0

      G+A.1  G-PK.1  G+A-PK  Value  2CrdY   Fls  Fld  Off  Crs   Int  TklW  \
1668    0.0     0.0     0.0   35.0    0.0  13.0  3.0  0.0  5.0  26.0  11.0
2175    0.0     0.0     0.0   35.0    0.0   3.0  3.0  0.0  1.0   3.0   4.0

       OG   Sh  SoT  SoT%  Sh/90  SoT/90  G/Sh  G/SoT league   xG  npxG  xAG  \
1668  0.0  6.0  5.0  83.3   0.55    0.46   0.0    0.0    FR1  0.2   0.2  0.3
2175  1.0  1.0  0.0   0.0   0.18    0.00   0.0    0.0    GB1  0.0   0.0  0.1

      npxG+xAG  PrgC  PrgP  PrgR  xG.1  xAG.1  xG+xAG  npxG.1  npxG+xAG.1
1668       0.6   2.0  43.0   6.0  0.02   0.03    0.05    0.02        0.05
2175       0.1   1.0  25.0   2.0  0.00   0.02    0.02    0.00        0.02
                Player Nation Pos       Squad   Age    MP  Starts    Min  90s  \
1128  Abdulai Juma Bah    SLE  DF  Valladolid  18.0  12.0    10.0  864.0  9.6
1653  Abdulai Juma Bah    SLE  DF        Lens  18.0  10.0     8.0  686.0  7.6

      Gls  Ast  G+A  G-PK   PK  PKatt  CrdY  CrdR  Gls.1  Ast.1  G+A.1  \
1128  0.0  0.0  0.0   0.0  0.0    0.0   1.0   0.0    0.0    0.0    0.0
1653  0.0  0.0  0.0   0.0  0.0    0.0   2.0   0.0    0.0    0.0    0.0

      G-PK.1  G+A-PK  Value  2CrdY  Fls  Fld  Off  Crs   Int  TklW   OG   Sh  \
1128     0.0     0.0    6.0    0.0  6.0  6.0  0.0  0.0  11.0   7.0  0.0  3.0
1653     0.0     0.0    6.0    0.0  7.0  1.0  0.0  0.0  16.0   9.0  0.0  2.0

      SoT  SoT%  Sh/90  SoT/90  G/Sh  G/SoT league   xG  npxG  xAG  npxG+xAG  \
1128  1.0  33.3   0.31    0.10   0.0    0.0    ES1  0.3   0.3  0.0       0.3
1653  1.0  50.0   0.26    0.13   0.0    0.0    FR1  0.1   0.1  0.2       0.3

      PrgC  PrgP  PrgR  xG.1  xAG.1  xG+xAG  npxG.1  npxG+xAG.1
1128   0.0  13.0   1.0  0.03   0.00    0.03    0.03        0.03
1653   3.0   9.0   1.0  0.01   0.02    0.03    0.01        0.03
          Player Nation Pos          Squad   Age    MP  Starts    Min  90s  \
922   Adam Aznou    MAR  DF     Valladolid  18.0  13.0    10.0  876.0  9.7
2993  Adam Aznou    MAR  DF  Bayern Munich  18.0   2.0     0.0   17.0  0.2

      Gls  Ast  G+A  G-PK   PK  PKatt  CrdY  CrdR  Gls.1  Ast.1  G+A.1  \
922   0.0  0.0  0.0   0.0  0.0    0.0   1.0   0.0    0.0    0.0    0.0
2993  0.0  0.0  0.0   0.0  0.0    0.0   0.0   0.0    0.0    0.0    0.0

      G-PK.1  G+A-PK  Value  2CrdY   Fls   Fld  Off   Crs   Int  TklW   OG  \
922      0.0     0.0    4.0    0.0  14.0  17.0  0.0  11.0  10.0  22.0  0.0
2993     0.0     0.0    4.0    0.0   0.0   0.0  0.0   1.0   0.0   0.0  0.0

       Sh  SoT  SoT%  Sh/90  SoT/90  G/Sh  G/SoT league   xG  npxG  xAG  \
922   4.0  1.0  25.0   0.41     0.1   0.0    0.0    ES1  0.3   0.3  0.3
2993  0.0  0.0   0.0   0.00     0.0   0.0    0.0     L1  0.0   0.0  0.0

      npxG+xAG  PrgC  PrgP  PrgR  xG.1  xAG.1  xG+xAG  npxG.1  npxG+xAG.1
922        0.6  16.0  25.0  26.0  0.03   0.03    0.06    0.03        0.06
2993       0.0   0.0   1.0   2.0  0.00   0.00    0.00    0.00        0.00
         Player Nation Pos       Squad   Age   MP  Starts    Min  90s  Gls  \
437   Adryelson    BRA  DF  Anderlecht  26.0  7.0     6.0  542.0  6.0  1.0
1429  Adryelson    BRA  DF        Lyon  26.0  1.0     0.0    1.0  0.0  0.0

      Ast  G+A  G-PK   PK  PKatt  CrdY  CrdR  Gls.1  Ast.1  G+A.1  G-PK.1  \
437   0.0  1.0   1.0  0.0    0.0   0.0   0.0   0.17    0.0   0.17    0.17
1429  0.0  0.0   0.0  0.0    0.0   1.0   0.0   0.00    0.0   0.00    0.00

      G+A-PK  Value  2CrdY  Fls  Fld  Off  Crs   Int  TklW   OG   Sh  SoT  \
437     0.17    3.5    0.0  2.0  4.0  0.0  1.0  10.0   7.0  0.0  6.0  3.0
1429    0.00    3.5    0.0  0.0  0.0  0.0  0.0   1.0   0.0  0.0  0.0  0.0

      SoT%  Sh/90  SoT/90  G/Sh  G/SoT league   xG  npxG  xAG  npxG+xAG  PrgC  \
437   50.0   0.76    0.38  0.17   0.33    BE1  NaN   NaN  NaN       NaN   NaN
1429   0.0   0.00    0.00  0.00   0.00    FR1  0.0   0.0  0.0       0.0   0.0

      PrgP  PrgR  xG.1  xAG.1  xG+xAG  npxG.1  npxG+xAG.1
437    NaN   NaN   NaN    NaN     NaN     NaN         NaN
1429   1.0   0.0   0.0    0.0     0.0     0.0         0.0
          Player Nation Pos        Squad   Age    MP  Starts     Min   90s  \
879   Akor Adams    NGA  FW      Sevilla  24.0   4.0     1.0   134.0   1.5
1427  Akor Adams    NGA  FW  Montpellier  24.0  15.0    13.0  1075.0  11.9

      Gls  Ast  G+A  G-PK   PK  PKatt  CrdY  CrdR  Gls.1  Ast.1  G+A.1  \
879   0.0  0.0  0.0   0.0  0.0    0.0   0.0   0.0   0.00   0.00   0.00
1427  3.0  1.0  4.0   3.0  0.0    0.0   2.0   0.0   0.25   0.08   0.33

      G-PK.1  G+A-PK  Value  2CrdY   Fls  Fld   Off  Crs  Int  TklW   OG  \
879     0.00    0.00    5.0    0.0   1.0  0.0   1.0  0.0  0.0   0.0  0.0
1427    0.25    0.33    5.0    0.0  17.0  8.0  16.0  5.0  1.0   3.0  0.0

        Sh   SoT   SoT%  Sh/90  SoT/90  G/Sh  G/SoT league   xG  npxG  xAG  \
879    2.0   2.0  100.0   1.34    1.34  0.00   0.00    ES1  0.4   0.4  0.0
1427  26.0  12.0   46.2   2.18    1.00  0.12   0.25    FR1  4.3   4.3  1.0

      npxG+xAG  PrgC  PrgP  PrgR  xG.1  xAG.1  xG+xAG  npxG.1  npxG+xAG.1
879        0.4   0.0   5.0   5.0  0.29   0.00    0.29    0.29        0.29
1427       5.3  11.0   6.0  45.0  0.36   0.08    0.44    0.36        0.44
               Player Nation    Pos        Squad   Age    MP  Starts    Min  \
1622  Albert Gronbaek    DEN  MF,FW       Rennes  23.0  16.0     9.0  813.0
2116  Albert Gronbaek    DEN  FW,MF  Southampton  23.0   4.0     2.0  143.0

      90s  Gls  Ast  G+A  G-PK   PK  PKatt  CrdY  CrdR  Gls.1  Ast.1  G+A.1  \
1622  9.0  2.0  1.0  3.0   2.0  0.0    0.0   1.0   0.0   0.22   0.11   0.33
2116  1.6  0.0  0.0  0.0   0.0  0.0    0.0   0.0   0.0   0.00   0.00   0.00

      G-PK.1  G+A-PK  Value  2CrdY   Fls   Fld  Off   Crs  Int  TklW   OG  \
1622    0.22    0.33   11.0    0.0  10.0  10.0  0.0  28.0  3.0  11.0  0.0
2116    0.00    0.00   11.0    0.0   0.0   1.0  0.0   1.0  0.0   1.0  0.0

        Sh  SoT  SoT%  Sh/90  SoT/90  G/Sh  G/SoT league   xG  npxG  xAG  \
1622  22.0  9.0  40.9   2.44     1.0  0.09   0.22    FR1  1.5   1.5  1.0
2116   2.0  0.0   0.0   1.26     0.0  0.00   0.00    GB1  0.1   0.1  0.0

      npxG+xAG  PrgC  PrgP  PrgR  xG.1  xAG.1  xG+xAG  npxG.1  npxG+xAG.1
1622       2.5  23.0  30.0  58.0  0.17   0.12    0.28    0.17        0.28
2116       0.1   1.0   1.0   3.0  0.07   0.01    0.08    0.07        0.08
             Player Nation Pos     Squad   Age    MP  Starts    Min  90s  Gls  \
2545  Alberto costa    POR  DF  Juventus  20.0   9.0     3.0  357.0  4.0  0.0
4009  Alberto costa    POR  DF   Vitoria  20.0  10.0     7.0  675.0  7.5  0.0

      Ast  G+A  G-PK   PK  PKatt  CrdY  CrdR  Gls.1  Ast.1  G+A.1  G-PK.1  \
2545  1.0  1.0   0.0  0.0    0.0   3.0   0.0    0.0   0.25   0.25     0.0
4009  2.0  2.0   0.0  0.0    0.0   0.0   0.0    0.0   0.27   0.27     0.0

      G+A-PK  Value  2CrdY   Fls   Fld  Off   Crs   Int  TklW   OG   Sh  SoT  \
2545    0.25   10.0    0.0   8.0   2.0  0.0   3.0   4.0  10.0  0.0  7.0  2.0
4009    0.27   10.0    0.0  11.0  11.0  0.0  23.0  11.0  16.0  0.0  7.0  0.0

      SoT%  Sh/90  SoT/90  G/Sh  G/SoT league   xG  npxG  xAG  npxG+xAG  PrgC  \
2545  28.6   1.76     0.5   0.0    0.0    IT1  0.6   0.6  0.2       0.8   8.0
4009   0.0   0.93     0.0   0.0    0.0    PO1  0.2   0.2  1.5       1.7  30.0

      PrgP  PrgR  xG.1  xAG.1  xG+xAG  npxG.1  npxG+xAG.1
2545   8.0  25.0  0.15   0.05    0.20    0.15        0.20
4009  31.0  52.0  0.03   0.20    0.23    0.03        0.23
         Player Nation    Pos        Squad   Age    MP  Starts    Min  90s  \
2674  Ali Jasim    IRQ  FW,DF         Como  20.0   2.0     0.0   10.0  0.1
3604  Ali Jasim    IRQ  FW,MF  Almere City  20.0  11.0     4.0  437.0  4.9

      Gls  Ast  G+A  G-PK   PK  PKatt  CrdY  CrdR  Gls.1  Ast.1  G+A.1  \
2674  0.0  0.0  0.0   0.0  0.0    0.0   0.0   0.0   0.00    0.0   0.00
3604  1.0  0.0  1.0   1.0  0.0    0.0   0.0   0.0   0.21    0.0   0.21

      G-PK.1  G+A-PK  Value  2CrdY  Fls  Fld  Off  Crs  Int  TklW   OG    Sh  \
2674    0.00    0.00   0.55    0.0  1.0  0.0  0.0  1.0  0.0   0.0  0.0   0.0
3604    0.21    0.21   0.55    0.0  1.0  2.0  0.0  8.0  3.0   6.0  0.0  11.0

      SoT  SoT%  Sh/90  SoT/90  G/Sh  G/SoT league   xG  npxG  xAG  npxG+xAG  \
2674  0.0   0.0   0.00    0.00  0.00   0.00    IT1  0.0   0.0  0.0       0.0
3604  3.0  27.3   2.27    0.62  0.09   0.33    NL1  0.8   0.8  1.4       2.2

      PrgC  PrgP  PrgR  xG.1  xAG.1  xG+xAG  npxG.1  npxG+xAG.1
2674   1.0   1.0   1.0  0.00   0.00    0.00    0.00        0.00
3604  20.0  25.0  42.0  0.16   0.29    0.45    0.16        0.45
            Player Nation    Pos Squad   Age    MP  Starts     Min   90s  Gls  \
545   Alieu Fadera    GAM     MF  Genk  22.0   2.0     2.0   180.0   2.0  0.0
2605  Alieu Fadera    GAM  FW,DF  Como  22.0  28.0    20.0  1644.0  18.3  1.0

      Ast  G+A  G-PK   PK  PKatt  CrdY  CrdR  Gls.1  Ast.1  G+A.1  G-PK.1  \
545   0.0  0.0   0.0  0.0    0.0   1.0   0.0   0.00   0.00   0.00    0.00
2605  3.0  4.0   1.0  0.0    0.0   2.0   1.0   0.05   0.16   0.22    0.05

      G+A-PK  Value  2CrdY   Fls   Fld   Off   Crs   Int  TklW   OG    Sh  \
545     0.00    4.5    0.0   5.0   6.0   0.0   9.0   2.0  10.0  0.0   4.0
2605    0.22    4.5    0.0  40.0  50.0  14.0  39.0  12.0  47.0  0.0  28.0

      SoT  SoT%  Sh/90  SoT/90  G/Sh  G/SoT league   xG  npxG  xAG  npxG+xAG  \
545   1.0  25.0   2.00    0.50  0.00   0.00    BE1  NaN   NaN  NaN       NaN
2605  9.0  32.1   1.53    0.49  0.04   0.11    IT1  1.7   1.7  4.0       5.7

      PrgC  PrgP   PrgR  xG.1  xAG.1  xG+xAG  npxG.1  npxG+xAG.1
545    NaN   NaN    NaN   NaN    NaN     NaN     NaN         NaN
2605  74.0  36.0  160.0  0.09   0.22    0.31    0.09        0.31
                  Player Nation Pos   Squad   Age    MP  Starts     Min   90s  \
2881  Anass Salah-Eddine    NED  DF    Roma  22.0   3.0     2.0   152.0   1.7
3801  Anass Salah-Eddine    NED  DF  Twente  22.0  18.0    15.0  1280.0  14.2

      Gls  Ast  G+A  G-PK   PK  PKatt  CrdY  CrdR  Gls.1  Ast.1  G+A.1  \
2881  0.0  1.0  1.0   0.0  0.0    0.0   0.0   0.0   0.00   0.59   0.59
3801  2.0  2.0  4.0   2.0  0.0    0.0   1.0   0.0   0.14   0.14   0.28

      G-PK.1  G+A-PK  Value  2CrdY  Fls   Fld  Off   Crs   Int  TklW   OG  \
2881    0.00    0.59    8.0    0.0  2.0   1.0  0.0   6.0   1.0   1.0  0.0
3801    0.14    0.28    8.0    0.0  9.0  16.0  1.0  28.0  17.0  19.0  0.0

        Sh  SoT  SoT%  Sh/90  SoT/90  G/Sh  G/SoT league   xG  npxG  xAG  \
2881   2.0  1.0  50.0   1.18    0.59   0.0   0.00    IT1  0.3   0.3  0.1
3801  10.0  6.0  60.0   0.70    0.42   0.2   0.33    NL1  0.7   0.7  1.4

      npxG+xAG  PrgC  PrgP  PrgR  xG.1  xAG.1  xG+xAG  npxG.1  npxG+xAG.1
2881       0.5   8.0   2.0  15.0  0.19   0.08    0.27    0.19        0.27
3801       2.1  55.0  76.0  80.0  0.05   0.10    0.15    0.05        0.15
                   Player Nation Pos       Squad   Age    MP  Starts    Min  \
1032  Anastasios Douvikas    GRE  FW  Celta Vigo  24.0  20.0     6.0  700.0
2582  Anastasios Douvikas    GRE  FW        Como  24.0  13.0     6.0  580.0

      90s  Gls  Ast  G+A  G-PK   PK  PKatt  CrdY  CrdR  Gls.1  Ast.1  G+A.1  \
1032  7.8  3.0  1.0  4.0   3.0  0.0    0.0   2.0   0.0   0.39   0.13   0.51
2582  6.4  2.0  2.0  4.0   2.0  0.0    0.0   1.0   0.0   0.31   0.31   0.62

      G-PK.1  G+A-PK  Value  2CrdY   Fls   Fld  Off  Crs  Int  TklW   OG  \
1032    0.39    0.51   10.0    0.0  10.0  27.0  9.0  1.0  3.0   4.0  0.0
2582    0.31    0.62   10.0    0.0  13.0  17.0  1.0  2.0  1.0   2.0  0.0

        Sh  SoT  SoT%  Sh/90  SoT/90  G/Sh  G/SoT league   xG  npxG  xAG  \
1032  17.0  9.0  52.9   2.19    1.16  0.18   0.33    ES1  4.4   4.4  0.2
2582  14.0  5.0  35.7   2.17    0.78  0.14   0.40    IT1  2.5   2.5  1.1

      npxG+xAG  PrgC  PrgP  PrgR  xG.1  xAG.1  xG+xAG  npxG.1  npxG+xAG.1
1032       4.7   6.0   6.0  43.0  0.57   0.03    0.60    0.57        0.60
2582       3.7   8.0   6.0  36.0  0.40   0.17    0.57    0.40        0.57
              Player Nation Pos    Squad   Age    MP  Starts    Min  90s  Gls  \
2472  Andrea Belotti    ITA  FW     Como  30.0  18.0     7.0  593.0  6.6  2.0
3952  Andrea Belotti    ITA  FW  Benfica  30.0  14.0     4.0  457.0  5.1  3.0

      Ast  G+A  G-PK   PK  PKatt  CrdY  CrdR  Gls.1  Ast.1  G+A.1  G-PK.1  \
2472  0.0  2.0   2.0  0.0    0.0   1.0   0.0   0.30    0.0   0.30    0.30
3952  0.0  3.0   3.0  0.0    0.0   0.0   0.0   0.59    0.0   0.59    0.59

      G+A-PK  Value  2CrdY   Fls   Fld  Off  Crs  Int  TklW   OG    Sh   SoT  \
2472    0.30    2.0    0.0   9.0  19.0  5.0  5.0  1.0   5.0  0.0  19.0   3.0
3952    0.59    2.0    0.0  11.0  19.0  5.0  2.0  1.0   3.0  0.0  26.0  14.0

      SoT%  Sh/90  SoT/90  G/Sh  G/SoT league   xG  npxG  xAG  npxG+xAG  PrgC  \
2472  15.8   2.88    0.46  0.11   0.67    IT1  2.5   2.5  0.4       2.8   9.0
3952  53.8   5.12    2.76  0.12   0.21    PO1  5.3   5.3  1.1       6.4  11.0

      PrgP  PrgR  xG.1  xAG.1  xG+xAG  npxG.1  npxG+xAG.1
2472   9.0  33.0  0.37   0.05    0.43    0.37        0.43
3952   8.0  40.0  1.04   0.22    1.26    1.04        1.26
                  Player Nation    Pos        Squad   Age    MP  Starts  \
790   Andreas Skov Olsen    DEN     FW  Club Brugge  24.0  19.0    14.0
3342  Andreas Skov Olsen    DEN  FW,MF    Wolfsburg  24.0  12.0     4.0

         Min   90s  Gls  Ast   G+A  G-PK   PK  PKatt  CrdY  CrdR  Gls.1  \
790   1136.0  12.6  8.0  4.0  12.0   8.0  0.0    0.0   1.0   0.0   0.63
3342   535.0   5.9  1.0  1.0   2.0   1.0  0.0    0.0   0.0   0.0   0.17

      Ast.1  G+A.1  G-PK.1  G+A-PK  Value  2CrdY  Fls   Fld  Off   Crs  Int  \
790    0.32   0.95    0.63    0.95   14.0    0.0  7.0  12.0  2.0  37.0  4.0
3342   0.17   0.34    0.17    0.34   14.0    0.0  2.0   3.0  2.0  29.0  2.0

      TklW   OG    Sh   SoT  SoT%  Sh/90  SoT/90  G/Sh  G/SoT league   xG  \
790    7.0  0.0  39.0  17.0  43.6   3.09    1.35  0.21   0.47    BE1  NaN
3342   7.0  0.0   7.0   1.0  14.3   1.18    0.17  0.14   1.00     L1  0.8

      npxG  xAG  npxG+xAG  PrgC  PrgP  PrgR  xG.1  xAG.1  xG+xAG  npxG.1  \
790    NaN  NaN       NaN   NaN   NaN   NaN   NaN    NaN     NaN     NaN
3342   0.8  1.9       2.7  22.0  22.0  48.0  0.14   0.32    0.46    0.14

      npxG+xAG.1
790          NaN
3342        0.46
            Player Nation Pos       Squad   Age   MP  Starts    Min  90s  Gls  \
1276  Andy Pelmard    MAD  DF  Las Palmas  24.0  4.0     2.0  205.0  2.3  0.0
2832  Andy Pelmard    MAD  DF       Lecce  24.0  3.0     1.0  129.0  1.4  0.0

      Ast  G+A  G-PK   PK  PKatt  CrdY  CrdR  Gls.1  Ast.1  G+A.1  G-PK.1  \
1276  0.0  0.0   0.0  0.0    0.0   1.0   0.0    0.0    0.0    0.0     0.0
2832  0.0  0.0   0.0  0.0    0.0   1.0   0.0    0.0    0.0    0.0     0.0

      G+A-PK  Value  2CrdY  Fls  Fld  Off  Crs  Int  TklW   OG   Sh  SoT  \
1276     0.0    2.0    0.0  2.0  3.0  0.0  2.0  2.0   0.0  0.0  1.0  0.0
2832     0.0    2.0    0.0  2.0  0.0  0.0  0.0  0.0   6.0  0.0  0.0  0.0

      SoT%  Sh/90  SoT/90  G/Sh  G/SoT league   xG  npxG  xAG  npxG+xAG  PrgC  \
1276   0.0   0.44     0.0   0.0    0.0    ES1  0.0   0.0  0.0       0.1   1.0
2832   0.0   0.00     0.0   0.0    0.0    IT1  0.0   0.0  0.0       0.0   1.0

      PrgP  PrgR  xG.1  xAG.1  xG+xAG  npxG.1  npxG+xAG.1
1276  13.0   5.0   0.0   0.02    0.03     0.0        0.03
2832   1.0   0.0   0.0   0.00    0.00     0.0        0.00
               Player Nation Pos      Squad   Age    MP  Starts     Min   90s  \
1836  Anthony Rouault    FRA  DF     Rennes  23.0  11.0    11.0   972.0  10.8
3305  Anthony Rouault    FRA  DF  Stuttgart  23.0  18.0    14.0  1212.0  13.5

      Gls  Ast  G+A  G-PK   PK  PKatt  CrdY  CrdR  Gls.1  Ast.1  G+A.1  \
1836  0.0  0.0  0.0   0.0  0.0    0.0   3.0   0.0   0.00    0.0   0.00
3305  1.0  0.0  1.0   1.0  0.0    0.0   1.0   0.0   0.07    0.0   0.07

      G-PK.1  G+A-PK  Value  2CrdY   Fls  Fld  Off  Crs   Int  TklW   OG   Sh  \
1836    0.00    0.00   10.0    0.0   7.0  1.0  1.0  0.0   7.0   8.0  0.0  7.0
3305    0.07    0.07   10.0    0.0  19.0  8.0  0.0  1.0  17.0  11.0  0.0  5.0

      SoT  SoT%  Sh/90  SoT/90  G/Sh  G/SoT league   xG  npxG  xAG  npxG+xAG  \
1836  3.0  42.9   0.65    0.28   0.0    0.0    FR1  0.5   0.5  0.0       0.5
3305  1.0  20.0   0.37    0.07   0.2    1.0     L1  0.5   0.5  0.3       0.8

      PrgC  PrgP  PrgR  xG.1  xAG.1  xG+xAG  npxG.1  npxG+xAG.1
1836   3.0  36.0   0.0  0.05   0.00    0.05    0.05        0.05
3305   6.0  52.0   4.0  0.04   0.02    0.06    0.04        0.06
               Player Nation Pos       Squad   Age    MP  Starts     Min  \
975   Antonio Candela    ITA  DF  Valladolid  24.0  12.0    12.0   906.0
2514  Antonio Candela    ITA  DF     Venezia  24.0  14.0    12.0  1008.0

       90s  Gls  Ast  G+A  G-PK   PK  PKatt  CrdY  CrdR  Gls.1  Ast.1  G+A.1  \
975   10.1  0.0  0.0  0.0   0.0  0.0    0.0   1.0   0.0    0.0   0.00   0.00
2514  11.2  0.0  1.0  1.0   0.0  0.0    0.0   2.0   0.0    0.0   0.09   0.09

      G-PK.1  G+A-PK  Value  2CrdY   Fls  Fld  Off   Crs  Int  TklW   OG   Sh  \
975      0.0    0.00    1.8    0.0   5.0  7.0  2.0  20.0  6.0   6.0  0.0  1.0
2514     0.0    0.09    1.8    0.0  15.0  5.0  0.0  21.0  8.0  21.0  1.0  5.0

      SoT  SoT%  Sh/90  SoT/90  G/Sh  G/SoT league   xG  npxG  xAG  npxG+xAG  \
975   0.0   0.0   0.10     0.0   0.0    0.0    ES1  0.0   0.0  0.8       0.9
2514  0.0   0.0   0.45     0.0   0.0    0.0    IT1  0.3   0.3  0.8       1.2

      PrgC  PrgP  PrgR  xG.1  xAG.1  xG+xAG  npxG.1  npxG+xAG.1
975   16.0  22.0  29.0  0.00   0.08    0.08    0.00        0.08
2514  12.0  27.0  25.0  0.03   0.07    0.11    0.03        0.11
            Player Nation    Pos        Squad   Age    MP  Starts     Min  \
716   Antonio Nusa    NOR  FW,MF  Club Brugge  19.0   3.0     2.0   162.0
3255  Antonio Nusa    NOR  MF,DF   RB Leipzig  19.0  25.0    16.0  1558.0

       90s  Gls  Ast  G+A  G-PK   PK  PKatt  CrdY  CrdR  Gls.1  Ast.1  G+A.1  \
716    1.8  0.0  1.0  1.0   0.0  0.0    0.0   0.0   0.0   0.00   0.56   0.56
3255  17.3  3.0  3.0  6.0   3.0  0.0    0.0   0.0   0.0   0.17   0.17   0.35

      G-PK.1  G+A-PK  Value  2CrdY   Fls   Fld  Off   Crs  Int  TklW   OG  \
716     0.00    0.56   28.0    0.0   2.0   3.0  0.0   5.0  0.0   1.0  0.0
3255    0.17    0.35   28.0    0.0  14.0  28.0  9.0  35.0  8.0  17.0  0.0

        Sh  SoT  SoT%  Sh/90  SoT/90  G/Sh  G/SoT league   xG  npxG  xAG  \
716    6.0  2.0  33.3   3.33    1.11  0.00   0.00    BE1  NaN   NaN  NaN
3255  24.0  7.0  29.2   1.39    0.40  0.13   0.43     L1  1.6   1.6  2.8

      npxG+xAG  PrgC  PrgP   PrgR  xG.1  xAG.1  xG+xAG  npxG.1  npxG+xAG.1
716        NaN   NaN   NaN    NaN   NaN    NaN     NaN     NaN         NaN
3255       4.4  57.0  52.0  123.0  0.09   0.16    0.26    0.09        0.26
      Player Nation    Pos           Squad   Age    MP  Starts     Min   90s  \
906   Antony    BRA     FW           Betis  24.0  17.0    15.0  1362.0  15.1
1951  Antony    BRA  DF,MF  Manchester Utd  24.0   8.0     0.0   141.0   1.6

      Gls  Ast  G+A  G-PK   PK  PKatt  CrdY  CrdR  Gls.1  Ast.1  G+A.1  \
906   5.0  2.0  7.0   5.0  0.0    0.0   2.0   1.0   0.33   0.13   0.46
1951  0.0  0.0  0.0   0.0  0.0    0.0   0.0   0.0   0.00   0.00   0.00

      G-PK.1  G+A-PK  Value  2CrdY   Fls   Fld  Off   Crs  Int  TklW   OG  \
906     0.33    0.46   35.0    0.0  15.0  27.0  1.0  41.0  9.0  10.0  0.0
1951    0.00    0.00   35.0    0.0   2.0   5.0  0.0   5.0  2.0   3.0  0.0

        Sh   SoT  SoT%  Sh/90  SoT/90  G/Sh  G/SoT league   xG  npxG  xAG  \
906   43.0  17.0  39.5   2.84    1.12  0.12   0.29    ES1  2.9   2.9  3.5
1951   6.0   3.0  50.0   3.83    1.91  0.00   0.00    GB1  1.0   1.0  0.1


In [113]:
for _, group in grouped:
    ind_to_save = group.index[0]
    ind_to_del = group.index[1]
    group = group.reset_index(drop=True)
    if group.at[0, '90s'] < group.at[1, '90s']:
        group.at[0, 'Squad'] = group.at[1, 'Squad']
        group.at[0, 'league'] = group.at[1, 'league']
    for col in combine.columns[5:22]:
        group.at[0, col] += group.at[1, col]
    group.at[0, 'Gls.1'] = group.at[0, 'Gls'] / group.at[0, '90s']
    group.at[0, 'Ast.1'] = group.at[0, 'Ast'] / group.at[0, '90s']
    group.at[0, 'G+A.1'] = group.at[0, 'G+A.1'] / group.at[0, '90s']
    group.at[0, 'G-PK.1'] = group.at[0, 'G-PK.1'] / group.at[0, '90s']
    group.at[0, 'G+A-PK'] = group.at[0, 'G+A-PK'] / group.at[0, '90s']
    for col in combine.columns[23:33]:
        group.at[0, col] += group.at[1, col]
    group.at[0, 'SoT%'] = group.at[0, 'SoT'] / group.at[0, 'Sh'] * 100
    group.at[0, 'Sh/90'] = group.at[0, 'Sh'] / group.at[0, '90s']
    group.at[0, 'SoT/90'] = group.at[0, 'SoT'] / group.at[0, '90s']
    group.at[0, 'G/Sh'] = group.at[0, 'Gls'] / group.at[0, 'Sh']
    group.at[0, 'G/SoT'] = group.at[0, 'Gls'] / group.at[0, 'SoT']
    if not(pd.isna(group.at[0, 'xG'])) and not(pd.isna(group.at[1, 'xG'])):
        for col in combine.columns[39:46]:
            group.at[0, col] += group.at[1, col]
        group.at[0, 'xG+xAG'] += group.at[1, 'xG+xAG']
        group.at[0, 'xG.1'] = group.at[0, 'xG'] / group.at[0, '90s']
        group.at[0, 'xAG.1'] = group.at[0, 'xAG'] / group.at[0, '90s']
        group.at[0, 'npxG.1'] = group.at[0, 'npxG'] / group.at[0, '90s']
        group.at[0, 'npxG+xAG.1'] = group.at[0, 'npxG+xAG'] / group.at[0, '90s']
    elif not(pd.isna(group.at[1, 'xG'])):
        for col in combine.columns[39:]:
            group.at[0, col] = group.at[1, col]
    combine = combine.drop(ind_to_del)
    combine.loc[ind_to_save] = group.loc[0]
group

C:\Users\denis\AppData\Local\Temp\ipykernel_19432\416152483.py:21: RuntimeWarning: invalid value encountered in scalar divide
  group.at[0, 'G/SoT'] = group.at[0, 'Gls'] / group.at[0, 'SoT']
C:\Users\denis\AppData\Local\Temp\ipykernel_19432\416152483.py:21: RuntimeWarning: invalid value encountered in scalar divide
  group.at[0, 'G/SoT'] = group.at[0, 'Gls'] / group.at[0, 'SoT']
C:\Users\denis\AppData\Local\Temp\ipykernel_19432\416152483.py:21: RuntimeWarning: invalid value encountered in scalar divide
  group.at[0, 'G/SoT'] = group.at[0, 'Gls'] / group.at[0, 'SoT']
C:\Users\denis\AppData\Local\Temp\ipykernel_19432\416152483.py:17: RuntimeWarning: invalid value encountered in scalar divide
  group.at[0, 'SoT%'] = group.at[0, 'SoT'] / group.at[0, 'Sh'] * 100
C:\Users\denis\AppData\Local\Temp\ipykernel_19432\416152483.py:20: RuntimeWarning: invalid value encountered in scalar divide
  group.at[0, 'G/Sh'] = group.at[0, 'Gls'] / group.at[0, 'Sh']
C:\Users\denis\AppData\Local\Temp\ipykernel_19432\416152483.py:21: RuntimeWarning: invalid value encountered in scalar divide
  group.at[0, 'G/SoT'] = group.at[0, 'Gls'] / group.at[0, 'SoT']
C:\Users\denis\AppData\Local\Temp\ipykernel_19432\416152483.py:21: RuntimeWarning: invalid value encountered in scalar divide
  group.at[0, 'G/SoT'] = group.at[0, 'Gls'] / group.at[0, 'SoT']
C:\Users\denis\AppData\Local\Temp\ipykernel_19432\416152483.py:17: RuntimeWarning: invalid value encountered in scalar divide
  group.at[0, 'SoT%'] = group.at[0, 'SoT'] / group.at[0, 'Sh'] * 100
C:\Users\denis\AppData\Local\Temp\ipykernel_19432\416152483.py:20: RuntimeWarning: invalid value encountered in scalar divide
  group.at[0, 'G/Sh'] = group.at[0, 'Gls'] / group.at[0, 'Sh']
C:\Users\denis\AppData\Local\Temp\ipykernel_19432\416152483.py:21: RuntimeWarning: invalid value encountered in scalar divide
  group.at[0, 'G/SoT'] = group.at[0, 'Gls'] / group.at[0, 'SoT']
C:\Users\denis\AppData\Local\Temp\ipykernel_19432\416152483.py:21: RuntimeWarning: invalid value encountered in scalar divide
  group.at[0, 'G/SoT'] = group.at[0, 'Gls'] / group.at[0, 'SoT']
C:\Users\denis\AppData\Local\Temp\ipykernel_19432\416152483.py:21: RuntimeWarning: invalid value encountered in scalar divide
  group.at[0, 'G/SoT'] = group.at[0, 'Gls'] / group.at[0, 'SoT']
C:\Users\denis\AppData\Local\Temp\ipykernel_19432\416152483.py:17: RuntimeWarning: invalid value encountered in scalar divide
  group.at[0, 'SoT%'] = group.at[0, 'SoT'] / group.at[0, 'Sh'] * 100
C:\Users\denis\AppData\Local\Temp\ipykernel_19432\416152483.py:20: RuntimeWarning: invalid value encountered in scalar divide
  group.at[0, 'G/Sh'] = group.at[0, 'Gls'] / group.at[0, 'Sh']
C:\Users\denis\AppData\Local\Temp\ipykernel_19432\416152483.py:21: RuntimeWarning: invalid value encountered in scalar divide
  group.at[0, 'G/SoT'] = group.at[0, 'Gls'] / group.at[0, 'SoT']
C:\Users\denis\AppData\Local\Temp\ipykernel_19432\416152483.py:21: RuntimeWarning: invalid value encountered in scalar divide
  group.at[0, 'G/SoT'] = group.at[0, 'Gls'] / group.at[0, 'SoT']
C:\Users\denis\AppData\Local\Temp\ipykernel_19432\416152483.py:21: RuntimeWarning: invalid value encountered in scalar divide
  group.at[0, 'G/SoT'] = group.at[0, 'Gls'] / group.at[0, 'SoT']
C:\Users\denis\AppData\Local\Temp\ipykernel_19432\416152483.py:17: RuntimeWarning: invalid value encountered in scalar divide
  group.at[0, 'SoT%'] = group.at[0, 'SoT'] / group.at[0, 'Sh'] * 100
C:\Users\denis\AppData\Local\Temp\ipykernel_19432\416152483.py:20: RuntimeWarning: invalid value encountered in scalar divide
  group.at[0, 'G/Sh'] = group.at[0, 'Gls'] / group.at[0, 'Sh']
C:\Users\denis\AppData\Local\Temp\ipykernel_19432\416152483.py:21: RuntimeWarning: invalid value encountered in scalar divide
  group.at[0, 'G/SoT'] = group.at[0, 'Gls'] / group.at[0, 'SoT']
C:\Users\denis\AppData\Local\Temp\ipykernel_19432\416152483.py:21: RuntimeWarning: invalid value encountered in scalar divide
  group.at[0, 'G/SoT'] = group.at[0, 'Gls'] / group.at[0, 'SoT']
C:\Users\denis\AppData\Local\Temp\ipykernel_19432\416152483.py:21: RuntimeWarning: invalid value encountered in scalar divide
  group.at[0, 'G/SoT'] = group.at[0, 'Gls'] / group.at[0, 'SoT']
C:\Users\denis\AppData\Local\Temp\ipykernel_19432\416152483.py:21: RuntimeWarning: invalid value encountered in scalar divide
  group.at[0, 'G/SoT'] = group.at[0, 'Gls'] / group.at[0, 'SoT']

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,Value,2CrdY,Fls,Fld,Off,Crs,Int,TklW,OG,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,league,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1
0,Youssuf Sylla,BEL,FW,Charleroi,21.0,25.0,3.0,571.0,6.4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6,0.0,15.0,15.0,2.0,3.0,1.0,1.0,0.0,15.0,2.0,13.333333,2.34375,0.3125,0.0,0.0,BE1,0.5,0.5,0.1,0.6,1.0,5.0,17.0,0.24,0.05,0.29,0.24,0.29
1,Youssuf Sylla,BEL,"FW,MF",Willem II,21.0,12.0,0.0,179.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6,0.0,3.0,6.0,2.0,1.0,0.0,0.0,0.0,3.0,0.0,0.000000,1.51000,0.0000,0.0,0.0,NL1,0.5,0.5,0.1,0.6,1.0,5.0,17.0,0.24,0.05,0.29,0.24,0.29

In [115]:
combine[combine['Player'].str.contains('Mang')]

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,Value,2CrdY,Fls,Fld,Off,Crs,Int,TklW,OG,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,league,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1
232,Ricardo Mangas,POR,DF,Vitoria,26.0,15.0,5.0,539.0,6.0,2.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.333333,0.0,0.150000,0.150000,0.150000,2.5,0.0,11.0,12.0,2.0,15.0,6.0,6.0,0.0,8.0,5.0,62.500000,1.333333,0.833333,0.250000,0.400000,PO1,0.9,0.9,0.3,1.2,9.0,4.0,25.0,0.240000,0.070000,0.32,0.240000,0.320000
1719,Orel Mangala,BEL,MF,Everton,26.0,20.0,15.0,1328.0,14.7,1.0,0.0,1.0,1.0,0.0,0.0,2.0,0.0,0.068027,0.0,0.004762,0.004762,0.004762,18.0,0.0,24.0,17.0,2.0,7.0,21.0,8.0,0.0,17.0,6.0,35.294118,1.156463,0.408163,0.058824,0.166667,GB1,1.2,1.2,0.6,1.9,7.0,41.0,22.0,0.081633,0.040816,0.23,0.081633,0.129252
4175,Eliaquim Mangala,FRA,DF,Estoril,33.0,9.0,4.0,424.0,4.7,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.2,0.0,14.0,0.0,0.0,1.0,8.0,6.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,PO1,0.0,0.0,0.0,0.0,2.0,3.0,0.0,0.000000,0.000000,0.00,0.000000,0.000000

In [109]:
combine = combine.drop([689, 690, 691, 693, 694, 695])

In [32]:
combine.columns

Index(['Player', 'Nation', 'Pos', 'Squad', 'Age', 'MP', 'Starts', 'Min', '90s',
       'Gls', 'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls.1',
       'Ast.1', 'G+A.1', 'G-PK.1', 'G+A-PK', 'Value', '2CrdY', 'Fls', 'Fld',
       'Off', 'Crs', 'Int', 'TklW', 'OG', 'Sh', 'SoT', 'SoT%', 'Sh/90',
       'SoT/90', 'G/Sh', 'G/SoT', 'league', 'xG', 'npxG', 'xAG', 'npxG+xAG',
       'PrgC', 'PrgP', 'PrgR', 'xG.1', 'xAG.1', 'xG+xAG', 'npxG.1',
       'npxG+xAG.1'],
      dtype='object')

In [3]:
combine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4289 entries, 0 to 4288
Data columns (total 51 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Player      4289 non-null   object
 1   Nation      4274 non-null   object
 2   Pos         4289 non-null   object
 3   Squad       4289 non-null   object
 4   Age         4289 non-null   float64
 5   MP          4289 non-null   float64
 6   Starts      4289 non-null   float64
 7   Min         4289 non-null   float64
 8   90s         4289 non-null   float64
 9   Gls         4289 non-null   float64
 10  Ast         4289 non-null   float64
 11  G+A         4289 non-null   float64
 12  G-PK        4289 non-null   float64
 13  PK          4289 non-null   float64
 14  PKatt       4289 non-null   float64
 15  CrdY        4289 non-null   float64
 16  CrdR        4289 non-null   float64
 17  Gls.1       4289 non-null   float64
 18  Ast.1       4289 non-null   float64
 19  G+A.1       4289 non-null   float64
 20  G-PK.1      4289 non-null   float64
 21  G+A-PK      4289 non-null   float64
 22  Value       4289 non-null   float64
 23  2CrdY       4289 non-null   float64
 24  Fls         4289 non-null   float64
 25  Fld         4289 non-null   float64
 26  Off         4289 non-null   float64
 27  Crs         4289 non-null   float64
 28  Int         4289 non-null   float64
 29  TklW        4289 non-null   float64
 30  OG          4289 non-null   float64
 31  Sh          4289 non-null   float64
 32  SoT         4289 non-null   float64
 33  SoT%        4289 non-null   float64
 34  Sh/90       4289 non-null   float64
 35  SoT/90      4289 non-null   float64
 36  G/Sh        4289 non-null   float64
 37  G/SoT       4289 non-null   float64
 38  league      4289 non-null   object
 39  xG          3447 non-null   float64
 40  npxG        3447 non-null   float64
 41  xAG         3447 non-null   float64
 42  npxG+xAG    3447 non-null   float64
 43  PrgC        3447 non-null   float64
 44  PrgP        3447 non-null   float64
 45  PrgR        3447 non-null   float64
 46  xG.1        3447 non-null   float64
 47  xAG.1       3447 non-null   float64
 48  xG+xAG      3447 non-null   float64
 49  npxG.1      3447 non-null   float64
 50  npxG+xAG.1  3447 non-null   float64
dtypes: float64(46), object(5)
memory usage: 1.7+ MB

In [125]:
combine.describe()

,Age,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,Value,2CrdY,Fls,Fld,Off,Crs,Int,TklW,OG,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1
count,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,4289.000000,3447.000000,3447.000000,3447.000000,3447.000000,3447.000000,3447.000000,3447.000000,3447.000000,3447.000000,3447.000000,3447.000000,3447.000000
mean,24.504780,19.064118,13.190487,1183.581254,13.150175,1.783633,1.247377,3.031010,1.623922,0.159711,0.200746,2.617626,0.128235,0.127701,0.082529,0.203982,0.114924,0.195302,7.923607,0.054791,16.028678,15.081371,2.221730,24.008627,11.498718,13.985078,0.050595,17.060154,5.917230,27.845014,1.457471,0.493840,0.071997,0.198917,1.876356,1.715985,1.328721,3.045692,22.471715,50.073107,49.568900,0.151002,0.093507,0.252330,0.142241,0.235721
std,4.383019,10.814383,10.658665,902.105032,10.023676,3.114767,1.909602,4.438554,2.738118,0.701743,0.804917,2.574311,0.365065,0.304636,0.163902,0.359444,0.296251,0.351980,15.021664,0.234662,13.498942,14.909120,4.025459,36.523284,12.366095,13.161092,0.242433,19.581754,8.082706,21.337230,2.540658,1.674962,0.102701,0.248885,2.855051,2.478888,1.682046,3.740034,26.350141,50.060664,59.912897,0.417147,0.121005,0.452523,0.412648,0.438246
min,15.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,21.000000,10.000000,3.000000,349.000000,3.900000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.800000,0.000000,5.000000,3.000000,0.000000,2.000000,2.000000,3.000000,0.000000,3.000000,1.000000,11.100000,0.450000,0.050000,0.000000,0.000000,0.200000,0.200000,0.100000,0.500000,4.000000,11.000000,5.000000,0.030000,0.020000,0.070000,0.030000,0.067895
50%,24.000000,21.000000,12.000000,1069.000000,11.900000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,2.000000,0.000000,0.040000,0.000000,0.100000,0.030000,0.100000,2.500000,0.000000,13.000000,11.000000,1.000000,9.000000,7.000000,11.000000,0.000000,11.000000,3.000000,29.300000,0.970000,0.250000,0.040000,0.120000,0.900000,0.800000,0.700000,1.800000,14.000000,36.000000,27.000000,0.070000,0.070000,0.170000,0.070000,0.160000
75%,27.000000,28.000000,22.000000,1902.000000,21.100000,2.000000,2.000000,4.000000,2.000000,0.000000,0.000000,4.000000,0.000000,0.180000,0.124224,0.300000,0.150000,0.280000,8.000000,0.000000,24.000000,22.000000,3.000000,30.000000,18.000000,21.000000,0.000000,24.000000,8.000000,40.000000,2.010000,0.660000,0.120000,0.330000,2.300000,2.200000,1.900000,4.200000,31.000000,75.500000,74.000000,0.200000,0.140000,0.350000,0.180000,0.330000
max,41.000000,54.000000,38.000000,3420.000000,38.000000,39.000000,18.000000,47.000000,27.000000,12.000000,12.000000,15.000000,3.000000,12.860000,6.000000,12.860000,12.860000,12.860000,200.000000,2.000000,83.000000,107.000000,57.000000,287.000000,73.000000,78.000000,3.000000,161.000000,85.000000,100.000000,90.000000,90.000000,1.000000,1.000000,30.800000,24.000000,14.200000,32.400000,213.000000,363.000000,488.000000,21.210000,2.470000,21.210000,21.210000,21.210000

In [122]:
combine[combine['SoT%'].isna()]

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,Value,2CrdY,Fls,Fld,Off,Crs,Int,TklW,OG,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,league,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1
778,Joel Schingtienne,BEL,DF,Venezia,21.0,20.0,16.0,1482.0,16.5,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5,0.0,10.0,2.0,0.0,1.0,15.0,22.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,IT1,0.0,0.0,0.1,0.1,5.0,28.0,4.0,0.0,0.01,0.01,0.0,0.01
875,Max Aarons,ENG,"DF,MF",Valencia,24.0,7.0,2.0,206.0,2.3,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,4.0,0.0,7.0,1.0,6.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,ES1,0.0,0.0,0.0,0.0,1.0,14.0,13.0,0.0,0.00,0.02,0.0,0.00
1353,Daley Sinkgraven,NED,DF,Las Palmas,29.0,4.0,2.0,168.0,1.9,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6,0.0,4.0,2.0,0.0,8.0,3.0,4.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,ES1,0.0,0.0,0.0,0.0,4.0,7.0,8.0,0.0,0.00,0.02,0.0,0.00
2101,Ben Godfrey,ENG,DF,Ipswich Town,26.0,4.0,2.0,182.0,2.1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,GB1,0.0,0.0,0.0,0.0,2.0,5.0,2.0,0.0,0.00,0.00,0.0,0.00

In [123]:
combine['SoT%'] = combine['SoT%'].fillna(0)

In [126]:
combine.to_csv('../data/raw/stats/combine_players_24-25.csv', index=False)

In [7]:
leagues_encoded = pd.get_dummies(gks, columns=['league'], drop_first=True, dtype='uint8')
leagues_encoded

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,GA,GA90,SoTA,Saves,Save%,W,D,L,CS,CS%,PKatt,PKA,PKsv,PKm,PKsv%,Value,league_ES1,league_FR1,league_GB1,league_IT1,league_L1,league_NL1,league_PO1,league_RU1
0,Denis Adamov,RUS,GK,Zenit,26,4,3,327,3.6,5,1.38,14,9,64.3,2,0,1,1,33.3,0,0,0,0,0.0,1.0,0,0,0,0,0,0,0,1
1,Stanislav Agkatsev,RUS,GK,Krasnodar,22,30,30,2700,30.0,23,0.77,98,79,77.6,20,7,3,15,50.0,4,1,3,0,75.0,7.5,0,0,0,0,0,0,0,1
2,Igor Akinfeev,RUS,GK,CSKA Moscow,38,28,28,2520,28.0,21,0.75,71,53,74.6,15,8,5,12,42.9,3,3,0,0,0.0,1.0,0,0,0,0,0,0,0,1
3,Rustam Yatimov,TJK,GK,Rostov,26,20,20,1771,19.7,26,1.32,81,57,70.4,9,6,5,3,15.0,3,2,0,1,0.0,1.5,0,0,0,0,0,0,0,1
4,Aleksandr Belenov,RUS,GK,Fakel Voronezh,37,12,12,1080,12.0,17,1.42,48,31,64.6,1,4,7,3,25.0,0,0,0,0,0.0,0.1,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,Anatolii Trubin,UKR,GK,Benfica,22,32,32,2880,32.0,28,0.87,97,72,73.2,23,5,4,13,40.6,3,2,1,0,33.3,28.0,0,0,0,0,0,0,1,0
348,Joao Valido,POR,GK,Arouca,24,5,5,450,5.0,6,1.20,19,14,73.7,1,3,1,1,20.0,1,1,0,0,0.0,0.3,0,0,0,0,0,0,1,0
349,Bruno Varela,CPV,GK,Vitoria Guimarães,29,34,34,3060,34.0,37,1.09,98,63,67.3,14,12,8,13,38.2,7,5,0,2,0.0,2.5,0,0,0,0,0,0,1,0
350,Ricardo Velho,POR,GK,Farense,25,28,28,2520,28.0,40,1.43,123,89,72.4,3,9,16,6,21.4,7,6,0,1,0.0,4.0,0,0,0,0,0,0,1,0
351,Ivan Zlobin,RUS,GK,Famalicão,27,15,15,1350,15.0,18,1.20,62,45,72.6,4,7,4,5,33.3,1,1,0,0,0.0,1.5,0,0,0,0,0,0,1,0

In [10]:
leagues_encoded_filtered = leagues_encoded[(leagues_encoded['MP']>4)&(leagues_encoded['Value']>0)]
leagues_encoded_filtered

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,GA,GA90,SoTA,Saves,Save%,W,D,L,CS,CS%,PKatt,PKA,PKsv,PKm,PKsv%,Value,league_ES1,league_FR1,league_GB1,league_IT1,league_L1,league_NL1,league_PO1,league_RU1
1,Stanislav Agkatsev,RUS,GK,Krasnodar,22,30,30,2700,30.0,23,0.77,98,79,77.6,20,7,3,15,50.0,4,1,3,0,75.0,7.5,0,0,0,0,0,0,0,1
2,Igor Akinfeev,RUS,GK,CSKA Moscow,38,28,28,2520,28.0,21,0.75,71,53,74.6,15,8,5,12,42.9,3,3,0,0,0.0,1.0,0,0,0,0,0,0,0,1
3,Rustam Yatimov,TJK,GK,Rostov,26,20,20,1771,19.7,26,1.32,81,57,70.4,9,6,5,3,15.0,3,2,0,1,0.0,1.5,0,0,0,0,0,0,0,1
4,Aleksandr Belenov,RUS,GK,Fakel Voronezh,37,12,12,1080,12.0,17,1.42,48,31,64.6,1,4,7,3,25.0,0,0,0,0,0.0,0.1,0,0,0,0,0,0,0,1
6,Vitali Gudiyev,RUS,GK,Fakel Voronezh,29,18,18,1620,18.0,25,1.39,78,59,75.6,1,8,9,5,27.8,6,6,0,0,0.0,0.4,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,Anatolii Trubin,UKR,GK,Benfica,22,32,32,2880,32.0,28,0.87,97,72,73.2,23,5,4,13,40.6,3,2,1,0,33.3,28.0,0,0,0,0,0,0,1,0
348,Joao Valido,POR,GK,Arouca,24,5,5,450,5.0,6,1.20,19,14,73.7,1,3,1,1,20.0,1,1,0,0,0.0,0.3,0,0,0,0,0,0,1,0
349,Bruno Varela,CPV,GK,Vitoria Guimarães,29,34,34,3060,34.0,37,1.09,98,63,67.3,14,12,8,13,38.2,7,5,0,2,0.0,2.5,0,0,0,0,0,0,1,0
350,Ricardo Velho,POR,GK,Farense,25,28,28,2520,28.0,40,1.43,123,89,72.4,3,9,16,6,21.4,7,6,0,1,0.0,4.0,0,0,0,0,0,0,1,0
351,Ivan Zlobin,RUS,GK,Famalicão,27,15,15,1350,15.0,18,1.20,62,45,72.6,4,7,4,5,33.3,1,1,0,0,0.0,1.5,0,0,0,0,0,0,1,0

In [11]:
leagues_encoded_filtered['Value'] = np.log(leagues_encoded_filtered['Value'])
leagues_encoded_filtered

C:\Users\denis\AppData\Local\Temp\ipykernel_14416\689402320.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  leagues_encoded_filtered['Value'] = np.log(leagues_encoded_filtered['Value'])

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,GA,GA90,SoTA,Saves,Save%,W,D,L,CS,CS%,PKatt,PKA,PKsv,PKm,PKsv%,Value,league_ES1,league_FR1,league_GB1,league_IT1,league_L1,league_NL1,league_PO1,league_RU1
1,Stanislav Agkatsev,RUS,GK,Krasnodar,22,30,30,2700,30.0,23,0.77,98,79,77.6,20,7,3,15,50.0,4,1,3,0,75.0,2.014903,0,0,0,0,0,0,0,1
2,Igor Akinfeev,RUS,GK,CSKA Moscow,38,28,28,2520,28.0,21,0.75,71,53,74.6,15,8,5,12,42.9,3,3,0,0,0.0,0.000000,0,0,0,0,0,0,0,1
3,Rustam Yatimov,TJK,GK,Rostov,26,20,20,1771,19.7,26,1.32,81,57,70.4,9,6,5,3,15.0,3,2,0,1,0.0,0.405465,0,0,0,0,0,0,0,1
4,Aleksandr Belenov,RUS,GK,Fakel Voronezh,37,12,12,1080,12.0,17,1.42,48,31,64.6,1,4,7,3,25.0,0,0,0,0,0.0,-2.302585,0,0,0,0,0,0,0,1
6,Vitali Gudiyev,RUS,GK,Fakel Voronezh,29,18,18,1620,18.0,25,1.39,78,59,75.6,1,8,9,5,27.8,6,6,0,0,0.0,-0.916291,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,Anatolii Trubin,UKR,GK,Benfica,22,32,32,2880,32.0,28,0.87,97,72,73.2,23,5,4,13,40.6,3,2,1,0,33.3,3.332205,0,0,0,0,0,0,1,0
348,Joao Valido,POR,GK,Arouca,24,5,5,450,5.0,6,1.20,19,14,73.7,1,3,1,1,20.0,1,1,0,0,0.0,-1.203973,0,0,0,0,0,0,1,0
349,Bruno Varela,CPV,GK,Vitoria Guimarães,29,34,34,3060,34.0,37,1.09,98,63,67.3,14,12,8,13,38.2,7,5,0,2,0.0,0.916291,0,0,0,0,0,0,1,0
350,Ricardo Velho,POR,GK,Farense,25,28,28,2520,28.0,40,1.43,123,89,72.4,3,9,16,6,21.4,7,6,0,1,0.0,1.386294,0,0,0,0,0,0,1,0
351,Ivan Zlobin,RUS,GK,Famalicão,27,15,15,1350,15.0,18,1.20,62,45,72.6,4,7,4,5,33.3,1,1,0,0,0.0,0.405465,0,0,0,0,0,0,1,0

In [16]:
y = leagues_encoded_filtered.loc[:, 'Value']
X = leagues_encoded_filtered.drop(['Value', 'Pos', 'Nation', 'Squad'], axis=1)

In [14]:
y = leagues_encoded_filtered[leagues_encoded_filtered['Pos']=='DF'].loc[:,'Value']
X = leagues_encoded_filtered[leagues_encoded_filtered['Pos']=='DF'].drop(['Value', 'Pos', 'Nation', 'Squad', 'xG', 'npxG', 'xAG', 'npxG+xAG', 'PrgC', 'PrgP', 'PrgR', 'xG.1', 'xAG.1', 'xG+xAG', 'npxG.1', 'npxG+xAG.1'], axis=1)

In [17]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [18]:
X_test['Player'].to_csv('../data/raw/final_datasets/for_linear_model/GK/test_players_names.csv', index=False)
X_train['Player'].to_csv('../data/raw/final_datasets/for_linear_model/GK/train_players_names.csv', index=False)
X_test = X_test.drop('Player', axis=1)
X_train = X_train.drop('Player', axis=1)

In [19]:
scaler = StandardScaler()
#league_cols = ['league_ES1', 'league_FR1', 'league_GB1', 'league_IT1', 'league_L1', 'league_NL1', 'league_PO1', 'league_RU1']

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns)
# X_train_scaled[league_cols] = X_train[league_cols].values
# X_test_scaled[league_cols] = X_test[league_cols].values

In [20]:
X_train_scaled.to_csv('../data/processed/for_linear_model/GK/predictors_train_filtered.csv', index=False)
X_test_scaled.to_csv('../data/processed/for_linear_model/GK/predictors_test_filtered.csv', index=False)
y_train.to_csv('../data/processed/for_linear_model/GK/target_train_filtered_logariphmed.csv', index=False)
y_test.to_csv('../data/processed/for_linear_model/GK/target_test_filtered_logariphmed.csv', index=False)

In [6]:
duplicates = gks[gks.duplicated(subset=['Player', 'Age', 'Nation'], keep=False)]
duplicates

Empty DataFrame
Columns: [Player, Nation, Pos, Squad, Age, MP, Starts, Min, 90s, GA, GA90, SoTA, Saves, Save%, W, D, L, CS, CS%, PKatt, PKA, PKsv, PKm, PKsv%, Value, league]
Index: []

In [ ]:
grouped_gk = duplicates.groupby(['Player', 'Age', 'Nation'])
for _, group in grouped_gk:
    #print(group)
    ind_to_save = group.index[0]
    ind_to_del = group.index[1]
    group = group.reset_index(drop=True)
    if group.at[1, '90s'] > group.at[0, '90s']:
        group.at[0, 'Squad'] = group.at[1, 'Squad']
        group.at[0, 'league'] = group.at[1, 'league']
    for col in group.columns[5:len(group.columns) - 2]:
        group.at[0, col] += group.at[1, col]
    group.at[0, 'GA90'] = group.at[0, 'GA'] / group.at[0, '90s']
    group.at[0, 'Save%'] = group.at[0, 'Saves'] / group.at[0, 'SoTA'] * 100
    group.at[0, 'CS%'] = group.at[0, 'CS'] / group.at[0, 'MP'] * 100
    if group.at[0, 'PKatt'] != 0:
        group.at[0, 'PKsv%'] = group.at[0, 'PKsv'] / (group.at[0, 'PKatt'] - group.at[0, 'PKm']) * 100
    gks.loc[ind_to_save] = group.loc[0]
    gks = gks.drop(ind_to_del)

In [ ]:
gks.to_csv('../data/raw/stats/combine_gk_24-25.csv', index=False)