In [1]:
import pandas as pd

pd.options.display.max_columns = 37
pd.set_option('display.width', None)
pd.set_option('display.max_rows', None)

In [12]:
changes_final = {
    'é':'e',
    'ç':'c',
    'Ї':'I',
    'ć':'c',
    'ě':'e',
    'á':'a',
    'ä':'a',
    'ñ':'n',
    'ô':'o',
    'Ž':'Z',
    'ë':'e',
    'ã':'a',
    'ł':'l',
    'ś':'s',
    'Ó':'O',
    'š':'s',
    'Đ':'Dj',
    'ü':'u',
    'Á':'A',
    'ú':'u',
    'â':'a',
    'É':'E',
    'ê':'e',
    'í':'i',
    'ö':'o',
    'č':'c',
    'Ñ':'N',
    'Ö':'O',
    'ø':'o',
    'Ü':'U',
    'ę':'e',
    'ğ':'g',
    'ı':'i',
    'Þ':'Th',
    'è':'e',
    'ð':'d',
    'ý':'y',
    'Š':'S',
    'Ć':'C',
    'ž':'z',
    'ş':'s',
    'đ':'dj',
    'ò':'o',
    'ș':'s',
    'ă':'a',
    'Ç':'C',
    'Č':'C',
    'æ':'ae',
    'ń':'n',
    'ă':'a',
    'ț':'t',
    'Ł':'L',
    'ì':'i',
    'Ż':'Z',
    'ź':'z',
    'ō':'o',
    'ß':'ss',
    'ř':'r',
    'å':'a',
    'À':'A',
    'Ú':'U',
    'ů':'u',
    'õ':'o',
    'ū':'u',
    'ó':'o',
    'ï':'i',
    '\xad':''
}

changes = {
    'Г©':'é',
    'Г§':'ç',
    'ГЇ':'i',
    'Д‡':'ć',
    'Гі':'o',
    'Д›':'ě',
    'ГЎ':'á',
    'Г¤':'ä',
    'Г±':'ñ',
    'Гґ':'ô',
    'ЕЅ':'Ž',
    'Г«':'ë',
    'ГЈ':'ã',
    'Е‚':'ł',
    'Е›':'ś',
    'Г“':'Ó',
    'ЕЎ':'š',
    'Дђ':'Đ',
    'ГЃ':'Á',
    'Гє':'ú',
    'Гў':'â',
    'Г‰':'É',
    'ГЄ':'ê',
    'Гј':'ü',
    'Г¶':'ö',
    'ДЌ':'č',
    'Г‘':'Ñ',
    'Г–':'Ö',
    'Гё':'ø',
    'Гњ':'Ü',
    'Д™':'ę',
    'Дџ':'ğ',
    'Д±':'ı',
    'Гћ':'Þ',
    'ГЁ':'è',
    'Г°':'ð',
    'ГЅ':'ý',
    'Е ':'Š',
    'Д†':'Ć',
    'Еѕ':'ž',
    'Еџ':'ş',
    'Д‘':'đ',
    'ГІ':'ò',
    'Дѓ':'ă',
    'И™':'ș',
    'Г‡':'Ç',
    'ДЊ':'Č',
    'Г¦':'æ',
    'Е„':'ń',
    'Дѓ':'ă',
    'И›':'ț',
    'ЕЃ':'Ł',
    'Г¬':'ì',
    'Е»':'Ż',
    'Еє':'ź',
    'ЕЌ':'ō',
    'Гџ':'ß',
    'Е™':'ř',
    'ГҐ':'å',
    'Гљ':'Ú',
    'ГЂ':'À',
    'ЕЇ':'ů',
    'вЂ™':'’',
    'Гµ':'õ',
    'Е«':'ū',
    'Г‚':'Â',
    

    #'Г':'í'
}

champ_ids = ['BE1', 'BRA1', 'ES1', 'FR1', 'GB1', 'IT1', 'L1', 'NL1', 'PO1', 'RU1']

In [209]:
stats = pd.read_csv('../data/raw/stats/PO1_players_24-25.csv')
shooting = pd.read_csv('../data/raw/stats/PO1_misc_24-25.csv')

In [210]:
for i in range(len(stats)):
    if stats.at[i, 'Age'] != shooting.at[i, 'Age']:
        print(stats.loc[i])

In [159]:
stats.loc[45:50]

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,xG,...,npxG.1,npxG+xAG.1,Value,2CrdY,Fls,Fld,Off,Crs,Int,TklW,OG,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT
45,Jan Bednarek,POL,DF,Southampton,28.0,30,30,2531,28.1,2,0,2,2,0,0,7,0,0.7,...,0.02,0.04,9.0,0,0,1,0,0,0,0,0,5.0,3.0,60.0,0.18,0.11,0.40,0.67
46,Armel Bella Kotchap,GER,DF,Southampton,22.0,4,2,331,3.7,0,0,0,0,0,0,0,0,0.3,...,0.09,0.09,9.0,0,31,13,0,1,55,19,0,1.0,0.0,0.0,0.27,0.00,0.00,0.00
47,Jean-Ricner Bellegarde,FRA,"MF,FW",Wolves,26.0,35,20,1677,18.6,2,7,9,2,0,0,3,0,1.5,...,0.08,0.29,18.0,0,3,2,0,0,5,5,0,22.0,5.0,22.7,1.18,0.27,0.09,0.40
48,Rodrigo Bentancur,URU,MF,Tottenham,27.0,26,21,1645,18.3,2,0,2,2,0,0,9,0,1.3,...,0.07,0.10,30.0,0,31,46,1,42,8,23,0,22.0,6.0,27.3,1.20,0.33,0.09,0.33
49,Daniel Bentley,ENG,GK,Wolves,31.0,2,2,180,2.0,0,0,0,0,0,0,0,0,0.0,...,0.00,0.00,1.5,0,34,10,1,4,38,22,0,0.0,0.0,0.0,0.00,0.00,0.00,0.00
50,Sander Berge,NOR,MF,Fulham,26.0,31,26,2224,24.7,0,0,0,0,0,0,6,0,0.4,...,0.01,0.04,25.0,0,0,0,0,0,0,0,0,3.0,1.0,33.3,0.12,0.04,0.00,0.00

In [160]:
shooting.loc[45:50]

,Player,Nation,Pos,Squad,Age,90s,CrdY,CrdR,2CrdY,Fls,Fld,Off,Crs,Int,TklW,PKwon,PKcon,OG
45,Altay BayД±ndД±r,TUR,GK,Manchester Utd,26.0,4.0,0,0,0,0,1,0,0,0,0,NaN,NaN,0
46,Jan Bednarek,POL,DF,Southampton,28.0,28.1,7,0,0,31,13,0,1,55,19,NaN,NaN,0
47,Armel Bella Kotchap,GER,DF,Southampton,22.0,3.7,0,0,0,3,2,0,0,5,5,NaN,NaN,0
48,Jean-Ricner Bellegarde,HAI,MF,Wolves,26.0,18.6,3,0,0,31,46,1,42,8,23,NaN,NaN,0
49,Rodrigo Bentancur,URU,MF,Tottenham Hotspur,27.0,18.3,9,0,0,34,10,1,4,38,22,NaN,NaN,0
50,Daniel Bentley,ENG,GK,Wolves,31.0,2.0,0,0,0,0,0,0,0,0,0,NaN,NaN,0

In [162]:
for letter in changes:
    shooting['Player'] = shooting['Player'].str.replace(letter, changes[letter])
for letter in changes_final:
    shooting['Player'] = shooting['Player'].str.replace(letter, changes_final[letter])
shooting.loc[45:50]

,Player,Nation,Pos,Squad,Age,90s,CrdY,CrdR,2CrdY,Fls,Fld,Off,Crs,Int,TklW,PKwon,PKcon,OG
45,Altay Bayindir,TUR,GK,Manchester Utd,26.0,4.0,0,0,0,0,1,0,0,0,0,NaN,NaN,0
46,Jan Bednarek,POL,DF,Southampton,28.0,28.1,7,0,0,31,13,0,1,55,19,NaN,NaN,0
47,Armel Bella Kotchap,GER,DF,Southampton,22.0,3.7,0,0,0,3,2,0,0,5,5,NaN,NaN,0
48,Jean-Ricner Bellegarde,HAI,MF,Wolves,26.0,18.6,3,0,0,31,46,1,42,8,23,NaN,NaN,0
49,Rodrigo Bentancur,URU,MF,Tottenham Hotspur,27.0,18.3,9,0,0,34,10,1,4,38,22,NaN,NaN,0
50,Daniel Bentley,ENG,GK,Wolves,31.0,2.0,0,0,0,0,0,0,0,0,0,NaN,NaN,0

In [163]:
for letter in changes_final:
    stats['Player'] = stats['Player'].str.replace(letter, changes_final[letter])

In [164]:
df = stats.drop(['2CrdY', 'Fls', 'Fld', 'Off', 'Crs', 'Int', 'TklW', 'OG'], axis=1).merge(shooting[['Player', '2CrdY', 'Fls', 'Fld', 'Off', 'Crs', 'Int', 'TklW', 'OG']], how='left', on='Player')

In [165]:
df[df['2CrdY'].isna()]

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,xG,...,npxG.1,npxG+xAG.1,Value,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,2CrdY,Fls,Fld,Off,Crs,Int,TklW,OG
39,Benoît Badiashile,FRA,DF,Chelsea,23.0,5,3,334,3.7,0,0,0,0,0,0,0,0,0.0,...,0.00,0.00,22.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,Vladimir Coufal,CZE,DF,West Ham,31.0,22,11,1067,11.9,0,0,0,0,0,0,5,0,0.3,...,0.03,0.08,5.0,7.0,2.0,28.6,0.59,0.17,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,Luis Diaz,COL,FW,Liverpool,27.0,36,28,2399,26.7,13,5,18,13,0,0,2,0,12.0,...,0.45,0.64,70.0,71.0,30.0,42.3,2.66,1.13,0.18,0.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,Nicolas Dominguez,ARG,"MF,FW",Nott'ham Forest,26.0,34,23,1963,21.8,0,1,1,0,0,0,9,0,1.5,...,0.07,0.13,18.0,21.0,9.0,42.9,0.96,0.41,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,Andres Garcia,ESP,"DF,MF",Aston Villa,21.0,7,5,318,3.5,0,0,0,0,0,0,0,0,0.0,...,0.01,0.06,7.0,2.0,0.0,0.0,0.57,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,İlkay Gundogan,GER,MF,Manchester City,33.0,33,25,2223,24.7,1,6,7,1,0,0,1,0,3.2,...,0.13,0.27,5.0,27.0,7.0,25.9,1.09,0.28,0.04,0.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,Caoimhin Kelleher,IRL,GK,Liverpool,25.0,10,10,900,10.0,0,0,0,0,0,0,0,0,0.0,...,0.00,0.00,20.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,Antonin Kinsky,CZE,GK,Tottenham,21.0,6,6,540,6.0,0,0,0,0,0,0,0,0,0.0,...,0.00,0.01,15.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,Emiliano Martinez,ARG,GK,Aston Villa,31.0,37,37,3194,35.5,0,0,0,0,0,0,5,1,0.0,...,0.00,0.02,20.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,Lisandro Martinez,ARG,DF,Manchester Utd,26.0,20,20,1751,19.5,2,1,3,2,0,0,7,0,1.3,...,0.07,0.13,40.0,17.0,6.0,35.3,0.87,0.31,0.12,0.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
398,Hakon Rafn Valdimarsson,ISL,GK,Brentford,22.0,2,1,145,1.6,0,0,0,0,0,0,0,0,0.0,...,0.00,0.00,2.5,0.0,0.0,0.0,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
414,Guido Rodriguez,ARG,MF,West Ham,30.0,23,16,1149,12.8,0,1,1,0,0,0,6,0,0.2,...,0.02,0.03,10.0,8.0,1.0,12.5,0.63,0.08,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,Manuel Ugarte Ribeiro,URU,MF,Manchester Utd,23.0,29,22,1785,19.8,1,2,3,1,0,0,11,0,1.0,...,0.05,0.11,45.0,19.0,4.0,21.1,0.96,0.20,0.05,0.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506,Carlos Vinicius,BRA,"MF,FW",Fulham,29.0,3,0,16,0.2,0,0,0,0,0,0,0,0,0.0,...,0.21,0.21,3.5,1.0,1.0,100.0,5.63,5.63,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
539,Martin Ødegaard,NOR,MF,Arsenal,25.0,30,26,2325,25.8,3,8,11,2,1,1,4,0,4.8,...,0.16,0.37,85.0,49.0,17.0,34.7,1.90,0.66,0.04,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [200]:
shooting[shooting['Player'].str.contains('degaa')]

,Player,Nation,Pos,Squad,Age,90s,CrdY,CrdR,2CrdY,Fls,Fld,Off,Crs,Int,TklW,PKwon,PKcon,OG
561,Martin Гdegaard,NOR,MF,Arsenal,25.0,25.8,4,0,0,12,23,1,86,6,8,NaN,NaN,0

In [201]:
df.iloc[539, 42:] = [0, 12, 23, 1, 86, 6, 8, 0]
df.iloc[539]

Player        Martin Ødegaard
Nation                    NOR
Pos                        MF
Squad                 Arsenal
Age                      25.0
MP                         30
Starts                     26
Min                      2325
90s                      25.8
Gls                         3
Ast                         8
G+A                        11
G-PK                        2
PK                          1
PKatt                       1
CrdY                        4
CrdR                        0
xG                        4.8
npxG                      4.0
xAG                       5.4
npxG+xAG                  9.5
PrgC                       92
PrgP                      258
PrgR                      154
Gls.1                    0.12
Ast.1                    0.31
G+A.1                    0.43
G-PK.1                   0.08
G+A-PK                   0.39
xG.1                     0.19
xAG.1                    0.21
xG+xAG                    0.4
npxG.1                   0.16
npxG+xAG.1               0.37
Value                    85.0
Sh                       49.0
SoT                      17.0
SoT%                     34.7
Sh/90                     1.9
SoT/90                   0.66
G/Sh                     0.04
G/SoT                    0.12
2CrdY                     0.0
Fls                      12.0
Fld                      23.0
Off                       1.0
Crs                      86.0
Int                       6.0
TklW                      8.0
OG                        0.0
Name: 539, dtype: object

In [202]:
df.to_csv('../data/raw/stats/GB1_players_24-25.csv', index=False)

In [141]:
df.columns[42]

'2CrdY'