In [1]:
import pandas as pd
from copy import copy

pd.options.display.max_columns = 37
pd.set_option('display.width', None)
pd.set_option('display.max_rows', None)

In [11]:
stats = pd.read_csv('csv/stats/RU1_players_24-25.csv')
values = pd.read_csv('csv/values/PO1_players_values_24-25.csv')

In [2]:
changes = {
    'é':'e',
    'ç':'c',
    'Ї':'I',
    'ć':'c',
    'ě':'e',
    'á':'a',
    'ä':'a',
    'ñ':'n',
    'ô':'o',
    'Ž':'Z',
    'ë':'e',
    'ã':'a',
    'ł':'l',
    'ś':'s',
    'Ó':'O',
    'š':'s',
    'Đ':'Dj',
    'ü':'u',
    'Á':'A',
    'ú':'u',
    'â':'a',
    'É':'E',
    'ê':'e',
    'í':'i',
    'ö':'o',
    'č':'c',
    'Ñ':'N',
    'Ö':'O',
    'ø':'o',
    'Ü':'U',
    'ę':'e',
    'ğ':'g',
    'ı':'i',
    'Þ':'Th',
    'è':'e',
    'ð':'d',
    'ý':'y',
    'Š':'S',
    'Ć':'C',
    'ž':'z',
    'ş':'s',
    'đ':'dj',
    'ò':'o',
    'ș':'s',
    'ă':'a',
    'Ç':'C',
    'Č':'C',
    'æ':'ae',
    'ń':'n',
    'ă':'a',
    'ț':'t',
    'Ł':'L',
    'ì':'i',
    'Ż':'Z',
    'ź':'z',
    'ō':'o',
    'ß':'ss',
    'ř':'r',
    'å':'a',
    'À':'A',
    'Ú':'U',
    'ů':'u',
    'õ':'o',
    'ū':'u',
    'ó':'o',
    'ï':'i',
    '\xad':''
}

champ_ids = ['BE1', 'BRA1', 'ES1', 'FR1', 'GB1', 'IT1', 'L1', 'NL1', 'PO1', 'RU1']

In [2]:
def unite_duplicates(stats):
    pairs_to_unite = []
    for i in stats[stats.duplicated(subset=['Player', 'Age', 'Nation'], keep='last')].index:
        pairs_to_unite.append((i, i+1))
    duplicated_players = stats[stats.duplicated(subset=['Player', 'Age', 'Nation'], keep=False)]
    stats = stats.drop_duplicates(subset=['Player', 'Age', 'Nation'], keep='last')
    for pair in pairs_to_unite:
        for col in stats.columns[5:24]:
            stats.at[pair[1], col] = duplicated_players.at[pair[0], col] + duplicated_players.at[pair[1], col]
        stats.at[pair[1], 'Gls.1'] = stats.at[pair[1], 'Gls']/stats.at[pair[1], '90s']
        stats.at[pair[1], 'Ast.1'] = stats.at[pair[1], 'Ast']/stats.at[pair[1], '90s']
        stats.at[pair[1], 'G+A.1'] = stats.at[pair[1], 'G+A']/stats.at[pair[1], '90s']
        stats.at[pair[1], 'G-PK.1'] = stats.at[pair[1], 'G-PK']/stats.at[pair[1], '90s']
        stats.at[pair[1], 'G+A-PK'] = (stats.at[pair[1], 'G-PK'] + stats.at[pair[1], 'Ast'])/stats.at[pair[1], '90s']
        stats.at[pair[1], 'xG.1'] = stats.at[pair[1], 'xG']/stats.at[pair[1], '90s']
        stats.at[pair[1], 'xAG.1'] = stats.at[pair[1], 'xAG']/stats.at[pair[1], '90s']
        stats.at[pair[1], 'xG+xAG'] = (stats.at[pair[1], 'xAG'] + stats.at[pair[1], 'xG'])/stats.at[pair[1], '90s']
        stats.at[pair[1], 'npxG.1'] = stats.at[pair[1], 'npxG']/stats.at[pair[1], '90s']
        stats.at[pair[1], 'npxG+xAG.1'] = stats.at[pair[1], 'npxG+xAG']/stats.at[pair[1], '90s']
        if pd.isna(stats.at[pair[1], 'Value']):
            stats.at[pair[1], 'Value'] = duplicated_players.at[pair[0], 'Value']
    cols = list(stats.columns)
    for i in range(cols.index('Gls.1'), len(cols)-1):
        stats[cols[i]] = stats[cols[i]].round(2)
    return stats
            

def do_join(stats, values):
    vals = copy(values)
    for letter in changes:
        stats['Player'] = stats['Player'].str.replace(letter, changes[letter])
        vals['Player'] = vals['Player'].str.replace(letter, changes[letter])
    stats['Value'] = [pd.NA]*len(stats)
    for i in range(len(stats)):
        for j in range(len(vals)):
            if stats.at[i, 'Player']==vals.at[j,'Player'] and stats.at[i,'Squad']==vals.at[j, 'Squad']:
                stats.at[i, 'Value'] = vals.at[j, 'Value']
                vals.drop(j)
                j-=1
    na_indexes = stats[stats['Value'].isna()].index
    for i in na_indexes:
        names = stats.at[i,'Player'].split(' ')
        for j in range(len(vals)):
            if stats.at[i,'Squad']==vals.at[j, 'Squad'] and any(name == vals.at[j,'Player'] for name in names):
                stats.at[i, 'Value'] = vals.at[j, 'Value']
                vals.drop(j)
                j-=1
    na_indexes = stats[stats['Value'].isna()].index
    for i in na_indexes:
        for j in range(len(vals)):
            names = vals.at[j,'Player'].split(' ')
            if stats.at[i, 'Squad']==vals.at[j,'Squad'] and any(stats.at[i,'Player'] == name for name in names):
                stats.at[i,'Value'] = vals.at[j,'Value']
                vals.drop(j)
                j-=1

In [92]:
merged_stats = stats.merge(values, on=['Player', 'Squad'], how='left')
print("количество null-стоимостей - ", len(merged_stats[merged_stats['Value'].isna()]))
merged_stats

количество null-стоимостей -  173

                              Player Nation    Pos           Squad  Age  MP  \
0                    Rodrigo Abascal    URU     DF        Boavista   30  29
1                       Nelson Abbey    ENG     DF         Rio Ave   20   8
2            Bilal Abdelrahman Zeeni    EGY     MF         Estrela   21   1
3                   Giorgi Aburjania    GEO     MF     AVS Futebol   29   9
4                            Adriano    BRA     MF     Santa Clara   24  32
5                       Lucas Áfrico    BRA     DF         Farense   29  21
6                      Salvador Agra    POR  MF,DF        Boavista   32  32
7                   Brandon Aguilera    CRC  MF,FW         Rio Ave   21  25
8                      Jorge Aguirre    CUB     FW  Gil Vicente FC   24  31
9                 Babatunde Akinsola    NGA  MF,FW     AVS Futebol   21  30
10                  Kerem Aktürkoğlu    TUR  FW,MF         Benfica   25  30
11                         Léo Alaba    BRA     DF     AVS Futebol   25   4
12                              Alan    BRA     MF      Moreirense   24  31
13                   Gonçalo Almeida    POR  DF,MF        Boavista   21  19
14                      Pedro Álvaro    POR     DF         Estoril   24  31
15                      Pedro Amaral    POR  DF,MF         Estoril   26  29
16                      Zeki Amdouni    SUI  MF,FW         Benfica   23  24
17        Artur Jorge Marques Amorim    POR     DF         Farense   29  19
18                            Andrew    BRA     GK  Gil Vicente FC   23  33
19                  Jeremy Antonisse    CUW  FW,MF      Moreirense   22  29
20                      Arvin Appiah    ENG  DF,FW        Nacional   23  26
21                      Óscar Aranda    ESP     FW       Famalicão   22  33
22                      Brian Araújo    FRA     GK  Gil Vicente FC   24   1
23                   Henrique Araújo    POR     FW          Arouca   22  24
24                Maximiliano Araújo    URU  DF,MF     Sporting CP   24  28
25                      Tomás Araújo    POR     DF         Benfica   22  28
26                     Telmo Arcanjo    CPV     FW         Vitoria   23  28
27                     Gboly Ariyibi    USA  FW,MF        Boavista   29  11
28                  Henrique Arreiol    POR     MF     Sporting CP   19   3
29                  Bright Arrey-Mbi    GER     DF           Braga   21  15
30                      Afonso Assis    POR     MF      Moreirense   18   1
31                  Gustavo Assuncao    POR     MF     AVS Futebol   24  23
32                     Otavio Ataide    BRA     DF           Porto   22  20
33                      João Aurélio    POR  DF,FW        Nacional   35  14
34                   Fredrik Aursnes    NOR  MF,FW         Benfica   28  29
35                    Daniel Azevedo    POR     GK        Casa Pia   26   1
36                       Ibrahima Ba    SEN     DF       Famalicão   19   2
37                      Felix Bacher    AUT     DF         Estoril   23  23
38                      Miguel Baeza    ESP  MF,FW        Nacional   24   5
39                     Alexander Bah    DEN     DF         Benfica   26  18
40                         Ney Bahia    BRA     MF     Santa Clara   20   2
41                    Adrian Bajrami    SUI     DF         Benfica   22   1
42                Theofanis Bakoulas    GRE     MF         Rio Ave   19  10
43                       Elves Baldé    GNB  MF,FW         Farense   24  20
44                     Mohamed Bamba    CIV     MF  Gil Vicente FC   19  11
45                      Robson Bambu    BRA     DF           Braga   26  15
46                       Chico Banza    ANG     FW         Estrela   25  13
47                       Simon Banza    COD     FW           Braga   27   1
48                    Rafael Barbosa    POR  MF,FW         Farense   28   7
49          Leandro Barreiro Martins    LUX     MF         Benfica   24  27
50                  Gil Bastião Dias    POR  FW,MF       Famalicão   27  30
51                   Gabriel Batista    BRA     GK     Santa Clara   26  34
52                  Gilberto Batista    GNB     DF      Moreirense   20   5
53                   Ricardo Batista    POR     GK        Casa Pia   37   1
54                    Yanis Begraoui    MAR  FW,MF         Estoril   23  34
55                        Gui Beleza    POR     MF  Gil Vicente FC   17   1
56                   Bachir Belloumi    ALG     FW         Farense   22   3
57                    Andrea Belotti    ITA     FW         Benfica   30  14
58              Fahem Benaissa Yahia    FRA  MF,DF        Casa Pia   22   8
59                              Beni    ANG     MF         Vitoria   22   7
60                              Beni    ANG     MF        Casa Pia   22  13
61                      Álex Bermejo    ESP  MF,FW         Farense   25  24
62                    Sergio Bermejo    ESP  MF,FW  Gil Vicente FC   26  10
63                    Simão Bertelli    BRA     GK     AVS Futebol   31  11
64                  Jan-Niklas Beste    GER  FW,DF         Benfica   25  13
65                         José Bica    POR  FW,MF         Vitoria   21   4
66                              Biel    BRA  MF,FW     Sporting CP   23   3
67                       Raúl Blanco    ESP     FW        Casa Pia   23   5
68                     Paulinho Boia    BRA  FW,MF        Nacional   26  15
69                        Kévin Boma    TOG     DF         Estoril   21  29
70                       Pedro Bondo    ANG     DF       Famalicão   19   6
71                      Kiko Bondoso    POR  FW,MF         Rio Ave   28  28
72                   Toni Borevkovic    CRO     DF         Vitoria   27  27
73                     Daniel Borges    BRA  MF,FW     Santa Clara   21  16
74                    Gonçalo Borges    POR  FW,MF           Porto   23  26
75                   Robert Božení­k    SVK     FW        Boavista   24  33
76                   Daniel Bragança    POR     MF     Sporting CP   25  18
77                     Bruno Brigido    BRA     GK         Estrela   33  18
78                   Alexandre Brito    POR  MF,DF     Sporting CP   19   2
79                      Rafael Brito    POR     MF        Casa Pia   22  22
80                       Tiago Brito    POR     MF         Estoril   20   4
81                             Bruma    POR  FW,MF           Braga   29  17
82                             Bruma    POR  FW,MF         Benfica   29  10
83            Jonathan Buatu Mananga    ANG     DF  Gil Vicente FC   30  21
84                      Leonel Bucca    ARG  MF,FW         Estrela   25  30
85                     Leonardo Buta    POR     DF      Moreirense   22   7
86                     Adrián Butzke    ESP     FW        Nacional   25  10
87                     Arthur Cabral    BRA     FW         Benfica   26  21
88                     Daniel Cabral    BRA     MF         Estrela   22   1
89                     Jovane Cabral    CPV  FW,MF         Estrela   26  26
90                    Lucas Calegari    BRA     DF       Famalicão   22  18
91                      Diogo Calila    MOZ  MF,DF     Santa Clara   25  31
92                   Ibrahima Camará    GUI     MF        Boavista   25  26
93                    André Candeias    POR  FW,MF         Farense   21   2
94                     Lazar Carević    MNE     GK       Famalicão   25  18
95                         Zé Carlos    POR  MF,DF         Vitoria   22   7
96                         Zé Carlos    POR     MF         Farense   22   9
97                         Zé Carlos    POR     DF  Gil Vicente FC   26  31
98                   Álvaro Carreras    ESP     DF         Benfica   21  32
99                     João Carvalho    POR  MF,FW         Estoril   27  28
100                   Pedro Carvalho    POR  DF,MF         Estoril   21  19
101                   Vitor Carvalho    BRA     MF           Braga   27  23
102                  Facundo Cáseres    ARG     MF  Gil Vicente FC   23  20
103                         Cassiano    BRA     FW        Casa Pia   35  26
104                   Jesús Castillo    PER     MF  Gil Vicente FC   23  15
105                     André Castro    POR     MF      Moreirense   36   1
106                  Cristian Castro    COL     DF     AVS Futebol   23  32
107                      Geny Catamo    MOZ  MF,DF     Sporting CP   23  30
108                             Cauê    BRA     FW  Gil Vicente FC   21  15
109                             Cauê    BRA  FW,MF        Casa Pia   21  12
110                            César    BRA     GK        Boavista   32  16
111                       Kaio César    BRA     FW         Vitoria   20  17
112                  Tidjany Chabrol    FRA  FW,MF  Gil Vicente FC   22  25
113                   Kevin Chamorro    CRC     GK         Estoril   24   4
114              Francisco Chissumba    POR     DF           Braga   19  16
115                    Till Cissokho    FRA     DF         Estrela   24   4
116                          Clayton    BRA     DF     AVS Futebol   24   2
117                          Clayton    BRA     FW         Rio Ave   25  31
118                    Diego Collado    ESP  MF,FW  Gil Vicente FC   23   5
119                     Semeu Commey    GHA     DF         Estrela   20   2
120                  Fábio Conceição    POR  MF,FW         Estrela   23  11
121                  Fábio Conceição    POR  FW,DF         Rio Ave   23  12
122                     Leo Cordeiro    BRA     MF         Estrela   28  27
123                    Félix Correia    POR  FW,MF  Gil Vicente FC   23  33
124                    Alberto costa    POR     DF         Vitoria   20  10
125       Bruno Xavier Almeida Costa    POR  MF,FW        Nacional   27  18
126                      Diogo Costa    POR     GK           Porto   24  32
127                    Gonçalo Costa    POR  DF,MF         Estoril   24  18
128                     Hélder Costa    ANG  FW,MF         Estoril   30  13
129                       João Costa    POR     FW     Santa Clara   24  24
130          João Paulo Santos Costa    POR     GK         Estrela   28  14
131                     Michel Costa    BRA     MF         Estoril   22  10
132                        Rui Costa    POR  FW,MF         Farense   28  15
133                       Marco Cruz    POR  DF,MF         Vitoria   20   2
134                      Sandro Cruz    ANG     DF  Gil Vicente FC   23  25
135                     Augusto Dabo    GNB     DF        Boavista   20  13
136                      Samuel Dahl    SWE  DF,MF         Benfica   24  11
137                     Amadou Dante    MLI  DF,MF          Arouca   23  16
138                Mathias De Amorim    POR     MF       Famalicão   19  24
139                      Zeno Debast    BEL  DF,MF     Sporting CP   20  31
140                             Depú    ANG     FW  Gil Vicente FC   24   3
141                           Derick    BRA  DF,MF         Farense   30  23
142                  Ángel Di Marí­a    ARG     FW         Benfica   36  25
143                   Abdoulay Diaby    MLI  FW,MF        Boavista   33  12
144                     Matheus Dias    BRA  MF,DF        Nacional   22  26
145                       Tiago Dias    POR  FW,DF        Casa Pia   26   8
146                 Ousmane Diomande    CIV     DF     Sporting CP   20  31
147                      Tiago Djalo    POR     DF           Porto   24   8
148                 Maxime Dominguez    SUI     MF  Gil Vicente FC   28   4
149                     Issiar Dramé    MLI     DF         Estrela   25  21
150                             Dudu    BRA  FW,MF        Nacional   24  21
151                   Carlos Eduardo    BRA  FW,MF  Gil Vicente FC   21   7
152                   Marcus Edwards    ENG  MF,FW     Sporting CP   25   6
153                 Demir Ege Tıknaz    TUR     MF         Rio Ave   19  28
154                    Marvin Elimbi    FRA     DF  Gil Vicente FC   21  11
155                     Simon Elisor    FRA     FW       Famalicão   25  15
156                     Úmaro Embalo    POR  FW,MF         Vitoria   23   7
157                   Rui Encarnação    POR     GK        Nacional   26   2
158                   Ricardo Esgaio    POR     DF     Sporting CP   31   9
159                     Tiago Esgaio    POR     DF          Arouca   28  25
160                     Dario Essugo    POR     MF     Sporting CP   19   2
161                    Luí­s Esteves    POR     MF        Nacional   26  33
162                Stephen Eustáquio    CAN  MF,DF           Porto   27  30
163                        Evanilson    BRA     FW           Porto   24   1
164                   Claudio Falcão    BRA  DF,MF         Farense   30  32
165             Eduardo Felicí­ssimo    POR     MF     Sporting CP   17   6
166                       Nuno Felix    POR     MF         Benfica   20   2
167                      Vando Félix    GNB  FW,MF         Vitoria   21  16
168  Jorge Filipe Oliveira Fernandes    POR     DF         Vitoria   27   6
169                  Lucas Fernandes    BRA  MF,FW     AVS Futebol   26   8
170                 Martim Fernandes    POR     DF           Porto   18  25
171                 Mateus Fernandes    POR  FW,MF     Sporting CP   20   1
172                  Roger Fernandes    POR  FW,MF           Braga   18  28
173                  Rúben Fernandes    POR     DF  Gil Vicente FC   38  28
174                Roberto Férnandez    ESP     FW           Braga   22  15
175             João Ferreira Barros    POR  MF,FW        Boavista   18  12
176                  Filipe Ferreira    POR     DF        Boavista   33  27
177        Fernando Ferreira Fonseca    POR  DF,MF     AVS Futebol   27  26
178                    João Ferreira    POR     DF           Braga   23  21
179      Marcelo dos Santos Ferreira    BRA     DF      Moreirense   35  33
180                   Pedro Ferreira    POR     MF     Santa Clara   26  32
181                   Tiago Ferreira    POR  FW,DF         Estrela   22   3
182                  Daniel Figueira    POR     GK         Estoril   26   1
183                  Sidoine Fogning    CMR     DF        Boavista   22  13
184             Tiago Fonseca Morais    POR  FW,MF         Rio Ave   20  31
185                      José Fontán    ESP     DF          Arouca   24  29
186                       José Fonte    POR     DF        Casa Pia   40  25
187                     Lucas França    BRA     GK        Nacional   28  33
188                     André Franco    POR  MF,FW           Porto   26  17
189                   Afonso Freitas    POR     DF        Nacional   24   1
190                    Iván Fresneda    ESP  DF,MF     Sporting CP   19  18
191                Godfried Frimpong    NED     DF      Moreirense   25  30
192                   Kanya Fujimoto    JPN     MF  Gil Vicente FC   25  30
193                     Taichi Fukui    JPN     MF          Arouca   20  30
194                    Rúben Furtado    POR  FW,MF           Braga   18   4
195                    Tiago Gabriel    POR     DF         Estrela   19  11
196                           Galeno    BRA  FW,DF           Porto   26  18
197                   Tiago Galletto    URU     MF     AVS Futebol   22   3
198                     Nino Galović    CRO     DF          Arouca   32   1
199         João Tiago Serrão Garcês    POR     MF        Nacional   31   1
200                          Garcí­a    BRA     DF        Nacional   22  33
201                 Fabrí­cio Garcia    CPV  FW,DF         Estoril   23  24
202                 Santiago Garcí­a    ESP     MF  Gil Vicente FC   22  27
203                     Bruno Gaspar    ANG     DF         Vitoria   31  13
204                       Mory Gbane    CIV  MF,DF  Gil Vicente FC   23  18
205                         Geovanny    POR     MF         Farense   20   6
206                   André Geraldes    POR  MF,DF        Casa Pia   33  26
207                    Ismaël Gharbi    TUN  FW,MF           Braga   20  23
208                 Marco van Ginkel    NED  MF,FW        Boavista   31  11
209                       José Gomes    POR     DF        Nacional   28  28
210                      Pedro gomes    POR     DF        Boavista   21  21
211                     Ví­tor Gomes    POR     MF         Rio Ave   36   6
212                    William Gomes    BRA  MF,FW           Porto   18   8
213                     Victor Gomez    ESP     DF           Braga   24  27
214             Nuno Gonçalo Moreira    POR  FW,MF        Casa Pia   25  21
215             Franscisco Gonçalves    POR     DF        Nacional   20   1
216                   João Gonçalves    POR     GK        Boavista   23   4
217                  Pedro Gonçalves    POR  MF,FW     Sporting CP   26  14
218                  Cristo González    ESP     MF          Arouca   26   2
219                   Mario González    ESP     FW       Famalicão   28  16
220                 Nicolás González    ESP     MF           Porto   22  17
221                       Jean Gorby    FRA     MF           Braga   22  24
222               João Goulart Silva    POR     DF        Casa Pia   24  33
223                    Tiago Gouveia    POR  FW,DF         Benfica   23   4
224                   Pablo Gozalbez    ESP     MF          Arouca   23  17
225                       João Graça    POR  MF,FW         Rio Ave   29  16
226                   Samuel Granada    BRA     FW     AVS Futebol   24   4
227                       Jaume Grau    ESP     MF     AVS Futebol   27  29
228                     Marko Grujić    SRB     MF           Porto   28   2
229                   Marko Gudžulić    SRB     GK         Estrela   22   2
230                    Rafik Guitane    FRA  FW,MF         Estoril   25  21
231                    Rafik Guitane    FRA     FW           Braga   25   1
232                        Deniz Gül    TUR     FW           Porto   20  14
233                  Viktor Gyökeres    SWE     FW     Sporting CP   26  33
234                   Justin de Haas    NED     DF       Famalicão   24  29
235                          Habraão    BRA     FW     Santa Clara   23   1
236                     Tomás Händel    POR     MF         Vitoria   23  32
237                    Conrad Harder    DEN  FW,MF     Sporting CP   19  28
238                  Thiago Helguera    URU     MF           Braga   18   1
239                 Gustavo Henrique    BRA  MF,FW         Estrela   25   4
240                  Morten Hjulmand    DEN     MF     Sporting CP   25  28
241                 Jordan Holsgrove    SCO     MF         Estoril   24  28
242                  Lukáš Horní­ček    CZE     GK           Braga   22  17
243                      André Horta    POR     MF           Braga   27  12
244                    Ricardo Horta    POR  MF,FW           Braga   29  34
245                             Igor    BRA     MF         Estrela   21  13
246                     André Inácio    BRA  MF,FW         Estrela   22  11
247                     André Inácio    BRA  FW,MF         Rio Ave   22  16
248                   Gonçalo Inácio    POR     DF     Sporting CP   22  28
249                            Isaac    BRA     FW        Nacional   20  27
250                           Ismael    POR     MF      Moreirense   25  29
251                    Franco Israel    URU     GK     Sporting CP   24  11
252               Ivan Jaime Pajuelo    ESP     FW           Porto   23   9
253                            Jason    ESP  FW,MF          Arouca   30  32
254                         Jhonatan    BRA     GK         Rio Ave   33   8
255                  Diederrick Joel    CMR     FW        Nacional   30  14
256                    Joel Jorquera    ESP     FW      Moreirense   23  12
257           Luiz Lúcio Reis Júnior    BRA     GK       Famalicão   23   1
258                     Samuel Justo    POR     MF         Farense   20   5
259                      Issa Kaboré    BFA     DF         Benfica   23   3
260                           Kaique    BRA     GK         Farense   21   6
261                      Osman Kakay    SLE     DF        Boavista   26   9

In [93]:
do_join(stats, values)
stats = unite_duplicates(stats)
print("количество null-объектов =", len(stats[stats['Value'].isna()]))
stats[stats['Value'].isna()]

количество null-объектов = 83

C:\Users\denis\AppData\Local\Temp\ipykernel_4944\3803764476.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stats[cols[i]] = stats[cols[i]].round(2)

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1,Value
2,Bilal Abdelrahman Zeeni,EGY,MF,Estrela,21,1,0,8,0.1,0,0,0,0,0,0,0,0,0.0,0.0,0.1,0.1,0,1,1,0.00,0.00,0.00,0.00,0.00,0.18,0.81,0.98,0.18,0.98,<NA>
9,Babatunde Akinsola,NGA,"MF,FW",AVS Futebol,21,30,11,1170,13.0,2,1,3,2,0,0,1,0,2.9,2.9,0.8,3.6,43,33,88,0.15,0.08,0.23,0.15,0.23,0.22,0.06,0.28,0.22,0.28,<NA>
13,Goncalo Almeida,POR,"DF,MF",Boavista,21,19,9,814,9.0,0,0,0,0,0,0,1,0,0.7,0.7,0.9,1.6,12,18,43,0.00,0.00,0.00,0.00,0.00,0.08,0.09,0.17,0.08,0.17,<NA>
17,Artur Jorge Marques Amorim,POR,DF,Farense,29,19,15,1281,14.2,0,1,1,0,0,0,9,0,0.9,0.9,0.3,1.2,1,22,1,0.00,0.07,0.07,0.00,0.07,0.07,0.02,0.09,0.07,0.09,<NA>
24,Maximiliano Araujo,URU,"DF,MF",Sporting CP,24,28,19,1771,19.7,3,4,7,3,0,0,7,1,2.6,2.6,4.3,6.9,52,89,201,0.15,0.20,0.36,0.15,0.36,0.13,0.22,0.35,0.13,0.35,<NA>
40,Ney Bahia,BRA,MF,Santa Clara,20,2,0,62,0.7,0,0,0,0,0,0,0,0,0.1,0.1,0.0,0.1,0,0,2,0.00,0.00,0.00,0.00,0.00,0.18,0.00,0.18,0.18,0.18,<NA>
49,Leandro Barreiro Martins,LUX,MF,Benfica,24,27,11,1211,13.5,3,1,4,3,0,0,5,0,3.8,3.8,1.6,5.4,12,50,50,0.22,0.07,0.30,0.22,0.30,0.28,0.12,0.40,0.28,0.40,<NA>
50,Gil Bastiao Dias,POR,"FW,MF",Famalicão,27,30,13,1406,15.6,5,2,7,5,0,0,7,0,2.8,2.8,1.1,3.8,45,61,123,0.32,0.13,0.45,0.32,0.45,0.18,0.07,0.24,0.18,0.24,<NA>
56,Bachir Belloumi,ALG,FW,Farense,22,3,3,270,3.0,0,0,0,0,0,0,0,0,0.2,0.2,0.1,0.3,8,14,20,0.00,0.00,0.00,0.00,0.00,0.08,0.02,0.10,0.08,0.10,<NA>
58,Fahem Benaissa Yahia,FRA,"MF,DF",Casa Pia,22,8,4,386,4.3,1,0,1,1,0,0,1,0,0.3,0.3,0.0,0.3,10,10,19,0.23,0.00,0.23,0.23,0.23,0.07,0.00,0.07,0.07,0.07,<NA>
64,Jan-Niklas Beste,GER,"FW,DF",Benfica,25,13,5,501,5.6,0,1,1,0,0,0,3,0,0.7,0.7,1.5,2.2,23,21,67,0.00,0.18,0.18,0.00,0.18,0.12,0.27,0.40,0.12,0.40,<NA>
73,Daniel Borges,BRA,"MF,FW",Santa Clara,21,16,1,194,2.2,0,0,0,0,0,0,1,0,0.3,0.3,0.2,0.5,3,7,6,0.00,0.00,0.00,0.00,0.00,0.15,0.09,0.24,0.15,0.24,<NA>
83,Jonathan Buatu Mananga,ANG,DF,Gil Vicente FC,30,21,20,1824,20.3,0,2,2,0,0,0,1,0,0.4,0.4,0.9,1.3,9,44,0,0.00,0.10,0.10,0.00,0.10,0.02,0.05,0.07,0.02,0.07,<NA>
106,Cristian Castro,COL,DF,AVS Futebol,23,32,32,2745,30.5,1,1,2,1,0,0,5,0,0.6,0.6,1.4,2.0,10,65,1,0.03,0.03,0.07,0.03,0.07,0.02,0.04,0.07,0.02,0.07,<NA>
112,Tidjany Chabrol,FRA,"FW,MF",Gil Vicente FC,22,25,13,1046,11.6,1,2,3,1,0,0,4,1,1.8,1.8,1.0,2.8,37,29,78,0.09,0.17,0.26,0.09,0.26,0.16,0.08,0.24,0.16,0.24,<NA>
121,Fabio Conceicao,POR,"FW,DF",Rio Ave,23,23,9,1103,12.3,1,1,2,1,0,0,0,0,1.0,1.0,1.3,2.3,28,30,80,0.08,0.08,0.16,0.08,0.16,0.08,0.11,0.19,0.08,0.19,<NA>
124,Alberto costa,POR,DF,Vitoria,20,10,7,675,7.5,0,2,2,0,0,0,0,0,0.2,0.2,1.5,1.7,30,31,52,0.00,0.27,0.27,0.00,0.27,0.03,0.20,0.23,0.03,0.23,<NA>
125,Bruno Xavier Almeida Costa,POR,"MF,FW",Nacional,27,18,11,919,10.2,2,1,3,1,1,1,0,0,1.7,0.9,1.8,2.7,16,40,35,0.20,0.10,0.29,0.10,0.20,0.17,0.17,0.34,0.09,0.26,<NA>
130,Joao Paulo Santos Costa,POR,GK,Estrela,28,14,14,1260,14.0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,<NA>
138,Mathias De Amorim,POR,MF,Famalicão,19,24,10,1072,11.9,1,1,2,1,0,0,4,0,1.2,1.2,1.5,2.6,13,62,60,0.08,0.08,0.17,0.08,0.17,0.10,0.12,0.22,0.10,0.22,<NA>
168,Jorge Filipe Oliveira Fernandes,POR,DF,Vitoria,27,6,5,415,4.6,0,0,0,0,0,0,0,0,0.1,0.1,0.3,0.4,2,25,1,0.00,0.00,0.00,0.00,0.00,0.02,0.08,0.10,0.02,0.10,<NA>
175,Joao Ferreira Barros,POR,"MF,FW",Boavista,18,12,2,260,2.9,0,0,0,0,0,0,1,0,0.4,0.4,0.1,0.5,8,5,11,0.00,0.00,0.00,0.00,0.00,0.13,0.03,0.16,0.13,0.16,<NA>
177,Fernando Ferreira Fonseca,POR,"DF,MF",AVS Futebol,27,26,21,1908,21.2,0,0,0,0,0,0,9,0,0.3,0.3,1.8,2.1,38,72,59,0.00,0.00,0.00,0.00,0.00,0.01,0.08,0.10,0.01,0.10,<NA>
181,Tiago Ferreira,POR,"FW,DF",Estrela,22,3,1,53,0.6,0,0,0,0,0,0,0,0,0.0,0.0,0.1,0.1,0,2,6,0.00,0.00,0.00,0.00,0.00,0.05,0.11,0.16,0.05,0.16,<NA>
182,Daniel Figueira,POR,GK,Estoril,26,1,1,90,1.0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,<NA>
184,Tiago Fonseca Morais,POR,"FW,MF",Rio Ave,20,31,18,1562,17.4,4,0,4,4,0,1,1,0,3.8,3.0,1.7,4.7,36,63,101,0.23,0.00,0.23,0.23,0.23,0.22,0.10,0.32,0.17,0.27,<NA>
197,Tiago Galletto,URU,MF,AVS Futebol,22,3,0,90,1.0,0,0,0,0,0,0,2,0,0.0,0.0,0.0,0.0,0,1,0,0.00,0.00,0.00,0.00,0.00,0.02,0.00,0.02,0.02,0.02,<NA>
199,Joao Tiago Serrao Garces,POR,MF,Nacional,31,1,0,17,0.2,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.07,0.00,0.07,0.07,0.07,<NA>
202,Santiago Garcia,ESP,MF,Gil Vicente FC,22,27,16,1475,16.4,4,2,6,4,0,0,10,0,1.4,1.4,1.3,2.7,17,66,46,0.24,0.12,0.37,0.24,0.37,0.09,0.08,0.17,0.09,0.17,<NA>
205,Geovanny,POR,MF,Farense,20,6,1,164,1.8,0,0,0,0,0,0,0,0,0.1,0.1,0.0,0.1,0,6,5,0.00,0.00,0.00,0.00,0.00,0.04,0.00,0.04,0.04,0.04,<NA>
210,Pedro gomes,POR,DF,Boavista,21,21,18,1452,16.1,0,0,0,0,0,0,7,1,0.9,0.9,0.1,1.0,2,35,16,0.00,0.00,0.00,0.00,0.00,0.06,0.01,0.06,0.06,0.06,<NA>
214,Nuno Goncalo Moreira,POR,"FW,MF",Casa Pia,25,21,18,1491,16.6,5,5,10,5,0,0,3,1,3.0,3.0,2.1,5.1,40,79,89,0.30,0.30,0.60,0.30,0.60,0.18,0.13,0.31,0.18,0.31,<NA>
215,Franscisco Goncalves,POR,DF,Nacional,20,1,0,18,0.2,0,0,0,0,0,0,1,0,0.0,0.0,0.0,0.0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,<NA>
220,Nicolas Gonzalez,ESP,MF,Porto,22,17,17,1441,16.0,5,3,8,5,0,0,6,1,4.3,4.3,0.7,5.0,22,114,42,0.31,0.19,0.50,0.31,0.50,0.27,0.05,0.31,0.27,0.31,<NA>
222,Joao Goulart Silva,POR,DF,Casa Pia,24,33,32,2838,31.5,2,0,2,2,0,0,4,0,1.0,1.0,0.5,1.4,16,50,2,0.06,0.00,0.06,0.06,0.06,0.03,0.02,0.05,0.03,0.05,<NA>
247,Andre Inacio,BRA,"FW,MF",Rio Ave,22,27,20,1816,20.2,2,2,4,2,0,0,2,0,4.2,4.2,2.4,6.7,76,41,128,0.10,0.10,0.20,0.10,0.20,0.21,0.12,0.33,0.21,0.33,<NA>
252,Ivan Jaime Pajuelo,ESP,FW,Porto,23,9,5,443,4.9,2,2,4,2,0,0,1,0,1.2,1.2,0.6,1.9,8,25,37,0.41,0.41,0.81,0.41,0.81,0.25,0.13,0.38,0.25,0.38,<NA>
255,Diederrick Joel,CMR,FW,Nacional,30,14,8,860,9.6,2,0,2,2,0,1,1,0,2.3,1.5,1.1,2.6,5,16,26,0.21,0.00,0.21,0.21,0.21,0.24,0.11,0.35,0.16,0.27,<NA>
257,Luiz Lucio Reis Junior,BRA,GK,Famalicão,23,1,1,90,1.0,0,0,0,0,0,0,1,0,0.0,0.0,0.0,0.0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,<NA>
262,Kali,ANG,DF,Casa Pia,20,1,0,1,0.0,0,0,0,0,0,0,1,0,0.0,0.0,0.0,0.0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,<NA>
271,Koka,EGY,"FW,MF",Rio Ave,31,9,0,167,1.9,1,0,1,1,0,0,2,0,0.8,0.8,0.2,1.1,3,4,5,0.54,0.00,0.54,0.54,0.54,0.45,0.13,0.58,0.45,0.58,<NA>
281,Larra,ESP,"MF,DF",Casa Pia,26,32,26,2242,24.9,2,3,5,2,0,0,9,1,1.9,1.9,2.8,4.7,51,56,116,0.08,0.12,0.20,0.08,0.20,0.08,0.11,0.19,0.08,0.19,<NA>
287,Yan Lincon,BRA,FW,Moreirense,21,8,3,262,2.9,3,0,3,3,0,0,2,0,0.6,0.6,0.0,0.6,3,4,8,1.03,0.00,1.03,1.03,1.03,0.21,0.01,0.22,0.21,0.22,<NA>
289,Danny Loader,CMR,"FW,MF",Porto,23,29,11,1071,11.9,3,1,4,2,1,1,3,0,4.2,3.4,0.8,4.1,18,31,71,0.25,0.08,0.34,0.17,0.25,0.35,0.06,0.41,0.28,0.35,<NA>
299,Luismi,EQG,FW,Moreirense,23,31,13,1369,15.2,5,3,8,5,0,0,1,0,5.4,5.4,1.1,6.5,22,21,65,0.33,0.20,0.53,0.33,0.53,0.35,0.07,0.43,0.35,0.43,<NA>
300,Vitali Lystsov,RUS,DF,Boavista,29,8,5,474,5.3,1,0,1,1,0,0,2,0,0.1,0.1,0.0,0.1,1,16,3,0.19,0.00,0.19,0.19,0.19,0.02,0.00,0.02,0.02,0.02,<NA>
312,Manuel Manu,POR,MF,Benfica,23,18,9,816,9.1,1,2,3,1,0,0,3,0,0.4,0.4,0.7,1.1,1,81,15,0.11,0.22,0.33,0.11,0.33,0.04,0.08,0.12,0.04,0.12,<NA>
317,Joao Mario Lopes,POR,"DF,MF",Porto,24,27,19,1767,19.6,0,3,3,0,0,0,5,0,0.8,0.8,4.4,5.2,78,119,182,0.00,0.15,0.15,0.00,0.15,0.04,0.23,0.27,0.04,0.27,<NA>
318,Uladzislaŭ Marozaŭ,BLR,FW,Arouca,23,11,3,279,3.1,0,0,0,0,0,0,0,0,0.3,0.3,0.2,0.5,3,1,10,0.00,0.00,0.00,0.00,0.00,0.09,0.07,0.17,0.09,0.17,<NA>
325,Bernardo Martins,POR,"FW,MF",Moreirense,26,31,19,1636,18.2,4,3,7,4,0,0,7,0,2.1,2.1,2.2,4.3,23,82,69,0.22,0.17,0.39,0.22,0.39,0.12,0.12,0.23,0.12,0.23,<NA>
331,Mauro Meireles Couto,POR,DF,Sporting CP,18,1,0,4,0.0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,1,2,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,<NA>
333,Yair Mena Palacios,COL,"MF,FW",AVS Futebol,24,10,0,93,1.0,0,0,0,0,0,0,4,0,0.1,0.1,0.0,0.1,1,1,8,0.00,0.00,0.00,0.00,0.00,0.05,0.04,0.10,0.05,0.10,<NA>
341,Bruno Messi,POR,"FW,MF",Santa Clara,27,7,0,113,1.3,0,0,0,0,0,0,1,0,0.1,0.1,0.1,0.2,8,4,18,0.00,0.00,0.00,0.00,0.00,0.09,0.05,0.15,0.09,0.15,<NA>
368,Christian Neiva Afonso,POR,"DF,MF",AVS Futebol,29,26,21,1619,18.0,1,2,3,1,0,0,5,1,0.4,0.4,2.0,2.4,13,43,42,0.06,0.11,0.17,0.06,0.17,0.02,0.11,0.13,0.02,0.13,<NA>
386,Samu Omorodion,ESP,FW,Porto,20,30,23,2263,25.1,19,3,22,15,4,4,3,1,14.1,10.9,2.0,12.9,23,28,132,0.76,0.12,0.87,0.60,0.72,0.56,0.08,0.64,0.43,0.51,<NA>
403,Ze Pedro Figueiredo,POR,DF,Porto,27,20,16,1497,16.6,0,0,0,0,0,0,2,0,0.9,0.9,0.4,1.3,9,93,7,0.00,0.00,0.00,0.00,0.00,0.05,0.02,0.08,0.05,0.08,<NA>
408,Francisco Pereira,POR,MF,Estoril,22,1,0,12,0.1,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,1,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,<NA>
411,Sebastian Perez Cardona,COL,MF,Boavista,31,29,24,2024,22.5,1,0,1,1,0,0,8,2,0.6,0.6,1.5,2.1,7,112,17,0.04,0.00,0.04,0.04,0.04,0.03,0.07,0.09,0.03,0.09,<NA>
420,Alexandre Pinto,POR,DF,Arouca,26,14,9,823,9.1,0,1,1,0,0,0,4,0,0.6,0.6,0.9,1.5,9,29,53,0.00,0.11,0.11,0.00,0.11,0.07,0.10,0.17,0.07,0.17,<NA>
422,Jaime Pinto,POR,"MF,FW",Farense,26,8,1,231,2.6,0,0,0,0,0,0,1,0,0.6,0.6,0.0,0.6,9,2,8,0.00,0.00,0.00,0.00,0.00,0.23,0.00,0.23,0.23,0.23,<NA>
430,Miguel Puche Garcia,ESP,"FW,MF",Arouca,23,22,4,519,5.8,2,0,2,2,0,0,1,0,1.2,1.2,1.2,2.4,18,18,43,0.35,0.00,0.35,0.35,0.35,0.22,0.20,0.42,0.22,0.42,<NA>
438,Guilherme Ramos,POR,DF,Santa Clara,26,6,4,331,3.7,0,0,0,0,0,0,2,0,0.1,0.1,0.0,0.1,3,12,0,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.02,0.01,0.02,<NA>
439,Leonardo Realpe,ECU,DF,Famalicão,23,5,5,450,5.0,0,0,0,0,0,0,1,0,0.6,0.6,0.0,0.6,2,13,0,0.00,0.00,0.00,0.00,0.00,0.11,0.00,0.12,0.11,0.12,<NA>
441,Francisco Reis Ferreira,POR,DF,Estrela,27,18,16,1410,15.7,0,0,0,0,0,0,6,0,0.4,0.4,0.4,0.7,6,53,4,0.00,0.00,0.00,0.00,0.00,0.02,0.02,0.05,0.02,0.05,<NA>
466,Luis Carlos Rocha Rodrigues,POR,DF,Santa Clara,37,29,29,2578,28.6,0,0,0,0,0,0,10,0,0.4,0.4,0.4,0.8,5,39,3,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.03,0.01,0.03,<NA>
467,Rafael Rodrigues,POR,"DF,MF",AVS Futebol,22,21,10,1033,11.5,1,0,1,1,0,0,5,0,0.5,0.5,0.5,1.1,11,27,25,0.09,0.00,0.09,0.09,0.09,0.05,0.05,0.09,0.05,0.09,<NA>
469,Ignacio Rodriguez,URU,DF,AVS Futebol,20,16,12,1188,13.2,0,0,0,0,0,0,5,1,0.2,0.2,0.3,0.5,2,29,0,0.00,0.00,0.00,0.00,0.00,0.02,0.02,0.04,0.02,0.04,<NA>
473,Gustavo sa,POR,MF,Famalicão,19,33,32,2520,28.0,4,6,10,4,0,0,7,0,3.7,3.7,3.5,7.2,42,117,149,0.14,0.21,0.36,0.14,0.36,0.13,0.13,0.26,0.13,0.26,<NA>
476,Sala,ESP,"FW,MF",Estoril,21,12,0,169,1.9,0,0,0,0,0,0,0,0,0.5,0.5,0.3,0.9,4,6,17,0.00,0.00,0.00,0.00,0.00,0.29,0.18,0.46,0.29,0.46,<NA>
481,Aderlan Santos,BRA,DF,Rio Ave,35,28,26,2178,24.2,0,0,0,0,0,0,4,0,1.1,1.1,0.0,1.1,3,27,3,0.00,0.00,0.00,0.00,0.00,0.05,0.00,0.05,0.05,0.05,<NA>
482,Bruno Santos,POR,FW,Farense,21,3,0,57,0.6,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,2,0.00,0.00,0.00,0.00,0.00,0.00,0.04,0.04,0.00,0.04,<NA>
499,Guilherme Serrao,POR,"MF,DF",Estrela,20,11,9,748,8.3,0,0,0,0,0,0,4,1,0.0,0.0,0.4,0.4,13,17,28,0.00,0.00,0.00,0.00,0.00,0.00,0.04,0.05,0.00,0.05,<NA>
505,Gustavo da Silva,BRA,FW,Vitoria,25,21,9,871,9.7,7,0,7,7,0,0,4,0,5.0,5.0,1.3,6.3,25,18,74,0.72,0.00,0.72,0.72,0.72,0.52,0.13,0.65,0.52,0.65,<NA>
506,Joel silva,POR,"MF,DF",Boavista,21,30,27,2397,26.6,2,1,3,2,0,0,4,0,2.0,2.0,2.3,4.3,32,75,79,0.08,0.04,0.11,0.08,0.11,0.07,0.09,0.16,0.07,0.16,<NA>
508,Luis Manuel Costa Silva,POR,MF,AVS Futebol,31,8,6,464,5.2,0,0,0,0,0,0,3,0,0.6,0.6,0.1,0.7,2,13,5,0.00,0.00,0.00,0.00,0.00,0.12,0.01,0.13,0.12,0.13,<NA>
515,Sphephelo Sithole,RSA,"FW,MF",Gil Vicente FC,25,2,0,53,0.6,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1,4,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,<NA>
520,Alexandre Sola,AND,MF,Estrela,20,1,0,21,0.2,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,<NA>
526,Valentim Sousa,POR,FW,Rio Ave,19,5,0,85,0.9,0,0,0,0,0,0,0,0,0.1,0.1,0.0,0.1,2,1,7,0.00,0.00,0.00,0.00,0.00,0.12,0.00,0.12,0.12,0.12,<NA>
529,Gabriel Airton de Souza,BRA,"FW,MF",Moreirense,28,18,8,910,10.1,3,1,4,3,0,0,1,0,1.8,1.8,0.2,1.9,23,14,64,0.30,0.10,0.40,0.30,0.40,0.17,0.02,0.19,0.17,0.19,<NA>
530,Jerry St. Juste,NED,DF,Sporting CP,27,14,5,581,6.5,0,0,0,0,0,0,3,0,0.3,0.3,0.0,0.3,5,35,2,0.00,0.00,0.00,0.00,0.00,0.05,0.00,0.05,0.05,0.05,<NA>
548,Anatolii Trubin,UKR,GK,Benfica,22,32,32,2880,32.0,0,0,0,0,0,0,1,0,0.0,0.0,0.0,0.0,0,1,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,<NA>
563,Gabriel Vieira,BRA,FW,Santa Clara,22,33,32,2787,31.0,6,3,9,5,1,1,2,0,8.8,8.0,3.2,11.2,54,45,165,0.19,0.10,0.29,0.16,0.26,0.28,0.10,0.39,0.26,0.36,<NA>
570,Marious Vrousai,GRE,"DF,MF",Rio Ave,26,31,28,2547,28.3,1,3,4,1,0,0,5,0,2.4,2.4,2.1,4.4,47,114,96,0.04,0.11,0.14,0.04,0.14,0.08,0.07,0.16,0.08,0.16,<NA>

In [387]:
values[values['Player'].str.contains('Edney')]

    Player  Value        Squad
356  Edney    0.3  Santa Clara

In [388]:
stats.at[40, 'Value'] = 0.3

In [385]:
stats.at[570, 'Player']

'Marious Vrousai'

In [389]:
stats.to_csv('csv/stats/PO1_players_24-25.csv', index=False)

In [21]:
leagues = ['BE1', 'BRA1', 'GB1', 'ES1', 'FR1', 'IT1', 'L1', 'NL1', 'PO1']
for league in leagues:
    df = pd.read_csv(f'csv/values/{league}_players_values_24-25.csv')
    for i in range(len(df)):
        while df.at[i, 'Player'][-1]==' ':
            df.at[i, 'Player'] = df.at[i, 'Player'][:-1]
    print(df.at[0, 'Player'])
    df.to_csv(f'csv/values/{league}_players_values_24-25.csv', index=False)

Simon Mignolet
Carlos Miguel
Ederson
Thibaut Courtois
Gianluigi Donnarumma
Josep Martínez
Jonas Urbig
Timon Wellenreuther
Rui Silva

In [81]:
stats[stats.duplicated(subset=['Player', 'Nation', 'Age'], keep=False)]

Empty DataFrame
Columns: [Player, Nation, Pos, Squad, Age, MP, Starts, Min, 90s, Gls, Ast, G+A, G-PK, PK, PKatt, CrdY, CrdR, xG, npxG, xAG, npxG+xAG, PrgC, PrgP, PrgR, Gls.1, Ast.1, G+A.1, G-PK.1, G+A-PK, xG.1, xAG.1, xG+xAG, npxG.1, npxG+xAG.1, Value]
Index: []

In [366]:
stats[(stats['Squad'].str.contains('Rio'))&(stats['Player'].str.contains(''))]

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1,Value
211,Vitor Gomes,POR,MF,Rio Ave,36.0,6.0,1.0,93.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6,0.6,0.0,7.0,1.0,0.00,0.97,0.97,0.00,0.97,0.00,0.62,0.62,0.00,0.62,0.1
526,Valentim Sousa,POR,FW,Rio Ave,19.0,5.0,0.0,85.0,0.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.1,0.0,0.1,2.0,1.0,7.0,0.00,0.00,0.00,0.00,0.00,0.12,0.00,0.12,0.12,0.12,<NA>
570,Marious Vrousai,GRE,"DF,MF",Rio Ave,26.0,31.0,28.0,2547.0,28.3,1.0,3.0,4.0,1.0,0.0,0.0,5.0,0.0,2.4,2.4,2.1,4.4,47.0,114.0,96.0,0.04,0.11,0.14,0.04,0.14,0.08,0.07,0.16,0.08,0.16,<NA>

In [369]:
values[(values['Squad'].str.contains('Rio'))&(values['Player'].str.contains('Tim'))]

    Player  Value    Squad
296    Tim   0.15  Rio Ave

In [386]:
stats[stats['Value'].isna()]

,Player,Nation,Pos,Squad,Age,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1,Value
40,Ney Bahia,BRA,MF,Santa Clara,20.0,2.0,0.0,62.0,0.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.1,0.0,0.1,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.18,0.0,0.18,0.18,0.18,<NA>

In [17]:
def unite_gk_duplicates(gk_stats):
    stats = copy(gk_stats)
    pairs_to_unite = []
    for i in stats[stats.duplicated(subset=['Player', 'Age', 'Nation'], keep='last')].index:
        pairs_to_unite.append((i, i+1))
    duplicated_players = stats[stats.duplicated(subset=['Player', 'Age', 'Nation'], keep=False)]
    stats = stats.drop_duplicates(subset=['Player', 'Age', 'Nation'], keep='last')
    for pair in pairs_to_unite:
        for col in ['MP', 'Starts', 'Min', '90s', 'GA', 'SoTA', 'Saves', 'W', 'D', 'L', 'CS', 'PKatt', 'PKA', 'PKsv', 'PKm',]:
            stats.at[pair[1], col] = duplicated_players.at[pair[0], col] + duplicated_players.at[pair[1], col]
        stats.at[pair[1],'GA90'] = stats.at[pair[1], 'GA'] / stats.at[pair[1], '90s']
        stats.at[pair[1], 'Save%'] = stats.at[pair[1], 'Saves'] / stats.at[pair[1], 'SoTA'] * 100
        stats.at[pair[1], 'CS%'] = stats.at[pair[1], 'CS'] / stats.at[pair[1], 'Starts']
        if stats.at[pair[1], 'PKatt'] != 0:
            stats.at[pair[1], 'Save%.1'] = stats.at[pair[1], 'PKsv'] / (stats.at[pair[1], 'PKatt'] - stats.at[pair[1], 'PKm']) * 100
        for col in stats.columns[5:]:
            stats[col] = stats[col].round(2)
    return stats

In [31]:
for champ_id in champ_ids:
    # stats = pd.read_csv(f'csv/stats/{champ_id}_players_24-25.csv')
    gks = pd.read_csv(f'csv/stats/{champ_id}_gk_24-25.csv')
    # gks = unite_gk_duplicates(gks)
    # for letter in changes:
    #     gks['Player'] = gks['Player'].str.replace(letter, changes[letter])
    # gks = gks.merge(stats[['Player', 'Nation', 'Pos', 'Age', 'Value']], on=['Player', 'Nation', 'Pos', 'Age'], how='inner')
    gks = gks.rename(columns={'Save%.1':'PKsv%'})
    gks['PKsv%'] = gks['PKsv%'].fillna(0)
    gks.to_csv(f'csv/stats/{champ_id}_gk_24-25.csv', index=False)

In [29]:
def unite_misc_duplicates(misc_stats):
    stats = copy(misc_stats)
    pairs_to_unite = []
    for i in stats[stats.duplicated(subset=['Player', 'Age', 'Nation'], keep='last')].index:
        pairs_to_unite.append((i, i+1))
    duplicated_players = stats[stats.duplicated(subset=['Player', 'Age', 'Nation'], keep=False)]
    stats = stats.drop_duplicates(subset=['Player', 'Age', 'Nation'], keep='last')
    for pair in pairs_to_unite:
        for col in ['90s', 'CrdY', 'CrdR', '2CrdY', 'Fls', 'Fld', 'Off', 'Crs', 'Int', 'TklW', 'OG']:
            stats.at[pair[1], col] = duplicated_players.at[pair[0], col] + duplicated_players.at[pair[1], col]
    return stats

In [56]:
def unite_shooting_duplicates(shooting_stats):
    stats = copy(shooting_stats)
    pairs_to_unite = []
    for i in stats[stats.duplicated(subset=['Player', 'Age', 'Nation'], keep='last')].index:
        pairs_to_unite.append((i, i+1))
    duplicated_players = stats[stats.duplicated(subset=['Player', 'Age', 'Nation'], keep=False)]
    stats = stats.drop_duplicates(subset=['Player', 'Age', 'Nation'], keep='last')
    for pair in pairs_to_unite:
        for col in ['90s', 'Gls', 'Sh', 'SoT', 'PK', 'PKatt']:
            stats.at[pair[1], col] = duplicated_players.at[pair[0], col] + duplicated_players.at[pair[1], col]
        if stats.at[pair[1], 'Sh'] > 0:
            stats.at[pair[1], 'SoT%'] = stats.at[pair[1], 'SoT'] / stats.at[pair[1], 'Sh'] * 100
            stats.at[pair[1], 'G/Sh'] = stats.at[pair[1], 'Gls'] / stats.at[pair[1], 'Sh']
        if stats.at[pair[1], 'SoT'] > 0:
            stats.at[pair[1], 'G/SoT'] = stats.at[pair[1], 'Gls'] / stats.at[pair[1], 'SoT']
        stats.at[pair[1], 'Sh/90'] = stats.at[pair[1], 'Sh'] / stats.at[pair[1], '90s']
        stats.at[pair[1], 'SoT/90'] = stats.at[pair[1], 'SoT'] / stats.at[pair[1], '90s']

    stats = stats.fillna(0)
    for col in stats.columns[9:14]:
        stats[col] = stats[col].round(2)
    return stats

In [30]:
for champ_id in champ_ids:
    if champ_id == 'BRA1':
        continue
    stats = pd.read_csv(f'csv/stats/{champ_id}_players_24-25.csv')
    misc = pd.read_csv(f'csv/stats/{champ_id}_misc_24-25.csv')
    misc = unite_misc_duplicates(misc)
    #misc.to_csv(f'csv/stats/{champ_id}_misc_24-25.csv', index=False)
    res = stats.merge(misc[['2CrdY', 'Fls', 'Fld', 'Off', 'Crs', 'Int', 'TklW', 'OG']], right_index=True, left_index=True)
    res.to_csv(f'csv/stats/{champ_id}_players_24-25.csv', index=False)

In [59]:
for champ_id in champ_ids:
    if champ_id == 'BRA1':
        continue
    stats = pd.read_csv(f'csv/stats/{champ_id}_players_24-25.csv')
    shooting = pd.read_csv(f'csv/stats/{champ_id}_shooting_24-25.csv')
    shooting = unite_shooting_duplicates(shooting)
    shooting.to_csv(f'csv/stats/{champ_id}_shooting_24-25.csv', index=False)
    shooting = pd.read_csv(f'csv/stats/{champ_id}_shooting_24-25.csv')
    res = stats.merge(shooting[['Sh', 'SoT', 'SoT%', 'Sh/90', 'SoT/90', 'G/Sh', 'G/SoT']], how='left', left_index=True, right_index=True)
    res.to_csv(f'csv/stats/{champ_id}_players_24-25.csv', index=False)