In [1]:
import pandas as pd
import xgboost as xgb
from sklearn.metrics import mean_absolute_error as mae, mean_absolute_percentage_error as mape, root_mean_squared_error as rmse, r2_score

In [3]:
X_train = pd.read_csv('csv/final_datasets/for_xgb/train_test_val/predictors_train.csv')
X_test = pd.read_csv('csv/final_datasets/for_xgb/train_test_val/predictors_test.csv')
X_val = pd.read_csv('csv/final_datasets/for_xgb/train_test_val/predictors_val.csv')
for col in ('Nation', 'Pos', 'Squad', 'league'):
    X_train[col] = X_train[col].astype('category')
    X_test[col] = X_test[col].astype('category')
    X_val[col] = X_val[col].astype('category')

players_train = pd.read_csv('csv/final_datasets/for_xgb/train_test_val/train_players_names.csv')
players_test = pd.read_csv('csv/final_datasets/for_xgb/train_test_val/test_players_names.csv')
players_val = pd.read_csv('csv/final_datasets/for_xgb/train_test_val/val_players_names.csv')

y_train = pd.read_csv('csv/final_datasets/for_xgb/train_test_val/target_train.csv')
y_test = pd.read_csv('csv/final_datasets/for_xgb/train_test_val/target_test.csv')
y_val = pd.read_csv('csv/final_datasets/for_xgb/train_test_val/target_val.csv')

In [2]:
params = {
    'max_depth': 3,
    'learning_rate': 0.013815876417793225,
    'subsample': 0.8564389753793318,
    'colsample_bytree': 0.6720743179899686,
    'reg_lambda': 3.3900178420389695,
    'reg_alpha': 2.2909993262533157,
    'n_estimators': 2000,
    'objective': 'reg:gamma',
    'random_state': 42,
    'early_stopping_rounds': 15,
    'eval_metric': 'mape',
    'enable_categorical': True
}

In [4]:
xgb_regressor = xgb.XGBRegressor(**params)
xgb_regressor.fit(
    X_train, y_train,
    eval_set = [(X_val, y_val)],
    verbose = True
)

[0]	validation_0-mape:6.93593
[1]	validation_0-mape:6.60893
[2]	validation_0-mape:6.30736
[3]	validation_0-mape:6.01426
[4]	validation_0-mape:5.70797
[5]	validation_0-mape:5.44209
[6]	validation_0-mape:5.20055
[7]	validation_0-mape:4.98334
[8]	validation_0-mape:4.82466
[9]	validation_0-mape:4.68502
[10]	validation_0-mape:4.55643
[11]	validation_0-mape:4.49565
[12]	validation_0-mape:4.41198
[13]	validation_0-mape:4.26983
[14]	validation_0-mape:4.11905
[15]	validation_0-mape:3.97839
[16]	validation_0-mape:3.84677
[17]	validation_0-mape:3.73782
[18]	validation_0-mape:3.59890
[19]	validation_0-mape:3.48890
[20]	validation_0-mape:3.39211
[21]	validation_0-mape:3.30571
[22]	validation_0-mape:3.20178
[23]	validation_0-mape:3.09235
[24]	validation_0-mape:2.99567
[25]	validation_0-mape:2.90254
[26]	validation_0-mape:2.84438
[27]	validation_0-mape:2.75545
[28]	validation_0-mape:2.67984
[29]	validation_0-mape:2.60326
[30]	validation_0-mape:2.53941
[31]	validation_0-mape:2.49595
[32]	validation_0-mape:2.43235
[33]	validation_0-mape:2.37406
[34]	validation_0-mape:2.32428
[35]	validation_0-mape:2.27244
[36]	validation_0-mape:2.23197
[37]	validation_0-mape:2.19820
[38]	validation_0-mape:2.15182
[39]	validation_0-mape:2.10944
[40]	validation_0-mape:2.07194
[41]	validation_0-mape:2.03957
[42]	validation_0-mape:2.01465
[43]	validation_0-mape:1.97840
[44]	validation_0-mape:1.94385
[45]	validation_0-mape:1.91643
[46]	validation_0-mape:1.89735
[47]	validation_0-mape:1.86927
[48]	validation_0-mape:1.84158
[49]	validation_0-mape:1.81199
[50]	validation_0-mape:1.79560
[51]	validation_0-mape:1.78305
[52]	validation_0-mape:1.75531
[53]	validation_0-mape:1.73502
[54]	validation_0-mape:1.71664
[55]	validation_0-mape:1.69071
[56]	validation_0-mape:1.66553
[57]	validation_0-mape:1.64703
[58]	validation_0-mape:1.62908
[59]	validation_0-mape:1.60785
[60]	validation_0-mape:1.59686
[61]	validation_0-mape:1.58033
[62]	validation_0-mape:1.56715
[63]	validation_0-mape:1.54406
[64]	validation_0-mape:1.52557
[65]	validation_0-mape:1.51270
[66]	validation_0-mape:1.49303
[67]	validation_0-mape:1.47701
[68]	validation_0-mape:1.46206
[69]	validation_0-mape:1.45043
[70]	validation_0-mape:1.43457
[71]	validation_0-mape:1.42008
[72]	validation_0-mape:1.40500
[73]	validation_0-mape:1.39563
[74]	validation_0-mape:1.38067
[75]	validation_0-mape:1.36664
[76]	validation_0-mape:1.35298
[77]	validation_0-mape:1.34036
[78]	validation_0-mape:1.32490
[79]	validation_0-mape:1.31274
[80]	validation_0-mape:1.30520
[81]	validation_0-mape:1.29412
[82]	validation_0-mape:1.28045
[83]	validation_0-mape:1.26910
[84]	validation_0-mape:1.25607
[85]	validation_0-mape:1.24513
[86]	validation_0-mape:1.23321
[87]	validation_0-mape:1.22219
[88]	validation_0-mape:1.21216
[89]	validation_0-mape:1.20221
[90]	validation_0-mape:1.19592
[91]	validation_0-mape:1.18673
[92]	validation_0-mape:1.17812
[93]	validation_0-mape:1.16950
[94]	validation_0-mape:1.15980
[95]	validation_0-mape:1.14991
[96]	validation_0-mape:1.14183
[97]	validation_0-mape:1.13410
[98]	validation_0-mape:1.12488
[99]	validation_0-mape:1.11779
[100]	validation_0-mape:1.11246
[101]	validation_0-mape:1.10616
[102]	validation_0-mape:1.09848
[103]	validation_0-mape:1.09359
[104]	validation_0-mape:1.08686
[105]	validation_0-mape:1.08128
[106]	validation_0-mape:1.07484
[107]	validation_0-mape:1.06757
[108]	validation_0-mape:1.06110
[109]	validation_0-mape:1.05513
[110]	validation_0-mape:1.04878
[111]	validation_0-mape:1.04254
[112]	validation_0-mape:1.03562
[113]	validation_0-mape:1.03065
[114]	validation_0-mape:1.02577
[115]	validation_0-mape:1.01896
[116]	validation_0-mape:1.01425
[117]	validation_0-mape:1.01023
[118]	validation_0-mape:1.00476
[119]	validation_0-mape:0.99990
[120]	validation_0-mape:0.99395
[121]	validation_0-mape:0.98833
[122]	validation_0-mape:0.98274
[123]	validation_0-mape:0.97847
[124]	validation_0-mape:0.97414
[125]	validation_0-mape:0.97079
[126]	validation_0-mape:0.96640
[127]	validation_0-mape:0.96182
[128]	validation_0-mape:0.95812
[129]	validation_0-mape:0.95529
[130]	validation_0-mape:0.95119
[131]	validation_0-mape:0.94762
[132]	validation_0-mape:0.94348
[133]	validation_0-mape:0.93940
[134]	validation_0-mape:0.93674
[135]	validation_0-mape:0.93415
[136]	validation_0-mape:0.93113
[137]	validation_0-mape:0.92744
[138]	validation_0-mape:0.92377
[139]	validation_0-mape:0.92061
[140]	validation_0-mape:0.91748
[141]	validation_0-mape:0.91384
[142]	validation_0-mape:0.91058
[143]	validation_0-mape:0.90693
[144]	validation_0-mape:0.90358
[145]	validation_0-mape:0.90009
[146]	validation_0-mape:0.89665
[147]	validation_0-mape:0.89259
[148]	validation_0-mape:0.88900
[149]	validation_0-mape:0.88585
[150]	validation_0-mape:0.88286
[151]	validation_0-mape:0.88010
[152]	validation_0-mape:0.87640
[153]	validation_0-mape:0.87343
[154]	validation_0-mape:0.87079
[155]	validation_0-mape:0.86826
[156]	validation_0-mape:0.86566
[157]	validation_0-mape:0.86317
[158]	validation_0-mape:0.86044
[159]	validation_0-mape:0.85778
[160]	validation_0-mape:0.85469
[161]	validation_0-mape:0.85159
[162]	validation_0-mape:0.84893
[163]	validation_0-mape:0.84618
[164]	validation_0-mape:0.84299
[165]	validation_0-mape:0.84054
[166]	validation_0-mape:0.83839
[167]	validation_0-mape:0.83567
[168]	validation_0-mape:0.83325
[169]	validation_0-mape:0.83088
[170]	validation_0-mape:0.82880
[171]	validation_0-mape:0.82682
[172]	validation_0-mape:0.82400
[173]	validation_0-mape:0.82156
[174]	validation_0-mape:0.81883
[175]	validation_0-mape:0.81718
[176]	validation_0-mape:0.81552
[177]	validation_0-mape:0.81393
[178]	validation_0-mape:0.81154
[179]	validation_0-mape:0.80914
[180]	validation_0-mape:0.80679
[181]	validation_0-mape:0.80493
[182]	validation_0-mape:0.80333
[183]	validation_0-mape:0.80126
[184]	validation_0-mape:0.79956
[185]	validation_0-mape:0.79791
[186]	validation_0-mape:0.79619
[187]	validation_0-mape:0.79434
[188]	validation_0-mape:0.79264
[189]	validation_0-mape:0.79082
[190]	validation_0-mape:0.78953
[191]	validation_0-mape:0.78835
[192]	validation_0-mape:0.78632
[193]	validation_0-mape:0.78466
[194]	validation_0-mape:0.78295
[195]	validation_0-mape:0.78103
[196]	validation_0-mape:0.77912
[197]	validation_0-mape:0.77750
[198]	validation_0-mape:0.77601
[199]	validation_0-mape:0.77425
[200]	validation_0-mape:0.77291
[201]	validation_0-mape:0.77190
[202]	validation_0-mape:0.77061
[203]	validation_0-mape:0.76880
[204]	validation_0-mape:0.76788
[205]	validation_0-mape:0.76635
[206]	validation_0-mape:0.76493
[207]	validation_0-mape:0.76378
[208]	validation_0-mape:0.76263
[209]	validation_0-mape:0.76116
[210]	validation_0-mape:0.75979
[211]	validation_0-mape:0.75853
[212]	validation_0-mape:0.75730
[213]	validation_0-mape:0.75627
[214]	validation_0-mape:0.75513
[215]	validation_0-mape:0.75427
[216]	validation_0-mape:0.75300
[217]	validation_0-mape:0.75195
[218]	validation_0-mape:0.75095
[219]	validation_0-mape:0.75003
[220]	validation_0-mape:0.74931
[221]	validation_0-mape:0.74794
[222]	validation_0-mape:0.74667
[223]	validation_0-mape:0.74567
[224]	validation_0-mape:0.74497
[225]	validation_0-mape:0.74400
[226]	validation_0-mape:0.74317
[227]	validation_0-mape:0.74230
[228]	validation_0-mape:0.74171
[229]	validation_0-mape:0.74076
[230]	validation_0-mape:0.73998
[231]	validation_0-mape:0.73884
[232]	validation_0-mape:0.73800
[233]	validation_0-mape:0.73692
[234]	validation_0-mape:0.73597
[235]	validation_0-mape:0.73523
[236]	validation_0-mape:0.73439
[237]	validation_0-mape:0.73386
[238]	validation_0-mape:0.73264
[239]	validation_0-mape:0.73190
[240]	validation_0-mape:0.73122
[241]	validation_0-mape:0.73042
[242]	validation_0-mape:0.72954
[243]	validation_0-mape:0.72877
[244]	validation_0-mape:0.72795
[245]	validation_0-mape:0.72744
[246]	validation_0-mape:0.72665
[247]	validation_0-mape:0.72571
[248]	validation_0-mape:0.72471
[249]	validation_0-mape:0.72383
[250]	validation_0-mape:0.72264
[251]	validation_0-mape:0.72209
[252]	validation_0-mape:0.72088
[253]	validation_0-mape:0.72021
[254]	validation_0-mape:0.71946
[255]	validation_0-mape:0.71855
[256]	validation_0-mape:0.71777
[257]	validation_0-mape:0.71709
[258]	validation_0-mape:0.71642
[259]	validation_0-mape:0.71565
[260]	validation_0-mape:0.71471
[261]	validation_0-mape:0.71391
[262]	validation_0-mape:0.71336
[263]	validation_0-mape:0.71280
[264]	validation_0-mape:0.71201
[265]	validation_0-mape:0.71137
[266]	validation_0-mape:0.71053
[267]	validation_0-mape:0.70975
[268]	validation_0-mape:0.70892
[269]	validation_0-mape:0.70890
[270]	validation_0-mape:0.70831
[271]	validation_0-mape:0.70790
[272]	validation_0-mape:0.70735
[273]	validation_0-mape:0.70660
[274]	validation_0-mape:0.70581
[275]	validation_0-mape:0.70495
[276]	validation_0-mape:0.70405
[277]	validation_0-mape:0.70323
[278]	validation_0-mape:0.70263
[279]	validation_0-mape:0.70165
[280]	validation_0-mape:0.70107
[281]	validation_0-mape:0.70021
[282]	validation_0-mape:0.69972
[283]	validation_0-mape:0.69885
[284]	validation_0-mape:0.69887
[285]	validation_0-mape:0.69810
[286]	validation_0-mape:0.69773
[287]	validation_0-mape:0.69719
[288]	validation_0-mape:0.69637
[289]	validation_0-mape:0.69565
[290]	validation_0-mape:0.69505
[291]	validation_0-mape:0.69461
[292]	validation_0-mape:0.69404
[293]	validation_0-mape:0.69358
[294]	validation_0-mape:0.69330
[295]	validation_0-mape:0.69278
[296]	validation_0-mape:0.69201
[297]	validation_0-mape:0.69182
[298]	validation_0-mape:0.69130
[299]	validation_0-mape:0.69067
[300]	validation_0-mape:0.69031
[301]	validation_0-mape:0.68963
[302]	validation_0-mape:0.68914
[303]	validation_0-mape:0.68879
[304]	validation_0-mape:0.68836
[305]	validation_0-mape:0.68790
[306]	validation_0-mape:0.68738
[307]	validation_0-mape:0.68701
[308]	validation_0-mape:0.68662
[309]	validation_0-mape:0.68611
[310]	validation_0-mape:0.68572
[311]	validation_0-mape:0.68508
[312]	validation_0-mape:0.68462
[313]	validation_0-mape:0.68422
[314]	validation_0-mape:0.68392
[315]	validation_0-mape:0.68358
[316]	validation_0-mape:0.68298
[317]	validation_0-mape:0.68288
[318]	validation_0-mape:0.68251
[319]	validation_0-mape:0.68186
[320]	validation_0-mape:0.68149
[321]	validation_0-mape:0.68098
[322]	validation_0-mape:0.68056
[323]	validation_0-mape:0.68033
[324]	validation_0-mape:0.67979
[325]	validation_0-mape:0.67965
[326]	validation_0-mape:0.67930
[327]	validation_0-mape:0.67893
[328]	validation_0-mape:0.67866
[329]	validation_0-mape:0.67838
[330]	validation_0-mape:0.67789
[331]	validation_0-mape:0.67759
[332]	validation_0-mape:0.67725
[333]	validation_0-mape:0.67669
[334]	validation_0-mape:0.67634
[335]	validation_0-mape:0.67611
[336]	validation_0-mape:0.67600
[337]	validation_0-mape:0.67585
[338]	validation_0-mape:0.67550
[339]	validation_0-mape:0.67500
[340]	validation_0-mape:0.67462
[341]	validation_0-mape:0.67413
[342]	validation_0-mape:0.67379
[343]	validation_0-mape:0.67326
[344]	validation_0-mape:0.67283
[345]	validation_0-mape:0.67213
[346]	validation_0-mape:0.67167
[347]	validation_0-mape:0.67101
[348]	validation_0-mape:0.67091
[349]	validation_0-mape:0.67065
[350]	validation_0-mape:0.67019
[351]	validation_0-mape:0.66974
[352]	validation_0-mape:0.66961
[353]	validation_0-mape:0.66932
[354]	validation_0-mape:0.66887
[355]	validation_0-mape:0.66849
[356]	validation_0-mape:0.66826
[357]	validation_0-mape:0.66800
[358]	validation_0-mape:0.66743
[359]	validation_0-mape:0.66696
[360]	validation_0-mape:0.66659
[361]	validation_0-mape:0.66637
[362]	validation_0-mape:0.66582
[363]	validation_0-mape:0.66554
[364]	validation_0-mape:0.66507
[365]	validation_0-mape:0.66487
[366]	validation_0-mape:0.66457
[367]	validation_0-mape:0.66437
[368]	validation_0-mape:0.66403
[369]	validation_0-mape:0.66399
[370]	validation_0-mape:0.66393
[371]	validation_0-mape:0.66349
[372]	validation_0-mape:0.66328
[373]	validation_0-mape:0.66276
[374]	validation_0-mape:0.66236
[375]	validation_0-mape:0.66190
[376]	validation_0-mape:0.66134
[377]	validation_0-mape:0.66075
[378]	validation_0-mape:0.66047
[379]	validation_0-mape:0.66032
[380]	validation_0-mape:0.65986
[381]	validation_0-mape:0.65954
[382]	validation_0-mape:0.65926
[383]	validation_0-mape:0.65911
[384]	validation_0-mape:0.65905
[385]	validation_0-mape:0.65902
[386]	validation_0-mape:0.65866
[387]	validation_0-mape:0.65833
[388]	validation_0-mape:0.65800
[389]	validation_0-mape:0.65758
[390]	validation_0-mape:0.65728
[391]	validation_0-mape:0.65697
[392]	validation_0-mape:0.65685
[393]	validation_0-mape:0.65674
[394]	validation_0-mape:0.65642
[395]	validation_0-mape:0.65609
[396]	validation_0-mape:0.65592
[397]	validation_0-mape:0.65546
[398]	validation_0-mape:0.65521
[399]	validation_0-mape:0.65467
[400]	validation_0-mape:0.65454
[401]	validation_0-mape:0.65424
[402]	validation_0-mape:0.65380
[403]	validation_0-mape:0.65353
[404]	validation_0-mape:0.65322
[405]	validation_0-mape:0.65314
[406]	validation_0-mape:0.65303
[407]	validation_0-mape:0.65272
[408]	validation_0-mape:0.65233
[409]	validation_0-mape:0.65203
[410]	validation_0-mape:0.65172
[411]	validation_0-mape:0.65120
[412]	validation_0-mape:0.65122
[413]	validation_0-mape:0.65094
[414]	validation_0-mape:0.65082
[415]	validation_0-mape:0.65052
[416]	validation_0-mape:0.65028
[417]	validation_0-mape:0.64993
[418]	validation_0-mape:0.64966
[419]	validation_0-mape:0.64900
[420]	validation_0-mape:0.64884
[421]	validation_0-mape:0.64847
[422]	validation_0-mape:0.64820
[423]	validation_0-mape:0.64806
[424]	validation_0-mape:0.64778
[425]	validation_0-mape:0.64778
[426]	validation_0-mape:0.64762
[427]	validation_0-mape:0.64755
[428]	validation_0-mape:0.64731
[429]	validation_0-mape:0.64701
[430]	validation_0-mape:0.64677
[431]	validation_0-mape:0.64666
[432]	validation_0-mape:0.64636
[433]	validation_0-mape:0.64627
[434]	validation_0-mape:0.64580
[435]	validation_0-mape:0.64571
[436]	validation_0-mape:0.64535
[437]	validation_0-mape:0.64512
[438]	validation_0-mape:0.64487
[439]	validation_0-mape:0.64482
[440]	validation_0-mape:0.64483
[441]	validation_0-mape:0.64474
[442]	validation_0-mape:0.64444
[443]	validation_0-mape:0.64422
[444]	validation_0-mape:0.64399
[445]	validation_0-mape:0.64378
[446]	validation_0-mape:0.64355
[447]	validation_0-mape:0.64319
[448]	validation_0-mape:0.64303
[449]	validation_0-mape:0.64282
[450]	validation_0-mape:0.64245
[451]	validation_0-mape:0.64234
[452]	validation_0-mape:0.64171
[453]	validation_0-mape:0.64136
[454]	validation_0-mape:0.64122
[455]	validation_0-mape:0.64104
[456]	validation_0-mape:0.64111
[457]	validation_0-mape:0.64075
[458]	validation_0-mape:0.64063
[459]	validation_0-mape:0.64030
[460]	validation_0-mape:0.63975
[461]	validation_0-mape:0.63949
[462]	validation_0-mape:0.63906
[463]	validation_0-mape:0.63909
[464]	validation_0-mape:0.63889
[465]	validation_0-mape:0.63877
[466]	validation_0-mape:0.63835
[467]	validation_0-mape:0.63815
[468]	validation_0-mape:0.63786
[469]	validation_0-mape:0.63768
[470]	validation_0-mape:0.63741
[471]	validation_0-mape:0.63711
[472]	validation_0-mape:0.63685
[473]	validation_0-mape:0.63683
[474]	validation_0-mape:0.63671
[475]	validation_0-mape:0.63654
[476]	validation_0-mape:0.63633
[477]	validation_0-mape:0.63621
[478]	validation_0-mape:0.63610
[479]	validation_0-mape:0.63571
[480]	validation_0-mape:0.63561
[481]	validation_0-mape:0.63547
[482]	validation_0-mape:0.63522
[483]	validation_0-mape:0.63506
[484]	validation_0-mape:0.63475
[485]	validation_0-mape:0.63453
[486]	validation_0-mape:0.63431
[487]	validation_0-mape:0.63396
[488]	validation_0-mape:0.63364
[489]	validation_0-mape:0.63334
[490]	validation_0-mape:0.63302
[491]	validation_0-mape:0.63274
[492]	validation_0-mape:0.63223
[493]	validation_0-mape:0.63188
[494]	validation_0-mape:0.63166
[495]	validation_0-mape:0.63141
[496]	validation_0-mape:0.63119
[497]	validation_0-mape:0.63118
[498]	validation_0-mape:0.63092
[499]	validation_0-mape:0.63069
[500]	validation_0-mape:0.63048
[501]	validation_0-mape:0.63035
[502]	validation_0-mape:0.63013
[503]	validation_0-mape:0.63010
[504]	validation_0-mape:0.62986
[505]	validation_0-mape:0.62960
[506]	validation_0-mape:0.62944
[507]	validation_0-mape:0.62934
[508]	validation_0-mape:0.62904
[509]	validation_0-mape:0.62877
[510]	validation_0-mape:0.62871
[511]	validation_0-mape:0.62827
[512]	validation_0-mape:0.62821
[513]	validation_0-mape:0.62817
[514]	validation_0-mape:0.62792
[515]	validation_0-mape:0.62773
[516]	validation_0-mape:0.62748
[517]	validation_0-mape:0.62741
[518]	validation_0-mape:0.62727
[519]	validation_0-mape:0.62730
[520]	validation_0-mape:0.62726
[521]	validation_0-mape:0.62708
[522]	validation_0-mape:0.62695
[523]	validation_0-mape:0.62689
[524]	validation_0-mape:0.62663
[525]	validation_0-mape:0.62643
[526]	validation_0-mape:0.62631
[527]	validation_0-mape:0.62620
[528]	validation_0-mape:0.62609
[529]	validation_0-mape:0.62590
[530]	validation_0-mape:0.62573
[531]	validation_0-mape:0.62559
[532]	validation_0-mape:0.62554
[533]	validation_0-mape:0.62544
[534]	validation_0-mape:0.62508
[535]	validation_0-mape:0.62492
[536]	validation_0-mape:0.62499
[537]	validation_0-mape:0.62478
[538]	validation_0-mape:0.62456
[539]	validation_0-mape:0.62438
[540]	validation_0-mape:0.62434
[541]	validation_0-mape:0.62430
[542]	validation_0-mape:0.62393
[543]	validation_0-mape:0.62382
[544]	validation_0-mape:0.62359
[545]	validation_0-mape:0.62348
[546]	validation_0-mape:0.62340
[547]	validation_0-mape:0.62321
[548]	validation_0-mape:0.62317
[549]	validation_0-mape:0.62323
[550]	validation_0-mape:0.62311
[551]	validation_0-mape:0.62296
[552]	validation_0-mape:0.62277
[553]	validation_0-mape:0.62249
[554]	validation_0-mape:0.62233
[555]	validation_0-mape:0.62222
[556]	validation_0-mape:0.62200
[557]	validation_0-mape:0.62183
[558]	validation_0-mape:0.62182
[559]	validation_0-mape:0.62169
[560]	validation_0-mape:0.62167
[561]	validation_0-mape:0.62140
[562]	validation_0-mape:0.62119
[563]	validation_0-mape:0.62113
[564]	validation_0-mape:0.62103
[565]	validation_0-mape:0.62082
[566]	validation_0-mape:0.62060
[567]	validation_0-mape:0.62039
[568]	validation_0-mape:0.62029
[569]	validation_0-mape:0.62019
[570]	validation_0-mape:0.62004
[571]	validation_0-mape:0.61998
[572]	validation_0-mape:0.61993
[573]	validation_0-mape:0.61967
[574]	validation_0-mape:0.61945
[575]	validation_0-mape:0.61946
[576]	validation_0-mape:0.61931
[577]	validation_0-mape:0.61913
[578]	validation_0-mape:0.61893
[579]	validation_0-mape:0.61872
[580]	validation_0-mape:0.61873
[581]	validation_0-mape:0.61862
[582]	validation_0-mape:0.61840
[583]	validation_0-mape:0.61839
[584]	validation_0-mape:0.61832
[585]	validation_0-mape:0.61823
[586]	validation_0-mape:0.61811
[587]	validation_0-mape:0.61789
[588]	validation_0-mape:0.61761
[589]	validation_0-mape:0.61748
[590]	validation_0-mape:0.61726
[591]	validation_0-mape:0.61736
[592]	validation_0-mape:0.61737
[593]	validation_0-mape:0.61718
[594]	validation_0-mape:0.61704
[595]	validation_0-mape:0.61705
[596]	validation_0-mape:0.61695
[597]	validation_0-mape:0.61672
[598]	validation_0-mape:0.61654
[599]	validation_0-mape:0.61644
[600]	validation_0-mape:0.61638
[601]	validation_0-mape:0.61632
[602]	validation_0-mape:0.61623
[603]	validation_0-mape:0.61610
[604]	validation_0-mape:0.61585
[605]	validation_0-mape:0.61587
[606]	validation_0-mape:0.61588
[607]	validation_0-mape:0.61561
[608]	validation_0-mape:0.61549
[609]	validation_0-mape:0.61537
[610]	validation_0-mape:0.61536
[611]	validation_0-mape:0.61520
[612]	validation_0-mape:0.61496
[613]	validation_0-mape:0.61487
[614]	validation_0-mape:0.61462
[615]	validation_0-mape:0.61447
[616]	validation_0-mape:0.61453
[617]	validation_0-mape:0.61420
[618]	validation_0-mape:0.61418
[619]	validation_0-mape:0.61420
[620]	validation_0-mape:0.61407
[621]	validation_0-mape:0.61381
[622]	validation_0-mape:0.61367
[623]	validation_0-mape:0.61341
[624]	validation_0-mape:0.61307
[625]	validation_0-mape:0.61296
[626]	validation_0-mape:0.61289
[627]	validation_0-mape:0.61285

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.6720743179899686, device=None,
             early_stopping_rounds=15, enable_categorical=True,
             eval_metric='mape', feature_types=None, feature_weights=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.013815876417793225,
             max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=3, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=2000, n_jobs=None,
             num_parallel_tree=None, ...)

In [5]:
y_train_pred = xgb_regressor.predict(X_train)
y_test_pred = xgb_regressor.predict(X_test)
y_val_pred = xgb_regressor.predict(X_val)

In [6]:
response_train = pd.concat([players_train, pd.Series(y_train_pred, name='Value_pred'), y_train], axis=1)
response_test = pd.concat([players_test, pd.Series(y_test_pred, name='Value_pred'), y_test], axis=1)
response_val = pd.concat([players_val, pd.Series(y_val_pred, name='Value_pred'), y_val], axis=1)

In [7]:
response_train_val = pd.concat([response_train, response_val])
response = pd.concat([response_train_val, response_test])

In [14]:
metrics = pd.DataFrame({
    'MAE':[mae(y_test_pred, y_test), mae(y_train_pred, y_train), mae(y_val_pred, y_val)],
    'RMSE':[rmse(y_test_pred, y_test), rmse(y_train_pred, y_train), rmse(y_val_pred, y_val)],
    'MAPE':[mape(y_test_pred, y_test), mape(y_train_pred, y_train), mape(y_val_pred, y_val)],
    'R2': [r2_score(y_test_pred, y_test), r2_score(y_train_pred, y_train), r2_score(y_val_pred, y_val)]
}, index = ['test', 'train', 'val'])

In [9]:
metrics

            MAE      RMSE      MAPE        R2
test   2.905539  6.013835  0.428165  0.727555
train  2.266067  4.912500  0.296498  0.876470
val    3.183195  7.026591  0.416339  0.647419

# Анализ результатов по позициям

## Нападающие (FW)

In [11]:
y_test_pred_fw = y_test_pred[players_test['Pos']=='FW']
y_train_pred_fw = y_train_pred[players_train['Pos']=='FW']
y_val_pred_fw = y_val_pred[players_val['Pos']=='FW']

y_test_fw = y_test[players_test['Pos']=='FW']
y_train_fw = y_train[players_train['Pos']=='FW']
y_val_fw = y_val[players_val['Pos']=='FW']

In [16]:
metrics_fw = pd.DataFrame({
    'MAE':[mae(y_test_pred_fw, y_test_fw), mae(y_train_pred_fw, y_train_fw), mae(y_val_pred_fw, y_val_fw)],
    'RMSE':[rmse(y_test_pred_fw, y_test_fw), rmse(y_train_pred_fw, y_train_fw), rmse(y_val_pred_fw, y_val_fw)],
    'MAPE':[mape(y_test_pred_fw, y_test_fw), mape(y_train_pred_fw, y_train_fw), mape(y_val_pred_fw, y_val_fw)],
    'R2': [r2_score(y_test_pred_fw, y_test_fw), r2_score(y_train_pred_fw, y_train_fw), r2_score(y_val_pred_fw, y_val_fw)]
}, index = ['test', 'train', 'val'])

In [17]:
metrics_fw

            MAE       RMSE      MAPE        R2
test   3.790856   8.040339  0.453851  0.704871
train  2.894789   6.941834  0.288439  0.876322
val    4.859196  10.670237  0.444976  0.339516

## Атакующие полузащитники (FW,MF)

In [20]:
y_test_pred_fw = y_test_pred[players_test['Pos']=='FW,MF']
y_train_pred_fw = y_train_pred[players_train['Pos']=='FW,MF']
y_val_pred_fw = y_val_pred[players_val['Pos']=='FW,MF']

y_test_fw = y_test[players_test['Pos']=='FW,MF']
y_train_fw = y_train[players_train['Pos']=='FW,MF']
y_val_fw = y_val[players_val['Pos']=='FW,MF']

In [21]:
metrics_fw = pd.DataFrame({
    'MAE':[mae(y_test_pred_fw, y_test_fw), mae(y_train_pred_fw, y_train_fw), mae(y_val_pred_fw, y_val_fw)],
    'RMSE':[rmse(y_test_pred_fw, y_test_fw), rmse(y_train_pred_fw, y_train_fw), rmse(y_val_pred_fw, y_val_fw)],
    'MAPE':[mape(y_test_pred_fw, y_test_fw), mape(y_train_pred_fw, y_train_fw), mape(y_val_pred_fw, y_val_fw)],
    'R2': [r2_score(y_test_pred_fw, y_test_fw), r2_score(y_train_pred_fw, y_train_fw), r2_score(y_val_pred_fw, y_val_fw)]
}, index = ['test', 'train', 'val'])

In [22]:
metrics_fw

            MAE      RMSE      MAPE        R2
test   2.309912  4.278449  0.367058  0.931342
train  2.100730  4.330883  0.284579  0.915150
val    3.241190  6.150671  0.494321  0.750069

## Фланговые нападающие (MF,FW)

In [23]:
y_test_pred_fw = y_test_pred[players_test['Pos']=='MF,FW']
y_train_pred_fw = y_train_pred[players_train['Pos']=='MF,FW']
y_val_pred_fw = y_val_pred[players_val['Pos']=='MF,FW']

y_test_fw = y_test[players_test['Pos']=='MF,FW']
y_train_fw = y_train[players_train['Pos']=='MF,FW']
y_val_fw = y_val[players_val['Pos']=='MF,FW']

In [24]:
metrics_fw = pd.DataFrame({
    'MAE':[mae(y_test_pred_fw, y_test_fw), mae(y_train_pred_fw, y_train_fw), mae(y_val_pred_fw, y_val_fw)],
    'RMSE':[rmse(y_test_pred_fw, y_test_fw), rmse(y_train_pred_fw, y_train_fw), rmse(y_val_pred_fw, y_val_fw)],
    'MAPE':[mape(y_test_pred_fw, y_test_fw), mape(y_train_pred_fw, y_train_fw), mape(y_val_pred_fw, y_val_fw)],
    'R2': [r2_score(y_test_pred_fw, y_test_fw), r2_score(y_train_pred_fw, y_train_fw), r2_score(y_val_pred_fw, y_val_fw)]
}, index = ['test', 'train', 'val'])

In [25]:
metrics_fw

            MAE      RMSE      MAPE        R2
test   2.744889  6.240373  0.378736  0.522664
train  2.137272  4.867549  0.264102  0.874488
val    2.371221  3.843063  0.484041  0.943911

## Полузащитники (MF)

In [26]:
y_test_pred_fw = y_test_pred[players_test['Pos']=='MF']
y_train_pred_fw = y_train_pred[players_train['Pos']=='MF']
y_val_pred_fw = y_val_pred[players_val['Pos']=='MF']

y_test_fw = y_test[players_test['Pos']=='MF']
y_train_fw = y_train[players_train['Pos']=='MF']
y_val_fw = y_val[players_val['Pos']=='MF']

In [27]:
metrics_fw = pd.DataFrame({
    'MAE':[mae(y_test_pred_fw, y_test_fw), mae(y_train_pred_fw, y_train_fw), mae(y_val_pred_fw, y_val_fw)],
    'RMSE':[rmse(y_test_pred_fw, y_test_fw), rmse(y_train_pred_fw, y_train_fw), rmse(y_val_pred_fw, y_val_fw)],
    'MAPE':[mape(y_test_pred_fw, y_test_fw), mape(y_train_pred_fw, y_train_fw), mape(y_val_pred_fw, y_val_fw)],
    'R2': [r2_score(y_test_pred_fw, y_test_fw), r2_score(y_train_pred_fw, y_train_fw), r2_score(y_val_pred_fw, y_val_fw)]
}, index = ['test', 'train', 'val'])

In [28]:
metrics_fw

            MAE      RMSE      MAPE        R2
test   3.039243  5.288789  0.465426  0.762898
train  2.498379  5.318811  0.298413  0.871665
val    2.850886  5.753353  0.352002  0.770012

## Опорные полузащитники и латтерали (MF,DF)

In [29]:
y_test_pred_fw = y_test_pred[players_test['Pos']=='MF,DF']
y_train_pred_fw = y_train_pred[players_train['Pos']=='MF,DF']
y_val_pred_fw = y_val_pred[players_val['Pos']=='MF,DF']

y_test_fw = y_test[players_test['Pos']=='MF,DF']
y_train_fw = y_train[players_train['Pos']=='MF,DF']
y_val_fw = y_val[players_val['Pos']=='MF,DF']

In [30]:
metrics_fw = pd.DataFrame({
    'MAE':[mae(y_test_pred_fw, y_test_fw), mae(y_train_pred_fw, y_train_fw), mae(y_val_pred_fw, y_val_fw)],
    'RMSE':[rmse(y_test_pred_fw, y_test_fw), rmse(y_train_pred_fw, y_train_fw), rmse(y_val_pred_fw, y_val_fw)],
    'MAPE':[mape(y_test_pred_fw, y_test_fw), mape(y_train_pred_fw, y_train_fw), mape(y_val_pred_fw, y_val_fw)],
    'R2': [r2_score(y_test_pred_fw, y_test_fw), r2_score(y_train_pred_fw, y_train_fw), r2_score(y_val_pred_fw, y_val_fw)]
}, index = ['test', 'train', 'val'])

In [31]:
metrics_fw

            MAE       RMSE      MAPE        R2
test   2.639724   6.180886  0.407736  0.795008
train  1.626191   3.646274  0.307777  0.911507
val    4.536350  13.168679  0.290881  0.422947

## Фланговые защитники (DF,MF)

In [32]:
y_test_pred_fw = y_test_pred[players_test['Pos']=='DF,MF']
y_train_pred_fw = y_train_pred[players_train['Pos']=='DF,MF']
y_val_pred_fw = y_val_pred[players_val['Pos']=='DF,MF']

y_test_fw = y_test[players_test['Pos']=='DF,MF']
y_train_fw = y_train[players_train['Pos']=='DF,MF']
y_val_fw = y_val[players_val['Pos']=='DF,MF']

In [33]:
metrics_fw = pd.DataFrame({
    'MAE':[mae(y_test_pred_fw, y_test_fw), mae(y_train_pred_fw, y_train_fw), mae(y_val_pred_fw, y_val_fw)],
    'RMSE':[rmse(y_test_pred_fw, y_test_fw), rmse(y_train_pred_fw, y_train_fw), rmse(y_val_pred_fw, y_val_fw)],
    'MAPE':[mape(y_test_pred_fw, y_test_fw), mape(y_train_pred_fw, y_train_fw), mape(y_val_pred_fw, y_val_fw)],
    'R2': [r2_score(y_test_pred_fw, y_test_fw), r2_score(y_train_pred_fw, y_train_fw), r2_score(y_val_pred_fw, y_val_fw)]
}, index = ['test', 'train', 'val'])

In [34]:
metrics_fw

            MAE      RMSE      MAPE        R2
test   1.959000  3.331735  0.531966  0.684551
train  1.698780  2.985250  0.294956  0.871001
val    2.077491  5.194981  0.336193  0.780868

## Защитники (DF)

In [35]:
y_test_pred_fw = y_test_pred[players_test['Pos']=='DF']
y_train_pred_fw = y_train_pred[players_train['Pos']=='DF']
y_val_pred_fw = y_val_pred[players_val['Pos']=='DF']

y_test_fw = y_test[players_test['Pos']=='DF']
y_train_fw = y_train[players_train['Pos']=='DF']
y_val_fw = y_val[players_val['Pos']=='DF']

In [36]:
metrics_fw = pd.DataFrame({
    'MAE':[mae(y_test_pred_fw, y_test_fw), mae(y_train_pred_fw, y_train_fw), mae(y_val_pred_fw, y_val_fw)],
    'RMSE':[rmse(y_test_pred_fw, y_test_fw), rmse(y_train_pred_fw, y_train_fw), rmse(y_val_pred_fw, y_val_fw)],
    'MAPE':[mape(y_test_pred_fw, y_test_fw), mape(y_train_pred_fw, y_train_fw), mape(y_val_pred_fw, y_val_fw)],
    'R2': [r2_score(y_test_pred_fw, y_test_fw), r2_score(y_train_pred_fw, y_train_fw), r2_score(y_val_pred_fw, y_val_fw)]
}, index = ['test', 'train', 'val'])

In [37]:
metrics_fw

            MAE      RMSE      MAPE        R2
test   3.017523  6.469540  0.427959  0.474212
train  2.116377  4.135880  0.307965  0.842261
val    3.062153  6.615084  0.419666  0.466142